### ISSUE TITLE
AWSMobileclient Transferutility Image upload. Access Denied when I use Cannedcontrollist for public access 

### ISSUE THREAD

**Issue by chikason** [aws-amplify/aws-sdk-android#1213] opened 2019-09-22 13:19 UTC
** Access Denied when I use CannedAccesscontrollist for public access but works after removing the  CannedAccessControlList **

*AWS Amplify **

AWSMobileclient Transferutility Image upload. Access Denied when I use Cannedcontrollist to public access 

 TransferUtility transferUtility = TransferUtility.builder()
                        .context(getActivity().getApplicationContext())
                        .awsConfiguration(AWSMobileClient.getInstance().getConfiguration())
                        .s3Client(new AmazonS3Client(AWSMobileClient.getInstance()))
                        .build();

        TransferObserver observer = transferUtility.upload("public/" + path, f,  CannedAccessControlList.PublicReadWrite);
                         observer.setTransferListener(new TransferListener() {
                             @Override
                             public void onStateChanged(int id, TransferState state) {
                                 
                             }

                             @Override
                             public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
                                 
                             }

                             @Override
                             public void onError(int id, Exception ex) {
                                 
                             }
                         });

 **aws android - SDK Version: 2.13.0**

**Comment by TrekSoft** [comment] 2019-09-27 18:34
Hey Chikason,

Just reproduced the issue on my end so investigating it now.

**Comment by TrekSoft** [comment] 2019-09-27 20:24
Alright so here's what's happening. When you setup storage and authentication through the Amplify CLI, it creates IAM policies which set the following default permissions (if you give the full permissions to auth and guest users during the CLI setup process):

- Anything uploaded to the public folder can be read/write/deleted by both authenticated and guest users (however, those guest users will still need to be coming from an app using Cognito as unauthenticated users)

- Protected / Private have more restrictive permissions I won't get into since you're case is public.

If this fits your use case, great. However, if you specifically want anyone anywhere to be able to read and write to your file (e.g. access it through a browser link), you would need to add the CannedAccessControlList variable you mentioned you were trying to add.

The reason this is failing is because the Amplify CLI doesn't give permissions to anyone to add custom ACL policy on an object. To change this, you can open your AWS console, go to IAM, select Roles, filter for authRole and find the policies which have your app name + authRole and unauthRole, for each one find the Public_policy, Edit Policy, expand S3, expand Actions, expand Permissions management, and check PutObjectAcl and PutObjectVersionAcl. Then review the policy and save.

To help us decide whether to make this permission accessible without needing this workaround, what is your use case that you are wanting to add the PublicReadWrite policy for?

**Comment by chikason** [comment] 2019-09-28 20:18
Ok.  I thought that the public means anywhere no matter where the request is coming from.
I later use or write policy that gave public access on the bucket without knowing that the App could access it.
But tell me,  in the app I wouldn't download the App using AWSMobileclient but access it using image processing library like Glide. My question is will it recognize the call made through this Api or library in my App?

**Comment by TrekSoft** [comment] 2019-09-30 13:36
Ok, how are you going to get the link to pass to Glide?

**Comment by chikason** [comment] 2019-09-30 19:15
Knowing the actually address of the bucket. Each time I am uploading a file  I construct a URL linking the file using filepath. I'll first of all get the extension of the file ( i.e .MP4 ) and use it to build the filepath with whatsoever I chose to name the file.  And after that, I save it on database.

**Comment by TrekSoft** [comment] 2019-09-30 19:57
Gotcha - ok yeah it wouldn't be able to access it. So for now you should use the override I mentioned to be able to set the ACL policy as you were trying to do.

**Comment by TrekSoft** [comment] 2019-09-30 19:58
Or, you can use the GeneratePresignedURL method from the S3 Client to get a URL you could save in your database that would be accessible even with the current default public folder settings:

https://docs.aws.amazon.com/code-samples/latest/catalog/java-s3-src-main-java-GeneratePresignedURL.java.html

**Comment by TrekSoft** [comment] 2019-10-01 20:49
Closing this issue for now - feel free to reopen if you have any more questions.

**Closed by TrekSoft** 2019-10-01 20:49 UTC
Labels: Question, Requesting Feedback, S3
