### ISSUE TITLE
TransferNetworkLossHandler can crash the thread when using a poor network connection

### ISSUE THREAD

**Issue by alex-pathspot** [aws-amplify/aws-sdk-android#1289] opened 2019-11-01 16:03 UTC
**Describe the bug**
TransferNetworkLossHandler is crashing on an illegal state exception when the network connection is poor.
```
java.lang.IllegalStateException
Couldn't read row 988, col 0 from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from it.
android.database.CursorWindow.nativeGetLong (CursorWindow.java)
android.database.CursorWindow.getLong + 511 (CursorWindow.java:511)
android.database.CursorWindow.getInt + 578 (CursorWindow.java:578)
android.database.AbstractWindowedCursor.getInt + 84 (AbstractWindowedCursor.java:84)
com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler.resumeAllTransfersOnNetworkAvailability + 171 (TransferNetworkLossHandler.java:171)
com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler.access$000 + 37 (TransferNetworkLossHandler.java:37)
com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler$1.run + 123 (TransferNetworkLossHandler.java:123)
java.lang.Thread.run + 761 (Thread.java:761)
```
**To Reproduce**
1. Use a slow network connection (~100kbps)
1. Attempt to upload files to s3.
1. on upload failure, terminate TransferUtility and create a new instance for when the network reconnects.

**Which AWS service(s) are affected?**
S3

**Expected behavior**
Failures in the TransferUtility should not terminate the thread via an uncaught exception. The transfer utility should close gracefully. 

**Screenshots**
N/A

**Environment Information:**
 - AWS Android SDK Version: 2.16.1
 - Android Version: 7.0
 - Specific to simulators:  Unknown

**Additional context**
The exception is being caught with:
```
 Thread.setDefaultUncaughtExceptionHandler(Thread.UncaughtExceptionHandler);
```

**Comment by TrekSoft** [comment] 2019-11-01 18:33
Could you post the code snippet from the customer performing the steps To Reproduce? I'm curious about step 3 in your "To Reproduce" section - they shouldn't be creating a new instance of TransferUtility when there's a network disruption. It's built to automatically handle network disruptions and finish the upload.

**Comment by raphkim** [comment] 2019-11-05 00:23
Hi, I investigated and documented this issue in #1006. 

Automatically handling transfer failure from poor network is a feature that isn't supported by `TransferUtility` at the moment. `TransferNetworkLossHandler` automatically handles exceptions thrown when it detects that the device's connection state is "off", which wouldn't be the case if the connection is simply slow. 

Thankfully, even if a transfer was interrupted by poor connection, the transferred data will persist for some time so that it can be resumed manually without loss of data.

**Comment by alex-pathspot** [comment] 2019-11-06 15:05
The issue appears to occur when a paused transfer utility is abandoned for garbage collection, and then the network resumes.

There was a flaw in the code that first abandoned the object before cancelling all transfers. Essentially the flow was the following

```
TransferUtility tu = new TransferUtility();
tu.upload(file)
//Network disconnect
tu = null;
try {
     tu.cancelAllWithType(TransferType.ANY);
}catch (NullPointerException){}
// Network Resumes
tu = new TransferUtility();
```

Replacing the above with the following appears to mitigate the crash
```
TransferUtility tu = new TransferUtility();
tu.upload(file)
//Network disconnect
tu.cancelAllWithType(TransferType.ANY);
tu = null;
// Network Resumes
tu = new TransferUtility();
```

This could indicate a possible race condition on network resume and transferutility garbage collection.

**Comment by kvasukib** [comment] 2019-11-06 17:31
@alex-pathspot What is the reason to set `tu = null`? and recreate new `TransferUtility` instances. We recommend to use one `Transferutility` instance for the lifecycle of the app without re-creating it.

**Comment by alex-pathspot** [comment] 2019-11-06 17:38
We create a new TransferUtility on loss of network, because we create a new session on any network failure.

**Comment by kvasukib** [comment] 2019-11-06 17:50
@alex-pathspot You do not have to re-create `Transferutility` instances on any event. The network loss handling is done by `TransferNetworkLossHandler` and `TransferService` whose lifecycle is the lifecycle of the app and is a standalone component which is de-coupled from `TransferUtility`.

We recommend not to re-create different `TransferUtility` instances and just have one for the app.

**Comment by alex-pathspot** [comment] 2019-11-06 17:55
What is the best way to handle session credentials expiring then?

**Comment by kvasukib** [comment] 2019-11-06 18:00
@alex-pathspot If session credentials expire during the course of a transfer, you would receive a `onFailure` callback. Upon `onFailure`, you can resume the transfer or start an other transfer for the same S3 key.

Please correct me if I'm understanding the session credentials problem correctly.

**Comment by alex-pathspot** [comment] 2019-11-07 15:11
Note we are fetching our s3 credentials via the method outlined in the following blog post. However the role associated provides s3 access, not dynamoDB access. 

https://aws.amazon.com/blogs/security/how-to-eliminate-the-need-for-hardcoded-aws-credentials-in-devices-by-using-the-aws-iot-credentials-provider/

**Comment by raphkim** [comment] 2019-11-07 23:54
May I ask which implementation of `AWSCredentialsProvider` you are using to instantiate your `AmazonS3Client` object? Ideally, you should manage your credentials directly from the provider rather than creating a new instance of S3 client each time.

**Comment by alex-pathspot** [comment] 2019-11-08 15:34
We were manually creating a `BasicSessionCredentials` from the HTTP reply to our https credential endpoint that is authenticated using our IOT core private keys. What is the correct `AWSCredentialsProvider` for this scenario?

**Comment by raphkim** [comment] 2019-11-08 22:41
Using `BasicSessionCredentials` is not a recommended practice. I suggest that you use something along the line of this:

```
CognitoCachingCredentialsProvider provider = new CognitoCachingCredentialsProvider(
    context,
    identityPoolId,
    Regions.US_EAST_1);
```

Credentials providers such as above can be used to instantiate S3 clients.

Or is there any specific use-case for using IOT service over Cognito to obtain credentials?

**Comment by alex-pathspot** [comment] 2019-11-08 22:49
The [amazon blogpost](https://aws.amazon.com/blogs/security/how-to-eliminate-the-need-for-hardcoded-aws-credentials-in-devices-by-using-the-aws-iot-credentials-provider/) and IOT core do not require cognito to fetch the STS credentials. I wrote my own `CredentialsProvider` that extends the base class that fetches the credentials via the HTTPS request outlined in that post.

It seems like the SDK is missing an implementation of an `IOTCredentialsProvider` for this use case. 

Using my implementation of `IOTCredentialsProvider` we are now maintaining one `TransferUtility` for the duration of the application.

**Comment by raphkim** [comment] 2019-11-09 00:06
Does your app use IOT as its core functionality? Otherwise, we strongly recommend that you look into Cognito as your method of authentication, as the SDK currently does not support authentication via IOT core.

**Comment by alex-pathspot** [comment] 2019-11-09 00:14
Yes it uses IOT as it's core functionality.

**Comment by raphkim** [comment] 2020-04-14 18:43
Closing due to inactivity. Please feel free to re-open this issue if necessary.

**Closed by raphkim** 2020-04-14 18:43 UTC
Labels: Bug, S3
