### ISSUE TITLE
App crashes after sometime with keystore error

### ISSUE THREAD

**Issue by imsipl** [aws-amplify/aws-sdk-android#2350] opened 2021-02-02 07:40 UTC
I am getting error from my mobile app when i tried to connect aws.
Initially App will work for sometime, this problem occurs if try to logout, or reinstall the application or randomly 
Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias

**Comment by richardmcclellan** [comment] 2021-07-21 15:43
Closing as duplicate of https://github.com/aws-amplify/aws-sdk-android/issues/1346.  Please see the potential solution described on that ticket.

**Closed by richardmcclellan** 2021-07-21 15:43 UTC
