### ISSUE TITLE
AWSMobileClient#initialize should be performed synchronously

### ISSUE THREAD

**Issue by monae** [aws-amplify/aws-sdk-android#2567] opened 2021-08-06 08:51 UTC
**Which AWS Services is the feature request for?**
aws-android-sdk-mobile-client

**Is your feature request related to a problem? Please describe.**
Consider following Android app code:
```kotlin
class MyApp : Application() {
    override fun onCreate() {
        super.onCreate()
        AWSMobileClient.getInstance().initialize(this, callback)
    }
}

class IntentHandlingActivity : Activity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        AWSMobileClient.getInstance().handleAuthResponse(intent)
    }
}
```

It has potential bug of losing obtained tokens because if the app process was killed and restored during the user's browser operation, handleAuthResponse may be called before async initialization was completed, i.e., its fields `hostedUI` and `mOAuth2Client` may be null.
You can avoid these uninitialized operations by waiting for the callback to be called, but it's painful and unintuitive.

**Describe the solution you'd like**
Loading configuration files and SharedPreferences doesn't need to be async.
I want synchronous version of AWSMobileClient#initialize method.

**Comment by monae** [comment] 2021-08-10 05:47
This kind of bug is also found in the official documentation: https://docs.amplify.aws/sdk/auth/hosted-ui/q/platform/android

**Comment by eeatonaws** [comment] 2022-05-27 21:52
Closing this issue as it is a duplicate of #1145. Please see issue #1145 for any updates.

**Closed by eeatonaws** 2022-05-27 21:52 UTC
Labels: duplicate, mobile client, improvement
