### ISSUE TITLE
User pool federation with hosted UI, "AuthNavigationException: user cancelled" always thrown before onSuccess  and when using in flugin flutter, it always return "User cancelled " and state "SIGN_OUT"

### ISSUE THREAD

**Issue by namanh007** [aws-amplify/aws-sdk-android#1083] opened 2019-07-23 09:25 UTC
**Describe the bug**

```
E/: [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
E/LOGIN: onError: 
    com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthNavigationException: user cancelled
        at com.amazonaws.mobileconnectors.cognitoauth.AuthClient$4.onNavigationEvent(AuthClient.java:624)
        at androidx.browser.customtabs.CustomTabsClient$2$1.run(CustomTabsClient.java:200)
        at android.os.Handler.handleCallback(Handler.java:891)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

**Gradle**

```
group 'com.flutter.master.flutter_plugin_hosted_ui'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '1.3.41'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.amazonaws:aws-android-sdk-appsync-gradle-plugin:2.9.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        jcenter()
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'com.amazonaws.appsync'

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    defaultConfig {
        minSdkVersion 23
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    //For AWSMobileClient only:
    implementation ('com.amazonaws:aws-android-sdk-mobile-client:2.13.+@aar') { transitive = true }
//For the drop-in UI also:
    implementation 'com.amazonaws:aws-android-sdk-auth-userpools:2.13.7'
    implementation 'com.amazonaws:aws-android-sdk-auth-ui:2.13.7'
    implementation("com.amazonaws:aws-android-sdk-cognitoauth:2.13.+@aar") { transitive = true }
    //Base SDK
    implementation 'com.amazonaws:aws-android-sdk-core:2.13.7'
    //AppSync SDK
    implementation 'com.amazonaws:aws-android-sdk-appsync:2.9.0'
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.1'
    implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'
    implementation 'com.google.android.gms:play-services-auth:17.0.0'
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'com.google.code.gson:gson:2.8.5'
}
```

**Comment by desokroshan** [comment] 2019-07-24 22:49
@namanh007 Thanks for reaching out. Can you please share more details : 

1. Set of steps to reproduce the issue
2. Relevant code sample
3. Which SDK and version are you working with. 

Thanks!

**Comment by desokroshan** [comment] 2019-07-31 16:42
@namanh007 Can you to reproduce this issue in the [cognito auth sample app](https://github.com/awslabs/aws-sdk-android-samples/tree/master/AmazonCognitoAuthDemo). That will help us root cause and fix the issue.

**Comment by AnhDTN** [comment] 2019-08-13 04:25
> @namanh007 Can you to reproduce this issue in the [cognito auth sample app](https://github.com/awslabs/aws-sdk-android-samples/tree/master/AmazonCognitoAuthDemo). That will help us root cause and fix the issue.

hello, sorry for the late

**Comment by AnhDTN** [comment] 2019-08-13 04:25
please check my git hub 
https://github.com/AnhDTN/demo_aws_hostedUI.git

**Comment by AnhDTN** [comment] 2019-08-13 04:31
this is project sample i create, please login with google(may be get exception "USER CANCEL") and then click addattribute, this get exception com.amazonaws.services.cognitoidentityprovider.model.NotAuthorizedException: Access Token does not have required scopes (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 3827ffad-049b-4305-be64-390dea0badc6)
Please check and tell my why :( thank you

**Comment by AnhDTN** [comment] 2019-08-14 02:41
@desokroshan  hello, i am namanh007. my problem just when login with facebook and google first time always get error "User cancel" but user state is "SIGN_IN". Please skip error getAttribute because i fixed

**Comment by AnhDTN** [comment] 2019-08-14 03:26
please check with google account, because i'm lose account test for facebook

**Comment by raphkim** [comment] 2020-01-24 18:57
closing in favor of #871

**Closed by raphkim** 2020-01-24 18:57 UTC
Labels: AWSMobileClient, Bug, Duplicate
