### ISSUE TITLE
Failed to execute HTTP call

### ISSUE THREAD

**Issue by bhavik45** [aws-amplify/aws-sdk-android#2746] opened 2021-12-16 13:40 UTC
**Failed to execute HTTP call**
We are facing a ”Failed to execute HTTP call” error with Cognito. I’m calling the sign-in method of Cognito and on the login success, I’m trying to fetch user details from the dynamo DB. In this API call, it goes for checking the session and it’s returning an error from there. The login is giving a successful response but still, it’s giving the above error on the next dynamo call. 

**Note- This is occurring only on a specific device.**

**Environment Information:**
 - AWS Android SDK Version: 2.22.6 and 2.35.0
 - Device: Samsung Galaxy S21 5G
 - Android Version: 11
 - Specific to simulators: No

**Code sample**
````
suspend fun CognitoUser.initiateUserAuthentication(mobileNo: String, password: String) = withContext(Dispatchers.IO) {
    suspendCoroutine<CognitoUserSession?> { cont ->

        initiateUserAuthentication(
            AuthenticationDetails(mobileNo, password, null), object : AuthenticationHandler {

                override fun onSuccess(
                    userSession: CognitoUserSession?,
                    newDevice: CognitoDevice?
                ) {
                    cont.resume(userSession)
                }

                override fun getAuthenticationDetails(
                    authenticationContinuation: AuthenticationContinuation?,
                    userId: String?
                ) {
                    val authenticationDetails = AuthenticationDetails(mobileNo, password, null)
                    authenticationContinuation?.setAuthenticationDetails(authenticationDetails)
                    authenticationContinuation?.continueTask()
                }

                override fun getMFACode(continuation: MultiFactorAuthenticationContinuation?) {
                }

                override fun authenticationChallenge(continuation: ChallengeContinuation?) {
                }

                override fun onFailure(exception: Exception) {
                    cont.resumeWithException(exception)
                }
            },
            false
        ).run()
    }
}
````

````
 private suspend fun getUserData(
        userSession: CognitoUserSession?,
        deviceKey: String?,
        userPool: CognitoUserPool,
        countryCode: String,
        phoneNumber: String,
        config: AWSConfiguration,
    ) {

        val phone = phoneNumber
        val mobileNo = countryCode.plus(phone)

        val deviceId = Settings.Secure.getString(application.contentResolver, Settings.Secure.ANDROID_ID)

        val client: AWSAppSyncClient = ClientFactory.getInstance(application, userPool, config)

        userSession?.let {

            try {

                val response = client.awaitQuery(userQuery)

                if (!response.hasErrors()) {

                // our stuff

                } else {
                    FirebaseCrashlytics.getInstance().recordException(Exception(response.errors().toString()))
                    networkStatus.postValue(NetworkStatus.Error(response.errors().firstOrNull()?.message() ?: "Error Occurred."))
                }

            } catch (e: Exception) {

                FirebaseCrashlytics.getInstance().recordException(Exception("getUserData ", e)) //here we got the log which is maintaion below

                networkStatus.postValue(NetworkStatus.Error(e.message ?: "Error Occurred."))
                signInStatus.postValue(SignInStatus.Failure(e))

            }

        }

    }
````

**Complete stack trace**
````
Non-fatal Exception: java.lang.Exception: getUserData 
       at com.app.ht.repository.SignInRepository.getUserData(SignInRepository.java:330)
       at com.app.ht.repository.SignInRepository.access$getUserData(SignInRepository.java:48)
       at com.app.ht.repository.SignInRepository$getUserData$1.invokeSuspend(SignInRepository.java:1)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:104)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
````

````
Caused by b.d.a.h.d: Failed to execute http call
       at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onFailure(ApolloServerInterceptor.java:95)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:525)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
````

````
Caused by java.io.IOException: Failed to retrieve Cognito User Pools token.
       at com.amazonaws.mobileconnectors.appsync.sigv4.AppSyncSigV4SignerInterceptor.intercept(AppSyncSigV4SignerInterceptor.java:165)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at com.amazonaws.mobileconnectors.appsync.retry.RetryInterceptor.intercept(RetryInterceptor.java:40)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.java:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
````

````
Caused by b.a.a.f.b: Cognito Userpools is not signed-in - AuthenticationDetails
       at com.app.ht.aws.cognito.HBasicCognitoUserPoolsAuthProvider.fetchToken(HBasicCognitoUserPoolsAuthProvider.java:83)
       at com.app.ht.aws.cognito.HBasicCognitoUserPoolsAuthProvider.getLatestAuthToken(HBasicCognitoUserPoolsAuthProvider.java:91)
       at com.amazonaws.mobileconnectors.appsync.sigv4.AppSyncSigV4SignerInterceptor.intercept(AppSyncSigV4SignerInterceptor.java:163)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at com.amazonaws.mobileconnectors.appsync.retry.RetryInterceptor.intercept(RetryInterceptor.java:40)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.java:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
````

**Comment by poojamat** [comment] 2021-12-17 04:46
@bhavik45 would [Fetch the current user's attributes ](https://docs.amplify.aws/lib/auth/user-attributes/q/platform/android/#fetch-the-current-users-attributes) work for you?

**Comment by bhavik45** [comment] 2021-12-17 11:28
> Could you please include your sample code?

@poojamat I have updated the ticket with the sample code.

**Comment by eeatonaws** [comment] 2022-01-05 21:05
@bhavik45, from the stack trace, it looks like the request to DynamoDB is failing because the user is not yet signed in (the sign in process may still be in progress). To sign in a user, you can use `AWSMobileClient.getInstance().signIn(...)` and in the `onResult` callback, get the user details if the sign in state is DONE. Please see sample code [here](https://docs.amplify.aws/sdk/auth/working-with-api/q/platform/android/#signin).

**Comment by bhavik45** [comment] 2022-01-12 05:45
@eeatonaws Thanks for the reply.

It’s working on all the other devices except one device. Also, It’s working well with the development instance on the same device, but the issue arises with the production instance only with the same code(in one specified device - Samsung Galaxy S21 5G).

We have used suspend method(async) for the sign-in process. So, the next call (to get user details) will only proceed once the login process is finished. Also, we tried putting some delay after login. We set delay of 3 seconds after the login call finished and then after we executed dynamo query to get the user details. But still no luck.

**Comment by gpanshu** [comment] 2022-01-13 18:10
@bhavik45 are you not able to sign in at all on that device? I have tested login on S21 5G and it works for our sample code in our documentation.

**Comment by bhavik45** [comment] 2022-01-19 09:17
@gpanshu No, Sign-in is working successfully, but right after sign-in we are making graphQL query call and that is failing with the above error. Currently, we are facing this issue on only one device.

**Comment by poojamat** [comment] 2022-01-27 02:53
Are you using the dependency: 'com.amazonaws:aws-android-sdk-appsync:[VERSION]' ?

**Comment by bhavik45** [comment] 2022-01-28 05:46
@poojamat Yes, I'm using appsync dependency. 

`com.amazonaws:aws-android-sdk-appsync:3.2.0`

**Comment by bhavik45** [comment] 2022-02-21 09:45
Please update if anyone has any idea to resolve this?

**Comment by gpanshu** [comment] 2022-02-24 14:10
Since this is happening on only one device, do you mind checking please what permissions you have provided the app. 
Here are a few debug steps you can try and message back here: 
1. Ensure your device has enough free space
2. Uninstall the app and restart the device
3. Re-install the app
4. Check the permissions in settings to make sure all permissions are granted
5. Take a capture of the logcat and share it with us here from the time the application is installed and to the time the call fails.

**Comment by bhavik45** [comment] 2022-02-25 09:14
1. Ensure your device has enough free space
    **Yes it has.**

2. Uninstall the app and restart the device and Re-install the app
    **Yes, we have already tried it.**

3. Check the permissions in settings to make sure all permissions are granted
    **Yes, we have made sure to grant all the permission and it's already granted.**

4. Take a capture of the logcat and share it with us here from the time the application is installed and to the time the call fails.
    **We can not do so as this issue is occurring on a live user's device. We have set logs on all possible failures and shared the logs above. But we can not debug the application on that device to get more details.**

_Also, the User tried resetting all the network settings but had no luck with that too._

**Comment by gpanshu** [comment] 2022-02-25 15:27
Thank you so much for providing this information @bhavik45. We will investigate to see if we can figure out what may be happening. Unfortunately since its just one device that is having the issue and we do not have access to the logs and furthermore it works on our devices here chances are its a platform issue rather than an SDK issue.

**Comment by gpanshu** [comment] 2022-03-18 14:33
Closing this issue as this works as designed in the sample app we have. 

Suggested workaround for the customer: Please include your graphql code in the sign in success callback block instead of calling it afterwards as sign in is not a synchronous call and will not block the thread hence its possible that your graphql call is being called before sign in actually succeeds.

**Closed by gpanshu** 2022-03-18 14:33 UTC
Labels: cognito, pending-response
