### ISSUE TITLE
Everytime I am signing out from a Cognito AWS Hosted UI, I can signin again without providing credentials

### ISSUE THREAD

**Issue by scayetanot** [aws-amplify/aws-sdk-android#2531] opened 2021-06-30 18:33 UTC
**Describe the bug**
When signed-out after having sign-in with Cognito hosted UI using OKTA as provider, I am able to sign-in again with providing OKTA credentials.

**To Reproduce**

1- Sign-in using Cognito Hosted-UI, and enter your OKTA credentials.

**AndroidManisfest.xml**

```
     <activity android:name="com.amazonaws.mobile.client.activities.HostedUIRedirectActivity">
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />

            <data android:scheme="myapp" />
        </intent-filter>
    </activity>
```

**Sign-In code in the activity**

```
HostedUIOptions hostedUIOptionsForOkta = HostedUIOptions.builder()
            .scopes("openid", "email", "profile", "phone")
            .identityProvider("OKTA")
            .build();

    SignInUIOptions signInUIOptions = SignInUIOptions.builder()
            .hostedUIOptions(hostedUIOptionsForOkta)
            .build();
    // 'this' refers to the current active Activity
    AWSMobileClient.getInstance().showSignIn(this, signInUIOptions, new Callback<UserStateDetails>() {
        @Override
        public void onResult(UserStateDetails details) {
                if(details != null) {
                    switch(details.getUserState()) {
                        case SIGNED_IN:
                            Timber.d("Signed in");
                            MainActivity.start(LoginActivity.this);
                            finish();
                        default:
                            Timber.d("Signed-in onResult state: %s", details.getUserState());
                    }
                }
            }

        @Override
        public void onError(Exception e) {
            Timber.e( e,"Sign-in error");
        }
    });
```

2- Once Okta credentials are granted, `MainActivity` is started
3- Sign-out of the application using the code below:

```
AWSMobileClient.getInstance().signOut(SignOutOptions.builder().invalidateTokens(true).build(), new Callback<Void>() {
            @Override
            public void onResult(Void result) {
                AwsIotShadowHelper.clearSession();
                LoginActivity.start(SettingsActivity.this);
                runOnUiThread(() -> {
                    closeWaitDialog();
                    finish();
                });
            }

            @Override
            public void onError(Exception e) {
                Timber.e(e, "signOutFromSSO - onError: ");
                runOnUiThread(() ->
                        Toast.makeText(SettingsActivity.this, "Error during Sign-out: " + e.getMessage()
                                , Toast.LENGTH_SHORT).show());

            }
        });
```

4- The application is signed-out and back to the login screen
5- trigger the Sign-in with Okta again, an error message is returned from the SignIn as `invalid_grant`. the app stay on the Login page
6- trigger the Sign-in wit Okta again, the app logged in with asking the credentials

**Which AWS service(s) are affected?**
AWS Cognito Hosted UI

**Expected behavior**
When signed-out after having sign-in with Cognito hosted UI using OKTA as provider, the user must be requested to enter his/her credentials again and not be able to sign-in and bypass the input credential screen

**Screenshots**
No need

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: com.amazonaws:aws-android-sdk-cognitoauth:2.24.0
 - Device: Simulator
 - Android Version: Android 11.0 - API 30
 - Specific to simulators: both emulator and devices

**Additional context**

**Comment by richardmcclellan** [comment] 2021-07-08 19:59
This is a duplicate of https://github.com/aws-amplify/amplify-android/issues/1287.    Please follow that issue for further updates.

**Closed by richardmcclellan** 2021-07-08 19:59 UTC
Labels: bug, cognito, mobile client
