### ISSUE TITLE
AWSMobileClient getTokens is slow to return cached tokens

### ISSUE THREAD

**Issue by michatch** [aws-amplify/aws-sdk-android#1722] opened 2020-05-11 12:59 UTC
**Describe the bug**
When calling `AWSMobileClient.getInstance().getTokens()` On an initilized AWSMobileClient with a signed in user, it takes about 500ms to return the token.
I'm using this call to retrieve the JWT token with `AWSMobileClient.getInstance().getTokens().getIdToken().getTokenString()` to be able to make an authenticated API call. This adds already a lot of time to have an API response.
Is there a better way to retrieve the token?

**To Reproduce**

Using following dependencies:
- com.amazonaws:aws-android-sdk-mobile-client:2.16.12
- com.amazonaws:aws-android-sdk-cognitoauth:2.16.12@aar) { transitive = true }

Steps:
- AWSMobileClient.getInstance().initialize() 
- AWSMobileClient.getInstance().signIn()
- AWSMobileClient.getInstance().getTokens()

**Which AWS service(s) are affected?**
AWS Cognito 
Android SDK 2.16.12

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.16.12
 - Device: Samsung Galaxy Tab A
 - Android Version: 9
 - Specific to simulators: No

**Logs**
Log start when call to `getTokens()` is made.
Log ends when token was received.

```
2020-05-11 14:44:27.172 15474-15671/com.example.aws D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-05-11 14:44:27.172 15474-15671/com.example.aws D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-05-11 14:44:27.183 15474-15474/com.example.aws D/InputTransport: Input channel constructed: fd=92
2020-05-11 14:44:27.183 15474-15474/com.example.aws D/InputTransport: Input channel destroyed: fd=94
2020-05-11 14:44:27.200 15474-15671/com.example.aws D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-05-11 14:44:27.200 15474-15671/com.example.aws D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-05-11 14:44:27.225 15474-15474/com.example.aws E/ViewRootImpl: sendUserActionEvent() returned.
2020-05-11 14:44:27.229 15474-15671/com.example.aws D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-05-11 14:44:27.229 15474-15671/com.example.aws D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-05-11 14:44:27.257 15474-15671/com.example.aws D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-05-11 14:44:27.257 15474-15671/com.example.aws D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-05-11 14:44:27.280 15474-15671/com.example.aws D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-05-11 14:44:27.280 15474-15671/com.example.aws D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-05-11 14:44:27.307 15474-15671/com.example.aws D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-05-11 14:44:27.307 15474-15671/com.example.aws D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-05-11 14:44:27.328 15474-15671/com.example.aws D/AWSMobileClient: Inspecting user state details
2020-05-11 14:44:27.335 15474-15671/com.example.aws D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-05-11 14:44:27.335 15474-15671/com.example.aws D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-05-11 14:44:27.360 15474-15671/com.example.aws D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-05-11 14:44:27.360 15474-15671/com.example.aws D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-05-11 14:44:27.384 15474-15671/com.example.aws D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-05-11 14:44:27.384 15474-15671/com.example.aws D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-05-11 14:44:27.407 15474-15671/com.example.aws D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-05-11 14:44:27.407 15474-15671/com.example.aws D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-05-11 14:44:27.414 15474-15671/com.example.aws D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-05-11 14:44:27.414 15474-15671/com.example.aws D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-05-11 14:44:27.422 15474-15671/com.example.aws D/KeyProvider23: AndroidKeyStore contains keyAlias CognitoIdentityProviderCache.aesKeyStoreAlias
2020-05-11 14:44:27.422 15474-15671/com.example.aws D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-05-11 14:44:27.445 15474-15671/com.example.aws D/KeyProvider23: AndroidKeyStore contains keyAlias CognitoIdentityProviderCache.aesKeyStoreAlias
2020-05-11 14:44:27.445 15474-15671/com.example.aws D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-05-11 14:44:27.471 15474-15671/com.example.aws D/KeyProvider23: AndroidKeyStore contains keyAlias CognitoIdentityProviderCache.aesKeyStoreAlias
2020-05-11 14:44:27.471 15474-15671/com.example.aws D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-05-11 14:44:27.492 15474-15671/com.example.aws D/KeyProvider23: AndroidKeyStore contains keyAlias CognitoIdentityProviderCache.aesKeyStoreAlias
2020-05-11 14:44:27.492 15474-15671/com.example.aws D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-05-11 14:44:27.515 15474-15671/com.example.aws D/AWSMobileClient: hasFederatedToken: true provider: cognito-idp.eu-west-1.amazonaws.com/eu-west-1_p*******
2020-05-11 14:44:27.516 15474-15671/com.example.aws D/AWSMobileClient: waitForSignIn: userState:SIGNED_IN
2020-05-11 14:44:27.518 15474-15671/com.example.aws D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-05-11 14:44:27.519 15474-15671/com.example.aws D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-05-11 14:44:27.541 15474-15671/com.example.aws D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-05-11 14:44:27.541 15474-15671/com.example.aws D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-05-11 14:44:27.548 15474-15671/com.example.aws D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-05-11 14:44:27.548 15474-15671/com.example.aws D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-05-11 14:44:27.556 15474-15671/com.example.aws D/KeyProvider23: AndroidKeyStore contains keyAlias CognitoIdentityProviderCache.aesKeyStoreAlias
2020-05-11 14:44:27.556 15474-15671/com.example.aws D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-05-11 14:44:27.578 15474-15671/com.example.aws D/KeyProvider23: AndroidKeyStore contains keyAlias CognitoIdentityProviderCache.aesKeyStoreAlias
2020-05-11 14:44:27.578 15474-15671/com.example.aws D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-05-11 14:44:27.601 15474-15671/com.example.aws D/KeyProvider23: AndroidKeyStore contains keyAlias CognitoIdentityProviderCache.aesKeyStoreAlias
2020-05-11 14:44:27.601 15474-15671/com.example.aws D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-05-11 14:44:27.624 15474-15671/com.example.aws D/KeyProvider23: AndroidKeyStore contains keyAlias CognitoIdentityProviderCache.aesKeyStoreAlias
2020-05-11 14:44:27.624 15474-15671/com.example.aws D/KeyProvider23: Loading the encryption key from Android KeyStore.
```

**Comment by patrickkempff** [comment] 2020-05-18 15:56
We have the same issue with receiving the cached AccessToken. On a Samsung s9 it can take sometimes around 1000ms. Also calling `currentUserState()` takes more than 300ms

We are using the latest version of the SDK, but also had issues with the previous versions of the SDK.

**Comment by CameliaTripon** [comment] 2020-05-19 07:17
Same for us. We did some kind of local caching for the token using somehow the same rule as in the SDK. The first time we call getTokens, we save the token in our in-memory cache (together with the validity date). Next time we want the token, we are asking the local cache if it has a valid token (with 55 mins default validity). If we have a valid token, we return in from our cache (takes about 1 ms), otherwise we ask the SDK (which of course can take longer since the token is expired and they need to make a request).

It's not ideal but is better then waiting for about 500ms for each request since the token is cached in their SDK anyway

**Comment by tyjaon** [comment] 2020-06-03 10:33
@CameliaTripon but still it should be optimized on the AWSMobileClient side, because on some older phones like my samsung s8 + i don't know why is taking around 1s also I don't know about you guys but sometimes retrieving fresh new token is taking about 10s.

**Comment by Dachmian** [comment] 2020-06-17 12:51
We am also experiencing this issue. 
It is really a big issue for us that this process can take up to 10s.

**Comment by tyjaon** [comment] 2020-07-03 05:27
So guys from AWS could you comment it ? or respond to it? It's 2 months since the ticket was posted. The proposed solution above it's not the solution only a bypass.

**Comment by patrickkempff** [comment] 2020-08-03 10:02
Communication from the AWS team is really poor, there are multiple issues which affect a large user base but those tickets are just ignored it seems. Not a really good motivation to work with these services from a developer perspective...

**Comment by TrekSoft** [comment] 2020-08-03 14:59
Sorry for the delay on this - looks like this is recently impacting a significant number of users so we'll be prioritizing it here.

**Comment by tyjaon** [comment] 2020-08-04 08:09
ok so i'm experiencing it on:

- Samsung Galaxy s8 + Android 9.0
- build tools version 29.0.2, SDK 29
- login method HostedUI for Facebook/Google and normal for user registered via email (situations looks the same in the booth mentioned methods)

**Comment by TrekSoft** [comment] 2020-08-04 17:19
Thanks - sorry I wasn't clear - by version of SDK I meant the version of the AWS SDK you're using. What you gave is useful too.

**Comment by TrekSoft** [comment] 2020-08-05 14:40
Also @tyjaon I tried replicating it with those same parameters in the emulator and was getting response times in less than 300ms for fresh and less than 200ms cached with the latest SDK. Does that happen for you on the emulator or only on the device? Also could you post the specific steps to replicate the latency you're seeing?

**Comment by tyjaon** [comment] 2020-08-06 14:50
@TrekSoft I didn't tried It on emulator. It have happened on couple of different devices.  
Cached Token:
I was just calling the method mentioned below on initialized AWSMobileClient and user signed in via HostedUI via facebook.  But in cached token probably sign in method  shouldn’t matter.
`AWSMobileClient.getInstance().getTokens().getIdToken();`
I have tried couple times calling it and for cached tokens It's takes at least 500ms or more. Here are the logs (from samsung galaxy s8+ mentioned by me above) .

`2020-08-06 15:58:40.306 16585-17163/app.betify.betify D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-08-06 15:58:40.306 16585-17163/app.betify.betify D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-08-06 15:58:40.341 16585-17163/app.betify.betify D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-08-06 15:58:40.341 16585-17163/app.betify.betify D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-08-06 15:58:40.361 16585-17163/app.betify.betify D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-08-06 15:58:40.361 16585-17163/app.betify.betify D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-08-06 15:58:40.385 16585-17163/app.betify.betify D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-08-06 15:58:40.385 16585-17163/app.betify.betify D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-08-06 15:58:40.411 16585-17163/app.betify.betify D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-08-06 15:58:40.411 16585-17163/app.betify.betify D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-08-06 15:58:40.436 16585-17163/app.betify.betify D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-08-06 15:58:40.436 16585-17163/app.betify.betify D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-08-06 15:58:40.457 16585-17163/app.betify.betify D/AWSMobileClient: Inspecting user state details
2020-08-06 15:58:40.463 16585-17163/app.betify.betify D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-08-06 15:58:40.463 16585-17163/app.betify.betify D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-08-06 15:58:40.488 16585-17163/app.betify.betify D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-08-06 15:58:40.488 16585-17163/app.betify.betify D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-08-06 15:58:40.511 16585-17163/app.betify.betify D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-08-06 15:58:40.511 16585-17163/app.betify.betify D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-08-06 15:58:40.535 16585-17163/app.betify.betify D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-08-06 15:58:40.535 16585-17163/app.betify.betify D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-08-06 15:58:40.561 16585-17163/app.betify.betify D/KeyProvider23: AndroidKeyStore contains keyAlias CognitoIdentityProviderCache.aesKeyStoreAlias
2020-08-06 15:58:40.561 16585-17163/app.betify.betify D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-08-06 15:58:40.591 16585-17163/app.betify.betify D/KeyProvider23: AndroidKeyStore contains keyAlias CognitoIdentityProviderCache.aesKeyStoreAlias
2020-08-06 15:58:40.591 16585-17163/app.betify.betify D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-08-06 15:58:40.616 16585-17163/app.betify.betify D/KeyProvider23: AndroidKeyStore contains keyAlias CognitoIdentityProviderCache.aesKeyStoreAlias
2020-08-06 15:58:40.616 16585-17163/app.betify.betify D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-08-06 15:58:40.640 16585-17163/app.betify.betify D/KeyProvider23: AndroidKeyStore contains keyAlias CognitoIdentityProviderCache.aesKeyStoreAlias
2020-08-06 15:58:40.640 16585-17163/app.betify.betify D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-08-06 15:58:40.664 16585-17163/app.betify.betify D/KeyProvider23: AndroidKeyStore contains keyAlias CognitoIdentityProviderCache.aesKeyStoreAlias
2020-08-06 15:58:40.664 16585-17163/app.betify.betify D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-08-06 15:58:40.689 16585-17163/app.betify.betify D/AWSMobileClient: hasFederatedToken: true provider: cognito-idp.eu-west-1.amazonaws.com/eu-west-1_8At4CGQbx
2020-08-06 15:58:40.689 16585-17163/app.betify.betify D/AWSMobileClient: waitForSignIn: userState:SIGNED_IN
2020-08-06 15:58:40.691 16585-17163/app.betify.betify D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-08-06 15:58:40.691 16585-17163/app.betify.betify D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-08-06 15:58:40.715 16585-17163/app.betify.betify D/KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.mobile.client.aesKeyStoreAlias
2020-08-06 15:58:40.715 16585-17163/app.betify.betify D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-08-06 15:58:40.736 16585-17163/app.betify.betify D/KeyProvider23: AndroidKeyStore contains keyAlias CognitoIdentityProviderCache.aesKeyStoreAlias
2020-08-06 15:58:40.736 16585-17163/app.betify.betify D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-08-06 15:58:40.762 16585-17163/app.betify.betify D/KeyProvider23: AndroidKeyStore contains keyAlias CognitoIdentityProviderCache.aesKeyStoreAlias
2020-08-06 15:58:40.762 16585-17163/app.betify.betify D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-08-06 15:58:40.800 16585-17163/app.betify.betify D/KeyProvider23: AndroidKeyStore contains keyAlias CognitoIdentityProviderCache.aesKeyStoreAlias
2020-08-06 15:58:40.800 16585-17163/app.betify.betify D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-08-06 15:58:40.842 16585-17163/app.betify.betify D/KeyProvider23: AndroidKeyStore contains keyAlias CognitoIdentityProviderCache.aesKeyStoreAlias
2020-08-06 15:58:40.843 16585-17163/app.betify.betify D/KeyProvider23: Loading the encryption key from Android KeyStore.
2020-08-06 15:58:40.875 16585-17163/app.betify.betify D/KeyProvider23: AndroidKeyStore contains keyAlias CognitoIdentityProviderCache.aesKeyStoreAlias
2020-08-06 15:58:40.875 16585-17163/app.betify.betify D/KeyProvider23: Loading the encryption key from Android KeyStore.
.txt` 


For refresh I will provide you logs and statistics on the weekend

**Comment by TrekSoft** [comment] 2020-08-06 17:35
Ok and what version of our SDK are you using?

**Comment by tyjaon** [comment] 2020-08-06 19:02
2.16.6 , I'm using exactly the same command :

`AWSMobileClient.getInstance().getTokens().getIdToken();`

**Comment by TrekSoft** [comment] 2020-08-06 19:38
Just to make sure it isn't something we've already fixed could you try it on the latest version 2.17.0? If it is device dependent it'll take me a bit to get an old device to replicate it on so want to eliminate any obvious possibilities first.

**Comment by tyjaon** [comment] 2020-08-09 05:18
@TrekSoft I have upgraded lib version to the latest version 2.17.0 and I gave it to couple people to test it in order to check if it there is any improvements. The speed of retrieving new token didn't improve at all (when I personally have checked couple times it was 4s 5s 12s, my friends have obtained similar results ), but I must say that probably the situation with the retrieving cached token has partially improved from (500 ms + ) to around 100-400, but still if this operation is based on reading from cache and decryption it should be faster.

**Comment by TrekSoft** [comment] 2020-08-10 13:58
100-400ms sounds about right - it's retrieving it from device storage so it's not going to be instantaneous. The concern is the multiple seconds taken to retrieve new tokens. What type of internet connection were you on when you were seeing these times?

**Comment by tyjaon** [comment] 2020-08-11 11:41
4G +(LTE) with almost full signal. Everything after and before this initial token generating connection is running smoothly with normal pings to the server. If you want I can check also on WiFi connection.

**Comment by TrekSoft** [comment] 2020-08-11 17:36
That's fine - thanks. If I could get input from other users here especially if anyone is getting this with a more modern device that would be great so I can replicate it.

**Comment by reku47** [comment] 2020-08-11 18:23
i have similar times like @tyjaon 
- Oneplus 7t pro (android 10)
- build tools version 29.0.3, SDK 30
- normal for user registered via email (situations looks the same in the booth mentioned methods)
- aws-mobile-client 2.17.0
- I have tested it on mobile network with 4G+ with good signal  (the other request after token refresh are going without any hude delay, so I think that it's not a network related problem, but in same cases could stack some small additional delay)

**Comment by shivaanshi** [comment] 2020-08-11 18:26
Hi, I am also facing same issue, fetching id token from session taking longer than usual, it's taking more than 10 seconds. 
Device specification -
**Honor Play, android 9**

**Comment by TrekSoft** [comment] 2020-08-11 20:46
Thanks @reku47 - @shivaanshi could you please fill out the requested information?

- the version of Android you are experiencing it on
- the version of the AWS SDK
- the sign in method you are using (HostedUI, Federated, or normal)

**Comment by tyjaon** [comment] 2020-08-12 05:20
@TrekSoft btw also 100ms-400 ms  reading from internal storage is huge waste of time I don't know exactly what you guys are doing there but normally on the shared preferences with some encryption you should waste max 10-20ms, maybe max 100ms on older phones (by older I mean phones from the really low price range like 100-200$, that are 2-4 years old).

**Comment by shivaanshi** [comment] 2020-08-12 11:29
@TrekSoft Android version is 9
'com.amplifyframework:core:1.0.0'
'com.amplifyframework:aws-auth-cognito:1.0.0'
Federate

**Comment by WillBarden** [comment] 2020-08-12 15:34
@TrekSoft Also ran into the issue. It seems that AWSKeyValueStore is only caching the tokens when persistence is disabled. However, if internal storage takes this long to read, always checking the cache could result in a large performance increase. Perhaps line 204 and 181 of the AWSKeyValueStore class could be modified to be
`if (cache.contains(dataKey) || !isPersistenceEnabled) {
       return cache.get(dataKey);
}`

**Comment by TrekSoft** [comment] 2020-08-12 16:13
Thanks for that tip @WillBarden - it does seem like attempting to black box replicate this is not the answer so once I wrap up my other task for this sprint, I'll dig into the code there and see if some obvious improvements like that can be made. 

Also thanks @shivaanshi and @tyjaon for the additional input.

**Comment by tomrapadmi** [comment] 2020-08-13 14:21
One thing that I've noticed is that the `_getTokens` Runnable calls `getCurrentUser` which always returns a new instance of a `CognitoUser`, meaning that its memory cache of `private CognitoUserSession cipSession;` is always null when checked in `getCachedSession` line 961.

**Comment by TrekSoft** [comment] 2020-08-14 15:31
Btw @WillBarden I just checked into your proposal here and it makes a ton of sense so I've already added that to my fix and will see what other improvements can be made along with it.

**Comment by TrekSoft** [comment] 2020-08-14 19:06
Alright, I found the root cause - it's the waitForSignIn() method going haywire: https://github.com/aws-amplify/aws-sdk-android/blob/main/aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/AWSMobileClient.java#L918

Actual key store retrieval is lightning fast as we'd expect but because we first check that method, it adds hundreds of milliseconds of latency to the getTokens calls. Will keep this ticket updated as I address this.

**Comment by TrekSoft** [comment] 2020-08-17 17:23
Turns out there was a very simple fix to the lag time for the cached tokens - the code was always enabling a `waitForSignIn` block so that if you happened to call getTokens while it was in the middle of signing in it would wait until the sign in process completed. This check was written very badly and included a network call leading to the lag time. So I disabled this waitForSignIn block and it will throw an error if getTokens is attempted to be called while you were signed out (regardless of whether you are in the middle of signing in or not).

This lowered latency for me retrieving cached tokens from 900ms+ to 77ms.

**Comment by tyjaon** [comment] 2020-08-17 18:05
@TrekSoft Nice improvement :) When it will be available i will try it.

**Comment by tyjaon** [comment] 2020-08-19 06:01
@TrekSoft I have checked the situation with cached token has improved, now the retrieving time is unnoticeable from the user perspective, but the request for fresh token are still too long I have tested it couple times on different devices and It took 5s, 8s , 9s, 10s.

**Comment by TrekSoft** [comment] 2020-08-19 14:06
Alright, thanks - given the original issue here is about cached tokens, I'll close this issue and if you don't mind creating a new issue with the steps to reproduce, that'd be great and I'll look into that. For everyone else's information, upgrade to 2.18.0 to resolve the issue with retrieving cached tokens taking too long.

**Closed by TrekSoft** 2020-08-19 14:06 UTC
Labels: AWSMobileClient
