### ISSUE TITLE
Uploading large files to aws s3 almost always fails.

### ISSUE THREAD

**Issue by assassinshadow0** [aws-amplify/aws-sdk-android#1947] opened 2020-06-26 05:08 UTC
**Describe the bug**
I am using the AWS S3 SDK to upload files from android. The files range from 128kb to 99 MB. Files that are less than ~20 MB gets uploaded without problems pretty easily. However, when attempting to upload larger files like 30-50MB or greater, I get time out error. 
Things I have tried -

**Editing ClientConfiguration** and setting a higher time out - Works on some phones but randomly gets timeout errors.
**Defining AmazonS3Client in application context** - Same results as above.
**Editing ClientConfiguration**  setting setSocketTimeout and setConnectionTimeout to 0 - This works ! however, the upload speed is not so good. Often times the upload just pauses for long moments (10 seconds to a whole minute give or take) and then resumes back up. 

**To Reproduce**
The code i am using -
` 
            CannedAccessControlList filePermission = CannedAccessControlList.PublicRead;

            TransferObserver observer = AppController.getInstance().getTransferUtility().upload(
                    "", //empty bucket name, included in endpoint
                    fileName,
                    new File(file), 

                    filePermission

            );

            observer.setTransferListener(new TransferListener() {
                @Override
                public void onStateChanged(int id, TransferState state)
                {

                    Log.e("TAG", state.name());

                    if (TransferState.COMPLETED.equals(state))
                    {

                        finishUp();

                    }
                    else if (TransferState.CANCELED.equals(state))
                    {
                        listener.onError(true);
                    }
                    else if (TransferState.FAILED.equals(state))
                    {

                        retryCount++;

                        if (retryCount >= 5)
                        {
                            listener.onError(true);
                        }
                        else
                        {
                            Handler handler = new Handler();
                            handler.postDelayed(new Runnable() {
                                @Override
                                public void run() {
                                    PerformUpload();
                                }
                            }, 5000);

                        }

                    }

                }

                @Override
                public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
                    final double percent = (100. * (bytesCurrent / (double) bytesTotal));

                    mBuilder.setProgress(100, (int)percent, false);

                    if (retryCount > 0)
                    {

                        mBuilder.setContentTitle("Uploading..." + total + " Retry #" + retryCount);
                    }
                    else {
                        mBuilder.setContentTitle("Uploading..." + total);
                    }

                    mNotifyManager.notify(notif, mBuilder.build());
                }

                @Override
                public void onError(int id, Exception ex) {
                    Log.e("TAG", "New Loggeed error" +ex.getMessage());

       
                }
            });
`

**Comment by raphkim** [comment] 2020-06-26 06:14
Hi @assassinshadow0 ! Thank you for using the AWS Android SDK.

The timeout error in `TransferUtility` is often a result of having faulty internet connection. Is it possible that your connection was weak?

Our network loss handler logic is currently only able to deal with a complete loss of internet connection (i.e. the wifi/data connection state is *off*), and it will successfully attempt to automatically pause and resume the transfer in such case. However, it is not equipped to detect and handle slow connection that results in a timeout, in which case the transfer fails and does *NOT* resume by itself. However, the transferred data should persist, and manually starting the transfer again should resume from where it left off. Is this true in your case?

**Comment by assassinshadow0** [comment] 2020-06-26 08:33
I can confirm that the loss handler does do as described for cases such as internet loss.
In regards to weak internet connectivity-
I have tested the above code in 3 different internet settings and performed 10 large file uploads. Ill list them below.
1) mobile 4G - Works great 8/10 times. 
2) High end wifi connection - worked 8/10
3) Low end wifi - works 2/10 times.

Although the problem is, when an upload breaks loss handler reports 0 transfers left and nothing happens after that. Although I did try to force resume an upload, but that also did work.

**Comment by jamesonwilliams** [comment] 2020-07-01 12:21
I believe this issue is true of the upstream Amplify Android project, as well.

The Storage upload tests are ignored due to routine failures.

https://github.com/aws-amplify/amplify-android/blob/main/aws-storage-s3/src/androidTest/java/com/amplifyframework/storage/s3/AWSS3StorageUploadTest.java#L57

**Comment by usmanrana07** [comment] 2020-08-20 06:22
I'm facing the same issue and different people in different areas are facing this issue although internet is working fine. Other apps and features work fine.

**Comment by SamiLakka1979** [comment] 2021-01-18 12:46
We are facing the same issue. Everything works fine when the single file size is few megabytes up to few tens of megabytes during upload. After that we receive exception. Sometimes repeating the transfer from 5-10 times helps, sometimes not. The problem is not related to network speed, but to the file size. As mentioned in the original posting, there is a workaround of sorts using setSocketTimeout and setConnectionTimeout=0. However Amplify does not provide any means for accessing these parameters. 

Any comment on this would be nice. At the moment Amplify with S3 is pretty much unusable unless the file size is relatively small.

**Comment by alokipandey-qa** [comment] 2021-02-26 03:31
hey there, I am also facing same issue while uploading large(1GB..3GB) videos to s3 from android application. I am using transfer TransferUtility w/o any custom options.
It starts uploading goes for about 20..25% then I get callback in onStateChanged() with state=TransferState.FAILED.
this is reproducible in 100% cases at my end tried with multiple devices(best spec ones)/configurations as well.
is there any way to debug it further? I am kind of stuck here, any workaround/suggestions might help.
I am putting some code below:

//codeGoesHere

**
val transferUtility = TransferUtility.builder()
.context(context.applicationContext)
.s3Client(s3Client)
.build()

val transferObserver = transferUtility?.upload(BUCKET_NAME, fileKey, file, CannedAccessControlList.PublicRead)
transferObserver.setTransferListener(awsTransferListener)
**

**Comment by alokipandey** [comment] 2021-03-02 10:27
I also had this issue and I resolved it while going through multiple stackoverflow /github /aws doc pages. leaving a link to my documentation below for whomsoever may need it.
https://alokipandey.medium.com/upload-to-aws-s3-from-android-s3-in

**Comment by SamiLakka1979** [comment] 2021-03-02 10:31
Sorry, the link doesn’t work.



Alok <notifications@github.com> kirjoitti 2.3.2021 kello 12.27:

﻿

I also had this issue and I resolved it while going through multiple stackoverflow /github /aws doc pages. leaving a link to my documentation below for whomsoever may need it.
https://alokipandey.medium.com/upload-to-aws-s3-from-android-s3-in

**Comment by alokipandey** [comment] 2021-03-02 13:17
hey, my bad. I have edited the above reply, you can try now. thanks

**Comment by raphkim** [comment] 2021-04-22 18:52
There has been a change in `TransferUtility` to make large file uploads to be more reliable. Please try updating the SDK to v2.22.7 for improved experience. Thank you!

**Closed by raphkim** 2021-04-22 18:52 UTC
Labels: Bug, Needs Info from Requester, S3
