### ISSUE TITLE
Error: credential should be scoped to the correct service lex

### ISSUE THREAD

**Issue by cicchello82** [aws-amplify/aws-sdk-android#2385] opened 2021-03-18 15:29 UTC
Hi,
I'm trying the LexSample. I followed all configurations steps but if I launch the App and try to send text command to bot, I have the error **credential should be scoped to the correct service lex**
Anyne can help me?
Thanks in advance,
Giacomo

**Comment by raphkim** [comment] 2021-03-27 00:54
Hi @cicchello82 ,
As per our last discussion in Discord, I was unable to reproduce this issue in the LexSample app. Would you be able to update this ticket with more information to help us find out what may be causing this issue for you? The rest of the stacktrace and detailed configuration steps that you took (without any sensitive information) would be helpful.

**Comment by cicchello82** [comment] 2021-03-29 07:11
Hi @raphkim,
I tried two steps: first I followed the instruction in readme file for installing LexSample and it gave me the error.
The I import the sample in a working Android app with amplify Auth and Analyticsm but I had same error when I try to call the Bot.
I don't now if I miss some configuration settings. Could you please me wich part of code show you to better understand?
Thanks very much,
Giacomo

**Comment by richardmcclellan** [comment] 2021-04-20 18:52
We believe this issue was fixed in the [2.22.6 release](https://github.com/aws-amplify/aws-sdk-android/releases/tag/release_v2.22.6).  The latest version is [2.22.7](https://github.com/aws-amplify/aws-sdk-android/releases/tag/release_v2.22.7) - please give that a try!  If you are still having issues, feel free to comment or open a new issue.

**Closed by richardmcclellan** 2021-04-20 18:52 UTC
Labels: Lex

**Comment by cicchello82** [comment] 2021-04-21 08:23
Hi,
after upgrading libraries to 2.22.7 something changed but I have a new error "the request signature we calculated does not match the signature you provided. Check your aws secret.....".

**Comment by HaemanthSP** [comment] 2021-05-03 18:02
Hi @cicchello82 ,

Have you found the solution?
I am facing the same issue.

>  com.amazonaws.AmazonServiceException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

Best regards,
Haemanth
