### ISSUE TITLE
KVS: Access to identity is forbidden

### ISSUE THREAD

**Issue by KdB13** [aws-amplify/aws-sdk-android#2964] opened 2022-08-03 13:17 UTC
**Describe the bug**
I'm trying to implement Kinesis Video Streams using these [docs](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/producer-sdk-android.html) using the **Android Producer Library**. I've created the **User Pool** and **Cognito Identity Pool** exactly as mentioned in the docs with the defaults. When I install the sample app provided there and login, it works after first sign in. And then I close the app and reopen it and suddenly I get the following error and the app crashes:

`E/KinesisVideoAndroidClient: 2022-08-03T18:39Z T2: EXCEPTION: ExecutionException: Awaiting for the credentials update threw an exception: com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Access to Identity 'us-east-1:2973a417-c5c4-4739-8822-b5a8b8cf21ec' is forbidden. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 1e0b7f55-c7e6-442e-9165-60680731c45e)`

**To Reproduce**
Use this [sample](https://github.com/awslabs/aws-sdk-android-samples) with your own `aws_confoguration.json` file.
No other changes made to the sample app's code.

**Which AWS service(s) are affected?**
- Cognito
- Kinesis Video Streams

**Expected behavior**
The app should work fine when we open it the second time, instead of showing the above mentioned error.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.5.51
 - Device: Samsung Galaxy A50s
 - Android Version: 11
 - Specific to simulators: No

**Additional context**
I think the problem might be with the way we configure the **Auth** policy in the Identity Pool. I'm using the policy mentioned in the official docs:
```
{
    "Version": "2012-10-17",
    "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "cognito-identity:*",
        "kinesisvideo:*"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}
```

**Comment by eeatonaws** [comment] 2022-08-10 18:38
Closing this issue since it is a duplicate of #2798. Please follow issue #2798 for any updates.

**Closed by eeatonaws** 2022-08-10 18:38 UTC
Labels: bug, duplicate, kinesis
