### ISSUE TITLE
The specified key does not exist after 2.3.9

### ISSUE THREAD

**Issue by maxbax** [aws-amplify/aws-sdk-android#321] opened 2017-07-19 06:57 UTC
After #310 fixed, the version 2.4.5 resolve the space problem but not the general problem. If I write a special char into key string the upload doesn't work well.
The problem is not only for space, but for all special chars.
For example you can use "😂" as key
Usually in the key I write the file name so every characters is admitted. With the 2.3.9 version I can do this

Thanks

**Comment by defaultbr** [comment] 2017-07-24 21:28
sorry the reference...


+1 for me it occur too

WORD: "Saída" (accent at i) the file is never uploaded to S3 (cant find it)

**Comment by kwong93** [comment] 2017-08-01 20:01
I can also confirm, I uploaded file with the key 2017-08-01@02-47-38-M-10666-e713e147-a58a-4327-920a-b3ea006c15de.jpg and it converted the '@' symbol to %40.

**Comment by driskell** [comment] 2018-03-06 18:08
Possibly similar - attempting to download an object containing an @ (“at”) symbol returns AccessDenied (because it cannot find it)

**Comment by kvasukib** [comment] 2018-03-06 23:42
Thank you for reporting to us. We acknowledge that this bug has been introduced after 2.4.1 and we are working on to fix it. We will update this thread once we fix the issue. Thank you for the patience.

**Comment by minbi** [comment] 2018-04-19 15:35
We don't have an eta on the fix, but I have marked the issue so the bot will not close.

**Comment by ioannist** [comment] 2018-08-17 07:19
There is a similar problem with the ":" character. Using the Java SDK, I obtain the key of an S3 Put event from:

`String textFileKey = event.getS3().getObject().getKey();`

If I try to Get this file, AWS will say it does not exist. To fix it, you must replace the "%3A" encoded characters of the key with ":", a rather not elegant solution.

**Comment by kvasukib** [comment] 2018-10-07 23:43
Sorry for the delayed reply. This issue has been fixed in 2.7.4. Please upgrade and check and let us know if you have any issues.

**Comment by AghoPwn** [comment] 2018-10-08 09:00
I still have issues with 2.74, i'm sticking with 2.2.
I have spaces in my keys names.
With 2.2, i don't encode them and they are downloaded without issues.
With newer versions, i tried to Urlencode the key, replace space character with %20, or let the spaces unencoded, and i still can't download the file. What is the correct way to download files with space in the key name ?

Thanks,

**Comment by kvasukib** [comment] 2019-01-02 20:21
This is a duplicate of issue #526. We are tracking this issue in #526. We will capture all the details there.

**Closed by kvasukib** 2019-01-02 20:21 UTC
Labels: S3, bug
