### ISSUE TITLE
Wrong progress calculation/notification when resuming large multipart upload

### ISSUE THREAD

**Issue by Ma7moudHatem** [aws-amplify/aws-sdk-android#2269] opened 2020-12-01 17:02 UTC
I'm using the `TransferUtility` class to upload files to Amazon s3 using
`TransferUtility.upload()` or `TransferUtility.resume()` in case of
interruption, and using `TransferObserver.setTransferListener()` to listen for
upload progress.

If I upload a large file (let's say 100MB) using multipart upload without any
interruption , then the current progress of the upload is calculated and
dispatch correctly with the right value every period.

However, if the upload is interrupted for some reason after 50% of successfully
uploaded parts, and then resumed, the current progress of the upload is
calculated incorrectly. It will not notify the listener until the
`totalBytesTransferredOfAllParts(that currently pending or processing parts) >
prevTotalBytesTransferredOfAllParts(that already uploaded before)`, which is a
wrong calculation in the case of a resumed upload.

The calculation is made inside the `UploadTaskProgressListener` of the
`UploadTask` class. I think the issue could be fixed there.

**Used Dependencies:**
```gradle
implementation "com.amazonaws:aws-android-sdk-s3:2.22.2"
```

**Comment by sdhuka** [comment] 2022-05-18 21:22
Duplicate of #2601

**Closed by sdhuka** 2022-05-18 21:22 UTC
Labels: bug, duplicate, s3, good first issue
