### ISSUE TITLE
HostedUIRedirectActivity does not raise UserCancelledException 

### ISSUE THREAD

**Issue by AndreasBoehm** [aws-amplify/aws-sdk-android#2742] opened 2021-12-07 19:45 UTC
Taken from this issue: https://github.com/aws-amplify/amplify-android/issues/1536

**Describe the bug**
When using the showSignIn API, the library displays a custom tab with the Cognito Hosted UI interface, which the end user is able to close.

The documentation for amplify-android gives two seperate sets of version-dependent instructions for updating the AndroidManifest file.

When using the older instructions utilizing com.amazonaws.mobileconnectors.cognitoauth.activities.CustomTabsRedirectActivity, the closure of the CustomTab results in a UserCancelledException being raised from the showSignIn onError handler.

When using the newer instructions utilizing com.amplifyframework.auth.cognito.activities.HostedUIRedirectActivity, no such exception is raised.

**To Reproduce**
1. Follow the HostedUI instructions for 1.17.7 and below.
2. Close the Customtab
3. Note the UserCancelledException
4. Follow the HostedUI instructions for 1.17.8 and up.
5. Close the Customtab
6. Note the absence of a UserCancelledException.

```
mainActivity.let {
            Amplify.Auth.signInWithWebUI(
                    it,
                    { result ->
                      if (!resultSubmitted) {
                        resultSubmitted = true;
                        prepareSignInResult(flutterResult, result)
                      }
                    },
                    { error -> errorHandler.handleAuthError(flutterResult, error) }
            )
          }
```

**Which AWS service(s) are affected?**
Cognito auth with hosted UI

**Expected behavior**
A UserCancelledException should be thrown when the user closes the CustomTab.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.36.0
 - Device: Pixel 3
 - Android Version: 12
 - Specific to simulators: No

**Comment by gpanshu** [comment] 2022-03-18 17:42
Duplicate of https://github.com/aws-amplify/amplify-android/issues/1536 

Looking at the code it has been implemented :
CustomTabsManagerActivity.handleAuthorizationCanceled

private void handleAuthorizationCanceled() {
        Log.d(TAG, "Authorization flow canceled by user");
        setResult(RESULT_CANCELED);
    }
If this does not solve your issue please recreate but I highly recommend you update your libraries to the latest and try again.
Thank you

**Closed by gpanshu** 2022-03-18 17:42 UTC
Labels: bug, cognito
