### ISSUE TITLE
How to include custom authorization headers while connecting?

### ISSUE THREAD

**Issue by SanyasiraoM** [aws-amplify/aws-sdk-android#429] opened 2018-03-23 14:25 UTC
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS IOT

* In what version of SDK are you facing the problem?
2.6.7

* Is the issue limited to Simulators / Actual Devices?
Both

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific Android/OS version?
No

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

This is not an issue. We came to know that we can add custom authorization headers while connecting to aws iot broker at https://docs.aws.amazon.com/iot/latest/developerguide/custom-auth.html. So is there any snippet or reference to how to use them in android and ios?

**Comment by rohandubal** [comment] 2018-08-07 23:49
Hello,

I have added this as a feature request in our backlog and have submitted it to the team for prioritization. I do not have specific timeline that I can share at this point. We will let you know, either on this thread, or through a forum announcement when the feature is released in the SDK.

Thanks,
Rohan

**Comment by iamtonny** [comment] 2018-10-19 10:36
Hi, do you have any news about custom authentication for android and ios sdk??? When it can be implemented (month, half-year, year) ??  Thanx

**Comment by desokroshan** [comment] 2019-01-07 18:00
@iamtonny We are currently working on this request. I cannot share a specific timeline but I will update this thread once the feature has been released.

**Comment by j0bro** [comment] 2019-01-31 11:14
I am currently working on a big project where this would be very helpful; the SDK documentation claims it allows for setting the custom authorization headers, but the implementation is only present in the JS SDK. In [this forum thread](https://forums.aws.amazon.com/thread.jspa?messageID=836976) there is a post by user vita1ii who created a patch on the Paho MQTT client which is embedded in the AWS Android SDK.
Note that I am only assuming this functionality is also lacking from the iOS SDK, I am just following what was said above here.

**Comment by kvasukib** [comment] 2019-01-31 17:39
@j0bro We are waiting on Paho to release this fix so we could take a dependency on the version that has the fix. However for iOS SDK, we did not have any limitation, so we have this feature working for iOS: https://aws-amplify.github.io/docs/ios/pubsub#custom-authentication

**Comment by SandyRagaie** [comment] 2019-08-09 14:35
I am working on Android project now and this feature request blocks a main functionality in the application, is there any known work around we can do to overcome this until aws sdk is released?

**Comment by desokroshan** [comment] 2019-08-09 20:39
@SandyRagaie Thanks for reaching out. Supporting custom Auth in Android SDK needs paho version 1.2.1 which causes regression and breaks the SDK https://github.com/eclipse/paho.mqtt.java/issues/345. I will look into possible workarounds and provide an update soon as I can.

**Comment by cmbaykal** [comment] 2019-10-22 10:14
Hi. I saw the new release. I wonder when the custom auth is added to AWS SDK ?

**Comment by kvasukib** [comment] 2019-10-23 02:57
@cmbaykal This is still in our backlog for prioritization. We will let you know through this issue when the changes are being released.

**Comment by cagriyilmaz** [comment] 2019-12-13 08:21
Hi @desokroshan @kvasukib, do you have any news about custom authentication feature for android sdk?

**Comment by desokroshan** [comment] 2020-04-09 05:38
SDK supports custom authentication starting from version [2.16.8](https://github.com/aws-amplify/aws-sdk-android/releases/tag/release_v2.16.8).
Please refer to the documentation for more details regarding its usage : https://docs.amplify.aws/sdk/pubsub/working-api?platform=android#custom-authentication

Please note that the latest versions (2.16.1 and above) of SDK/custom-auth feature cannot currently be used on Android API levels lower than 24. This is due to bug a in Paho and release with a fix is soon likely to follow. Please refer to https://github.com/aws-amplify/aws-sdk-android/issues/1259 for more details.

**Closed by desokroshan** 2020-04-09 05:38 UTC
Labels: Feature Request, IoT
