### ISSUE TITLE
Getting java.net.UnknownHostException: Unable to resolve host "cognito-idp.us-east-1.amazonaws.com": No address associated with hostname in various Auth results

### ISSUE THREAD

**Issue by Gesraha101** [aws-amplify/aws-sdk-android#3371] opened 2023-07-31 11:34 UTC
**Describe the bug**
I have been getting `java.net.UnknownHostException: Unable to resolve host "cognito-idp.us-east-1.amazonaws.com": No address associated with hostname` exception in some Auth methods results (mainly Auth.fetchAuthSession since it is the most used one) in live reports. I could not reproduce this myself unfortunately. I even tried to do it by slowing down the network on an emulator, but it worked fine (with a delay of course but it did work). The recovery suggestion is "Sorry, we don't have a suggested fix for this error yet."

It is worth mentioning that I am using proguard with no rules made for amplify. I think I saw someone mentioning there should be some rules for it in an earlier search, but I cannot remember where.

**Which AWS service(s) are affected?**
Amplify Auth

**Expected behavior**
Expected to do intended behavior without the exception.

**Screenshots**
N/A

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.8.7
 - Device: Normal distribution among all devices (Xiaomi, Samsung, Oppo are the top ones)
 - Android Version: Normal distribution among android versions
 - Specific to simulators: No

**Comment by mattcreaser** [comment] 2023-07-31 14:47
Duplicate of https://github.com/aws-amplify/amplify-android/issues/2542

**Closed by mattcreaser** 2023-07-31 14:47 UTC
