### ISSUE TITLE
Number format exception Transfer Record

### ISSUE THREAD

**Issue by sougandhmp** [aws-amplify/aws-sdk-android#1461] opened 2020-01-30 15:53 UTC
Sharing the crash logs

AWS s3 transfer utility causes crash. Have seen similar bug 
https://github.com/aws-amplify/aws-sdk-android/issues/1093 in which it was suggested to remove "awss3transfertable.db"which i have not tried. But I have tried updating to the latest version but still issues are reported..

Caused by java.lang.NumberFormatException
For input string: "ANY"

sun.misc.FloatingDecimal.readJavaFormatString (FloatingDecimal.java:2043)
sun.misc.FloatingDecimal.parseDouble (FloatingDecimal.java:110)
java.lang.Double.parseDouble (Double.java:538)
com.google.gson.stream.JsonReader.nextInt (JsonReader.java:186)
com.google.gson.internal.bind.TypeAdapters$7.a (TypeAdapters.java:13)
com.google.gson.internal.bind.TypeAdapters$7.read (TypeAdapters.java)
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.a (ReflectiveTypeAdapterFactory.java:2)
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.a (ReflectiveTypeAdapterFactory.java:47)
com.google.gson.Gson.a (Gson.java:20)
com.google.gson.Gson.a (Gson.java:4)
com.google.gson.Gson.a (Gson.java:9)
com.google.gson.Gson.assertFullConsumption (Gson.java)

com.amazonaws.mobileconnectors.s3.transferutility.TransferRecord.a (TransferRecord.java:422)
com.amazonaws.mobileconnectors.s3.transferutility.TransferDBUtil.getTransferById (TransferDBUtil.java:16)
com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility.a (TransferUtility.java:20)
com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility.a (TransferUtility.java:2)
com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility.a (TransferUtility.java:23)

 - AWS Android SDK Version: [e.g. 2.16.6, older versions also]
 - Device: [e.g. Galaxy S9 and many devices]
 - Android Version: [9]

**Comment by raphkim** [comment] 2020-01-31 18:33
Hi @sougandhmp ,

There may be a potential issue with how GSON de/serializes `TransferNetworkConnectionType` in the Android SDK for S3 when the code is obfuscated. Would you be able to try modifying your proguard configuration as [following](https://stackoverflow.com/questions/15543607/assertionerror-in-gson-enumtypeadapter-when-using-proguard-obfuscation)?

**Comment by sougandhmp** [comment] 2020-02-02 23:00
Hi @raphkim,
Thanks for the suggestion, I have added -keepclassmembers enum * { *; }  to the proguard rules. I will be checking crash is happening again for this reason.

**Comment by sougandhmp** [comment] 2020-02-10 10:04
Hi @raphkim ,

Should I do anything to the app other than adding this to pro-guard rules? Since the issue was not reported for fresh users. Also issue seems to happen multiple times for particular users.

Any help would be appreciated.

**Comment by raphkim** [comment] 2020-02-12 00:33
Have you tried deleting "awss3transfertable.db"? If the issue is only recurring for some people, I think it may be possible for the database to be corrupted.

**Comment by sougandhmp** [comment] 2020-02-17 15:02
Hi @raphkim , @palpatim 

I have not tried deleting "awss3transfertable.db". I have already mentioned it in the description of bug.
Since the issue was only happening for few production users i was not able to reproduce and check the issue.

**Comment by raphkim** [comment] 2020-02-19 17:48
I would suggest clearing the transfer database before moving forward. Once the database is corrupted, the issue will persist as long as the app continues to access it.

**Comment by svanegas** [comment] 2020-03-02 17:14
@sougandhmp, did you try deleting the database? any updates on your end?

@raphkim. I'm having the same issue and I'm **not using obfuscation**. Here's the stacktrace:

```
Caused by java.lang.NumberFormatException: Invalid double: "ANY"
       at java.lang.StringToReal.invalidReal(StringToReal.java:63)
       at java.lang.StringToReal.initialParse(StringToReal.java:164)
       at java.lang.StringToReal.parseDouble(StringToReal.java:282)
       at java.lang.Double.parseDouble(Double.java:301)
       at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1201)
       at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:226)
       at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:218)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
       at com.google.gson.Gson.fromJson(Gson.java:927)
       at com.google.gson.Gson.fromJson(Gson.java:892)
       at com.google.gson.Gson.fromJson(Gson.java:841)
       at com.google.gson.Gson.fromJson(Gson.java:813)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferRecord.updateFromDB(TransferRecord.java:159)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBUtil.getTransferById(TransferDBUtil.java:865)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility.submitTransferJob(TransferUtility.java:901)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility.pause(TransferUtility.java:772)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility.pauseAllWithType(TransferUtility.java:787)
```

**SDK Version:** 2.16.5
Noticed that happens mostly on Samsung devices with Android 10

Since I can't reproduce either, do you have some idea how this can be reproducible? Furthermore, about deleting the database:
- Could you please specify how should this process be done? 
- Do we have to manually delete that database? 
- When exactly needs to be deleted? 
- Wouldn't it affect anything else in the schema?

Thanks

**Comment by sougandhmp** [comment] 2020-03-04 23:21
Hi @svanegas,

No I couldn't verify the solution since I was not able to reproduce the crash.

**Comment by svanegas** [comment] 2020-04-15 15:15
@TrekSoft, @desokroshan, @palpatim, @raphkim. Guys, I'm still facing this issue and it's becoming now a big deal in production. Could anyone please assign to corresponding person and reopen?

Stack trace is above, and as I mentioned, occurs mostly on Samsung devices with Android 10.

Could you please explain me how could I implement a workaround or solve this issue?

Thanks

**Comment by raphkim** [comment] 2020-04-15 18:17
Hi @svanegas ,

I apologize for pre-maturely closing the issue. It seems to me that most people that have experienced this issue were able to resolve their issue by deleting their in-memory transfer data "awss3transfertable.db". This is the database that stores all of the ongoing transfers in the app so that the information is not lost upon closing the app. 

This database can be deleted by using `Context#deleteDatabase(String)` method and using "awss3transfertable.db" as the argument. However, I would advise against using this regularly inside the app outside of the context of explicitly clearing data.

I will further investigate the issue to see what we can do to mitigate the corruption of database.

**Comment by raphkim** [comment] 2020-04-15 18:19
@svanegas would you be able to check if you have `minifyEnabled` set to `true` inside your `build.gradle` file?

**Comment by svanegas** [comment] 2020-04-15 18:51
@raphkim. Thank you for reply.

Yes,  `minifyEnabled` is `true`.

I was getting ready to release soon a prod version that uses `deleteDatabase("awss3transfertable.db")` in the `onCreate()` of the `Application` class as a temporary workaround. But then I saw that you advise against using it this way.

Do you think the deletion of the database every time app is opened would affect something else? What do you think could be done better?

**Comment by raphkim** [comment] 2020-04-15 19:46
For future reference, `minifyEnabled = true` will obfuscate your code ;)

Deleting the database in the `onCreate()` method would remove the transfer information every time the app is exited, which defeats the purpose of keeping a persistent record of the ongoing transfers. This issue should ideally be resolved once the corrupted table is deleted once (outside of the app's lifecycle), and should not require it to be deleted thereafter.

**Comment by svanegas** [comment] 2020-04-15 19:51
> For future reference, `minifyEnabled = true` will obfuscate your code ;)
> 
> Deleting the database in the `onCreate()` method would remove the transfer information every time the app is exited, which defeats the purpose of keeping a persistent record of the ongoing transfers. This issue should ideally be resolved once the corrupted table is deleted once (outside of the app's lifecycle), and should not require it to be deleted thereafter.

@raphkim. Okay, so do you think a good strategy would be: Catch this exception, when this happens, delete database. It might be enough, right?

**Comment by raphkim** [comment] 2020-04-16 17:07
> There may be a potential issue with how GSON de/serializes `TransferNetworkConnectionType` in the Android SDK for S3 when the code is obfuscated. Would you be able to try modifying your proguard configuration as [following](https://stackoverflow.com/questions/15543607/assertionerror-in-gson-enumtypeadapter-when-using-proguard-obfuscation)?

While deleting database upon gson failure would be a good temporary workaround, I suggest that you verify the above solution first for a more permanent solution. With the temporary solution you've provided, a user experiencing this issue will inexplicably lose data on all of the ongoing/past transfers

**Comment by svanegas** [comment] 2020-04-16 18:10
Thanks @raphkim.

I already had this config, actually:
```
-keepnames class com.amazonaws.**
-keepnames class com.amazon.**
```

We will see how it behaves with workaround!

**Comment by buntupana** [comment] 2022-11-03 19:29
After more than two year this issue is still happening sometimes when I upload the library. Is there any solution to prevent this happening?

**Comment by PruthvirajSoftvan** [comment] 2022-12-13 05:50
**I have faced an issue after updating aws SDK from 2.28.0 to 2.58.0**

```
Fatal Exception: com.google.gson.n: java.lang.NumberFormatException: For input string: "ANY"
       at com.google.gson.internal.bind.TypeAdapters$7.b(TypeAdapters.java:25)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:2)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:47)
       at com.google.gson.Gson.fromJson(Gson.java:31)
       at com.google.gson.Gson.b(Gson.java:1)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferRecord.updateFromDB(TransferRecord.java:422)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler.resumeAllTransfersOnNetworkAvailability(TransferNetworkLossHandler.java:73)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler$1.run(TransferNetworkLossHandler.java:73)
       at java.lang.Thread.run(Thread.java:1012)
```

**Update Aws SDK from 2.28.0 to 2.58.0**
**This crash show in firebase. not reproduce**
  
Note :- Refer to above conversation and following steps  deleted by using Context#deleteDatabase(String) method so my question is that affect any other schema or internal app database or any change to crash end user or client app at production?

**Comment by mquineche** [comment] 2023-02-02 17:16
I'm facing this issue.
**I updated AWS SDK from 2.13.7 to 2.62.2. 
From Crashltycs: 5k crash events in 5 users** 

`Fatal Exception: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "ANY"
       at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:307)
       at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:297)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
       at com.google.gson.Gson.fromJson(Gson.java:963)
       at com.google.gson.Gson.fromJson(Gson.java:928)
       at com.google.gson.Gson.fromJson(Gson.java:877)
       at com.google.gson.Gson.fromJson(Gson.java:848)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferRecord.updateFromDB(TransferRecord.java:159)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler.resumeAllTransfersOnNetworkAvailability(TransferNetworkLossHandler.java:176)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler.access$000(TransferNetworkLossHandler.java:37)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler$1.run(TransferNetworkLossHandler.java:123)
       at java.lang.Thread.run(Thread.java:919)`

So any of those workaround has fixed this particular issue ?

**Comment by buntupana** [comment] 2023-03-09 05:56
And still no official answer

**Comment by buntupana** [comment] 2023-04-07 14:47
I'm still experiencing this issue once in a while for some production users and I can't even catch it to avoid crash and delete the database as it's suggested so I have no real solution.

**Comment by sdhuka** [comment] 2023-04-07 14:52
@buntupana We have reopened the issue and investigate further.

**Comment by sdhuka** [comment] 2023-06-20 16:45
@buntupana We have added the fix to prevent the crash in case of deserialization exception. Please update to the latest sdk version for the fix.

**Closed by sdhuka** 2023-06-20 16:45 UTC
Labels: bug, s3, pending-response
