### ISSUE TITLE
Confirm signIn  not working in api less than 23 

### ISSUE THREAD

**Issue by mohammedhasna2015** [aws-amplify/aws-sdk-android#1518] opened 2020-03-16 14:29 UTC
** i used "custom auth" so when trying to execute confirm singIn from Aws Mobile Client  after code send to mobile user  and execute confirm singin with code  , some error return to me .  **

**To Reproduce**
A code sample or steps:
```
 public  void confirmSignIn(Context context, String code) {

        Log.d(TAG, "confirmSignIn:"+code);
         AWSMobileClient.getInstance().initialize(context, new Callback<UserStateDetails>() {
             @Override
             public void onResult(UserStateDetails result) {
                 final Map<String, String> clientMetaData = new HashMap<String, String>();
                 final Map<String, String> res = new HashMap<String, String>();
                 clientMetaData.put("challengeResponseAnswer", ""+code);
                 res.put(CognitoServiceConstants.CHLG_RESP_ANSWER, ""+code);

                 AWSMobileClient.getInstance().confirmSignIn(res,clientMetaData, new Callback<SignInResult>() {
                     @Override
                     public void onResult(final SignInResult signInResult) {
                         mResultConfirmSignInResultMutableLiveData.postValue(signInResult);
                     }
                     @Override
                     public void onError(Exception e) {

                         Log.d(TAG, "verification:2Confirm Custom auth Sign-in error4", e);
                         if (e.getMessage().contains("Incorrect username or password")){
                             mResultIncorrectUserNameMutableLiveData.postValue(true);
                         }
                     }
                 });
             }

             @Override
             public void onError(Exception e) {
                 errorValueMutableLiveData.postValue(e.getMessage());

                 Log.d(TAG, "verification:onError1:"+e.getMessage());
             }
         });


    }
```

**Which AWS service(s) are affected?**
Aws mobile client , pinPoint Manager ,AppSync,S3 , core3  
**Expected behavior**

**Screenshots**
no screen 
**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [2.16.9]
 - Device: [e.g. Pixel , Simulator]
 - Android Version: [ lollipop ,Api 17 ]
 - Specific to simulators: [Yes]

**Additional context**
"Confirm singIn not working "
 this problem return this error . => 
Device confirmation failed: 
com.amazonaws.mobileconnectors.cognitoidentityprovider.exceptions.CognitoNotAuthorizedException: User is not authenticated

**Comment by raphkim** [comment] 2020-03-20 18:38
Closing in favor of #1499

**Closed by raphkim** 2020-03-20 18:38 UTC
Labels: AWSMobileClient

**Comment by mohammedhasna2015** [comment] 2020-03-20 18:43
where the solve problem ?

**Comment by jamesonwilliams** [comment] 2020-03-21 03:50
@mohammedhasna2015: @raphkim has marked this #1518 as a duplicate of #1499. Does #1499 describe your issue? We can use a single issue to track it.
