### ISSUE TITLE
How to implement custom authentication using aws mobile client

### ISSUE THREAD

**Issue by mahi1518** [aws-amplify/aws-sdk-android#1126] opened 2019-08-09 14:09 UTC
**I want to implement custom authentication in cognito using cognito trigger ?**

I already implement custom authentication using python aws SDK and it working fine.
My challenge in the implementation of custom authentication using aws mobile client is to 
where to  define the **AuthFlow='CUSTOM_AUTH'** in my android code 
the document I follow 
https://aws-amplify.github.io/docs/android/authentication

**Comment by palpatim** [comment] 2019-08-12 15:47
Dupe of #1123

**Closed by palpatim** 2019-08-12 15:47 UTC
