### ISSUE TITLE
S3 Download fail special chars

### ISSUE THREAD

**Issue by mvievardassystem** [aws-amplify/aws-sdk-android#597] opened 2018-12-04 10:36 UTC
**Describe the bug**

I use the SDK like : 
        TransferObserver transferObserver = transferUtility.download(
                GlobalVariables.getInstance().bucket,
                name,
                file
        );
        transferObserver.setTransferListener(new MyEvent());

I have a issu with a file like "+ et é_resize.png"

It works with a file like : "1 et 1_resize.png"

There is a bug in the SDK Android with some chars.

**Environment(please complete the following information):**
 - SDK Version: 2.8.4

**Comment by kvasukib** [comment] 2019-01-02 20:22
This is a duplicate of issue #526. We are tracking this issue in #526. We will capture all the details there.

**Closed by kvasukib** 2019-01-02 20:22 UTC
Labels: S3
