### ISSUE TITLE
Question: How to migrate to v2.19.0 from v2.9.0 ?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [aws-amplify/aws-sdk-android#2141] opened 2020-09-30 06:51 UTC
**State your question**
I got tasked to work on an old project, and I'm trying to update its dependencies. One of them is of here, and it's on 2.9.0. 
I wanted to update it to 2.19.0. On debug-variant, it still works fine.
It has some deprecated usages, I think, but it works.

However, when running on release-variant only, I get this crash:
```
    java.lang.AssertionError: java.lang.NoSuchFieldException: ANY
        at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:12)
        at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:5)
        at com.google.gson.Gson.getAdapter(Gson.java:9)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:4)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:15)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:4)
        at com.google.gson.Gson.getAdapter(Gson.java:9)
        at com.google.gson.Gson.toJson(Gson.java:11)
        at com.google.gson.Gson.toJson(Gson.java:9)
        at com.google.gson.Gson.toJson(Gson.java:4)
        at com.google.gson.Gson.toJson(Gson.java:2)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBUtil.f(TransferDBUtil.java:15)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBUtil.m(TransferDBUtil.java:1)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBUtil.l(TransferDBUtil.java:1)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBUtil.k(TransferDBUtil.java:1)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility.e(TransferUtility.java:2)
        at com.amazonaws.mobileconnectors.s3.transferutility.TransferUtility.d(TransferUtility.java:1)

```

**Which AWS Services are you utilizing?**
Not sure about the question. This is what I see on the gradle file:
    implementation 'com.amazonaws:aws-android-sdk-s3:2.18.0'

**Provide code snippets (if applicable)**

```java
    public static void downloadFile(final Context context, final String bucketName, final String fileName, final File file, final int identityType, final S3TransferListener transferListener) {
        L.i(TAG, "bucket: " + bucketName);
        L.i(TAG, "fileName: " + fileName);
        if (L.wtfNullCheck(bucketName)
                || L.wtfNullCheck(fileName)) {
            transferListener.onError(0, new InvalidParameterException("Invalid bucket or fileName"));
            return;
        }
        final TransferObserver observer = getTransferUtility(context, identityType).download(bucketName, fileName, file); // <-crash here
        if (transferListener != null) {
            observer.setTransferListener(transferListener);
        }
    }
```

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.25]
v2.19.0

**Device Information (please complete the following information):**
 - Device: [e.g. Pixel XL, Simulator]
Pixel 4
 - Android Version: [e.g. Nougat 7.1.2]
Android 11
 - Specific to simulators:
Didn't test on emulators.

**Comment by raphkim** [comment] 2020-10-05 16:42
Hi @AndroidDeveloperLB ,

There appears to be a bug with upgrading the Transfer database that causes this issue. So far it has been resolved by deleting the corrupted database and letting the SDK build a new one (one-time thing). 

https://github.com/aws-amplify/aws-sdk-android/issues/1461#issuecomment-614198841

Please feel free to reopen this issue if this does not work.

**Closed by raphkim** 2020-10-05 16:42 UTC

**Comment by AndroidDeveloperLB** [comment] 2020-10-06 07:43
@raphkim The issue I described is upon running the app on clean state, meaning the app wasn't installed before, so there can't be a DB issue in my case (because there is no DB file).
You say that this is an issue too? Is there an easy way to fix it? Shouldn't the SDK of this repository handle the upgrade?

Please re-open the report. It wasn't about upgrade (which I should check too). 
What's the best way to handle it?

**Comment by raphkim** [comment] 2020-10-06 08:40
Hey @AndroidDeveloperLB ,

The issue that you are experiencing comes from a bug with gson (third-party dependency of `TransferUtility`) and its inability to handle enums correctly when the app is minified (obfuscated). Can you confirm that you are obfuscating your app, or that you have `minifyEnabled` set to `true` inside your `build.gradle`?

In that case, please try the solution I suggested in the [same issue as earlier](https://github.com/aws-amplify/aws-sdk-android/issues/1461#issuecomment-614813999). By forcing the proguard to not obfuscate enums, you will no longer experience the bug.

**Comment by AndroidDeveloperLB** [comment] 2020-10-06 08:59
@raphkim It is only on release variant, and it is being minified. But the issue didn't exist on old version of this repository, and proguard rules are supposed to be automatically added by using it, no?
It also says so here:
https://github.com/aws-amplify/aws-sdk-android/blob/main/Proguard.md

How come I need to add this ?
I tried now to add `-keepclassmembers enum * { *; }`, and seems to work. 

But are you guys also saying there is an upgrade issue, that I need to delete DB file?

**Comment by AndroidDeveloperLB** [comment] 2020-11-23 13:08
Why is it closed?
Fixed?
If so, how, and what should I do now?

**Comment by raphkim** [comment] 2020-11-23 16:07
@AndroidDeveloperLB are you still experiencing an issue? It should be resolved now.

**Comment by AndroidDeveloperLB** [comment] 2020-11-23 17:47
@raphkim I can't right now. Just asked how it was fixed.
Should I do anything? Can I avoid the workaround of Proguard?

**Comment by raphkim** [comment] 2020-11-24 00:21
Yep! the workaround was added to our project's proguard so there shouldn't be anything you need to do. Please let us know if you aren't able to migrate smoothly.

**Comment by AndroidDeveloperLB** [comment] 2020-11-24 10:28
@raphkim Ok on which version it now works perfectly and there is no need for workarounds?
this:

```
    implementation 'com.amazonaws:aws-android-sdk-s3:2.19.3'
```

?

**Comment by jamesonwilliams** [comment] 2020-11-24 14:44
@AndroidDeveloperLB The AWS SDK for Android is broken up into a number of smaller libraries. You've mentioned the S3 and core libraries, above. That same link shows [many others](https://mvnrepository.com/artifact/com.amazonaws). If you're using the S3 `TransferUtility`, use the S3 library. The core library is a dependency of it, that will get pulled in automatically, without you needing to write anything.

**Comment by AndroidDeveloperLB** [comment] 2020-11-24 14:49
@jamesonwilliams 

Oh here it is:
https://mvnrepository.com/artifact/com.amazonaws/aws-android-sdk-s3

And the app indeed uses TransferUtility. So it should be fine, right? 

Is there some migration tutorial though? I've seen deprecation warning about it, such as `AmazonS3Client` , `TransferUtility`

**Comment by jamesonwilliams** [comment] 2020-11-24 15:38
Hi @AndroidDeveloperLB -- no, there is no migration guide that shows how to upgrade from version 2.9.0 to 2.19.0. 2.9.0 is about two years old, and we have been making incremental updates at each new release, since then.

Most functionality that gets deprecated will usually include Javadocs explaining why, or what to use instead. This is indeed the case for the constructors you've mentioned above.

For [`AmazonS3Client(AWSCredentials)`](https://github.com/aws-amplify/aws-sdk-android/blob/main/aws-android-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L294):
> Use AmazonS3Client(AWSCredentials, Region) instead.

And likewise for [`AmazonS3Client(AWSCredentialsProvider)`](https://github.com/aws-amplify/aws-sdk-android/blob/575ab649651724042995b74b6feeeb59780d5695/aws-android-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L333-L335):
> Use AmazonS3Client#AmazonS3Client(AWSCredentialsProvider, Region) instead.

In the case of [`TransferUtilify`](https://github.com/aws-amplify/aws-sdk-android/blame/575ab649651724042995b74b6feeeb59780d5695/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferUtility.java#L340-L341), it now uses a builder pattern:
> Please use TransferUtility.builder().s3Client(s3).context(context).build()

**Comment by AndroidDeveloperLB** [comment] 2020-11-24 15:42
@jamesonwilliams Thank you very much, but what is this region that it requires? How do I get it? Should it be null?

Speaking about null, can you please update the code to have nullability annotations, to know when it's ok to use null and when it's not?

**Comment by jamesonwilliams** [comment] 2020-11-24 15:51
> What is this region that it requires? How do I get it? Should it be null?

The region corresponds to the one you chose when you setup your S3 bucket. In the AWS SDK for Android, the different AWS regions are represented by the [`Region`](https://github.com/aws-amplify/aws-sdk-android/blob/575ab649651724042995b74b6feeeb59780d5695/aws-android-sdk-core/src/main/java/com/amazonaws/regions/Region.java#L30) class and the associated [`Regions`](https://github.com/aws-amplify/aws-sdk-android/blob/575ab649651724042995b74b6feeeb59780d5695/aws-android-sdk-core/src/main/java/com/amazonaws/regions/Regions.java#L21) enum.

For example, if you're using a bucket in us-west-2 (Oregon), you can use this for your region value:

```java
Region usWest2Region = Region.getRegion(Regions.US_WEST_2);
```

> Can you please update the code to have nullability annotations, to know when it's ok to use null and when it's not?

Please consider moving to [the Amplify library](https://docs.amplify.aws/lib/storage/getting-started/q/platform/android), which is AWS' current solution for file storage from Android. It generally does not allow null parameters anywhere -- but there are nullability cues _everywhere_.

**Comment by AndroidDeveloperLB** [comment] 2020-11-25 09:07
@jamesonwilliams Thank you very much for the help, but I've noticed 2 instances that I don't see the Region being set, so I'm not sure what to convert it to:

```
AmazonS3Client s3Client = new AmazonS3Client(new AnonymousAWSCredentials());
```

**Comment by svanegas** [comment] 2021-06-28 18:07
> Yep! the workaround was added to our project's proguard so there shouldn't be anything you need to do. Please let us know if you aren't able to migrate smoothly.

Hey @raphkim, I have upgraded from `2.16.5` to `2.24.0`, because this crash started to appear again on our reports, meaning that for some reason our workaround of deleting the database in case of failure, stopped working (discussed here: https://github.com/aws-amplify/aws-sdk-android/issues/1461) This was on Apr 2020.

So, we upgraded to latest version without adding the `-keepclassmembers enum * { *; }` in our own Proguard, hoping for the lib to do it by its own. But the crash still happens.

Now we're trying adding the Proguard line ourselves, but we don't have a way to reproduce this in order to see if the workaround is going to work. Do you know if we could force this to happen? Or somehow simulate a migration for a user that has corrupted DB and this crash raises?

Thank you.

**Comment by raphkim** [comment] 2021-06-28 18:26
We do not currently have a reliable way to reproduce this error, but the latest version should have resolved it. That is to say, the latest version will help prevent an existing working database from being corrupted, but it does not retro-actively fix a corrupted database. Is the crash happening on a device that has previously had the database reset while on the newer version of the SDK?

If you are still experiencing an issue, it is possible that proguard rules have not been merged correctly. You can try following the [instructions for checking merged proguard configuration](https://stackoverflow.com/questions/44430618/how-to-extract-merged-proguard-rules) to make sure that enum values are not being obfuscated. Adding the line directly to your app's proguard file will be a reliable way to ensure that you no longer run into this issue.

**Comment by svanegas** [comment] 2021-06-29 18:26
> We do not currently have a reliable way to reproduce this error, but the latest version should have resolved it. That is to say, the latest version will help prevent an existing working database from being corrupted, but it does not retro-actively fix a corrupted database. Is the crash happening on a device that has previously had the database reset while on the newer version of the SDK?
> 
> If you are still experiencing an issue, it is possible that proguard rules have not been merged correctly. You can try following the [instructions for checking merged proguard configuration](https://stackoverflow.com/questions/44430618/how-to-extract-merged-proguard-rules) to make sure that enum values are not being obfuscated. Adding the line directly to your app's proguard file will be a reliable way to ensure that you no longer run into this issue.

@raphkim, I checked the merged proguard, however this line `-keepclassmembers enum * { *; }` is there, added by the aws core lib. I just added it in our own proguard too, but:

I also realized that this is also happening not only when we explicitly try to upload/pause/cancel an upload but also when a registered `TransferNetworkLossHandler` is triggered. Check these logs:

```
Fatal Exception: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "ANY"
       at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:228)
       at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:218)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
       at com.google.gson.Gson.fromJson(Gson.java:932)
       at com.google.gson.Gson.fromJson(Gson.java:897)
       at com.google.gson.Gson.fromJson(Gson.java:846)
       at com.google.gson.Gson.fromJson(Gson.java:817)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferRecord.updateFromDB(TransferRecord.java:159)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler.resumeAllTransfersOnNetworkAvailability(TransferNetworkLossHandler.java:176)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler.access$000(TransferNetworkLossHandler.java:37)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler$1.run(TransferNetworkLossHandler.java:123)
       at java.lang.Thread.run(Thread.java:923)
Caused by java.lang.NumberFormatException: For input string: "ANY"
       at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
       at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
       at java.lang.Double.parseDouble(Double.java:538)
       at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1202)
       at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:226)
       at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:218)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
       at com.google.gson.Gson.fromJson(Gson.java:932)
       at com.google.gson.Gson.fromJson(Gson.java:897)
       at com.google.gson.Gson.fromJson(Gson.java:846)
       at com.google.gson.Gson.fromJson(Gson.java:817)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferRecord.updateFromDB(TransferRecord.java:159)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler.resumeAllTransfersOnNetworkAvailability(TransferNetworkLossHandler.java:176)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler.access$000(TransferNetworkLossHandler.java:37)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler$1.run(TransferNetworkLossHandler.java:123)
       at java.lang.Thread.run(Thread.java:923)
```

In this case, we won't be able to "wrap" this and clear the database once we've get this crash, since the `TransferNetworkLossHandler` is a singleton and won't be able to extend it to catch the exception, clear DB and retry.

What do you think could be a good approach to avoid this?

I assume this is happening to users that had a previous version of the DB before.
