### ISSUE TITLE
Failed to put a frame with status code 0x3200000d - Android Producer Library

### ISSUE THREAD

**Issue by tongvantruong** [aws-amplify/aws-sdk-android#909] opened 2019-04-19 06:19 UTC
I got the same issue like this https://github.com/aws-amplify/aws-sdk-android/issues/581

I am trying to run the example project on my One Plus 6 device follow: https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/producer-sdk-android.html

I have also taken a look at https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/troubleshooting.html#troubleshooting-producer-android-invalid-annexb.
- If I set `.withNalAdaptationFlags(StreamInfo.NalAdaptationFlags.NAL_ADAPTATION_ANNEXB_CPD_AND_FRAME_NALS)`, I will get the error Failed to put a frame with status code 0x3200000d repeated on the Logcat. But i can see the streaming video on Kinesis Video Stream about few seconds then it stops showing.
- If I change to `.withNalAdaptationFlags(StreamInfo.NalAdaptationFlags. NAL_ADAPTATION_ANNEXB_CPD_NALS)`. The error will be gone. But I will get "Fragment decoding error" on the Kinesis Video Stream:
`Fragment decoding error
There was an error decoding the video data. Verify that the stream contains valid H.264 content.
RetryHide details
Codec ID: avc1.42800d (H.264 Baseline@1.3)
Fragment number: 91343852333182343526454496973667225994578699509
Producer timestamp: January 1, 1970 9:05 AM +08
Server timestamp: April 19, 2019 1:04 PM +07
Size: 2.0 MB
This may be an intermittent issue. Retry the same action, or try refreshing your browser tab.`

Could someone please give me advise how to solve the issue?

**Comment by zhiyua-git** [comment] 2019-05-22 23:09
Hi @tongvantruong ,

The issue is caused by encoder passing frames with 3+ ending zeros and sdk will treat this as error for AnnexB case. 

The fix is in https://github.com/aws-amplify/aws-sdk-android/commit/7b09c97a7a066e634d10b6676884a6f6d81d46fe. It is verified on OnePlus 6T.
Now it is in develop branch: https://github.com/aws-amplify/aws-sdk-android/tree/develop.

You can either follow this instruction to build the change and test or wait for new release of aws-sdk-android.
1. git clone https://github.com/aws-amplify/aws-sdk-android
2. git checkout develop
3. Open build.gradle in aws-sdk-android as project in AndroidStudio
4. Select aws-sdk-android-kinesisvideo in the Android section of project view, then Build -> Make Module 'aws-sdk-android-kinesisvideo'
5. git clone https://github.com/awslabs/aws-sdk-android-samples
6. cp aws-sdk-android/aws-android-sdk-kinesisvideo/build/outputs/aar/aws-android-sdk-kinesisvideo-debug.aar aws-sdk-android-samples/AmazonKinesisVideoDemoApp/libs/
7. Open build.gradle in aws-sdk-android-samples/AmazonKinesisVideoDemoApp/ as project in AndroidStudio
8. Modify line 54 from "implementation ("com.amazonaws:aws-android-sdk-kinesisvideo:$aws_version@aar") { transitive = true }" to "implementation fileTree(dir: 'libs', include: ['.jar', '.aar'])"
9. "Gradle files have changed ..." would show up, click Sync Now and then Build -> Make Project.

Sorry for the lengthy instruction set but at this stage this might be the shortest path.

Thanks,
-ZH

**Comment by chintan2181997** [comment] 2019-07-03 19:43
I am getting below errors When i execute MAke module from your step 4.?

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':aws-android-sdk-core:getApi23'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'sh''
	at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:222)
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:202)
	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:342)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:86)
	at org.gradle.internal.operations.BuildOperationIdentifierPreservingRunnable.run(BuildOperationIdentifierPreservingRunnable.java:39)
	... 6 more
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'sh'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.internal.WindowsProcessLauncher.start(WindowsProcessLauncher.java:22)
	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:68)
	... 7 more
Caused by: java.io.IOException: Cannot run program "sh" (in directory "C:\Users\Owner\Downloads\aws-sdk-android-master\aws-sdk-android-master\aws-android-sdk-core"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 10 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 11 more

**Comment by kvasukib** [comment] 2019-07-03 19:59
@chintan2181997 Sorry for the inconvenience caused. I have documented the instructions to build the SDK here: https://github.com/aws-amplify/aws-sdk-android/blob/develop/README.md#pre-requisites-to-build-the-sdk

**Comment by kvasukib** [comment] 2019-07-03 20:49
@zhiyua-git Thank you for the update. I will update the libs with the latest.

**Closed** 2021-09-23 17:09 UTC
Labels: question, kinesis video
