### ISSUE TITLE
Deploy fails in amplify admin ui after saving and deploying

### ISSUE THREAD

**Issue by marenero1974** [aws-amplify/aws-sdk-android#2364] opened 2021-02-20 20:54 UTC
Hi,
i have a problem related to amplify admin ui, that doesn't permit me to update a table already created, i want to change the model of a dynamodb table.
In the home of amplify admin ui after saving and deployng my changes it says:

Update API | 20/2/2021, 15:21:44 | FAILED

What should be the problem?

Thanks

**Device Information (please complete the following information):**
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by richardmcclellan** [comment] 2021-02-22 15:51
Closing as duplicate of https://github.com/aws-amplify/amplify-adminui/issues/128

**Closed by richardmcclellan** 2021-02-22 15:51 UTC
