### ISSUE TITLE
Getting expired Id token and access token for valid refresh token

### ISSUE THREAD

**Issue by ranshine** [aws-amplify/aws-sdk-android#3145] opened 2023-01-11 14:19 UTC
I am using aws-amplify cognito library for oauth authentication, i am trying to fetch access token and id token for every 15 mins, sometimes i am getting expired access token and id token.

`    implementation 'com.amplifyframework:aws-auth-cognito:1.35.4'
`
Token fetching:
```
 Amplify.Auth.fetchAuthSession({ it ->
            val session = it as AWSCognitoAuthSession
            when (session.identityId.type) {
                AuthSessionResult.Type.SUCCESS -> {
                 // storing tokens
                   session.userPoolTokens.value?.idToken  // expired id token
                }
                AuthSessionResult.Type.FAILURE -> {
                    if (session.identityId.error != null) {
                       // logout
                    }
                }
            }
```

**Comment by eeatonaws** [comment] 2023-01-17 16:13
Closing this issue as it is a duplicate of [#2224](https://github.com/aws-amplify/amplify-android/issues/2224) in the Amplify Android repo. Please see issue [#2224](https://github.com/aws-amplify/amplify-android/issues/2224) for any updates.

**Closed by eeatonaws** 2023-01-17 16:13 UTC
Labels: bug, duplicate, cognito
