### ISSUE TITLE
isSignedIn behavior seems wrong

### ISSUE THREAD

**Issue by nicholasphair** [aws-amplify/aws-sdk-android#2955] opened 2022-07-25 05:41 UTC
**Describe the bug**
`isSignedIn()` returns `true` when a user is signed out.

**To Reproduce**
Call [isSignedIn][1] with a UserState of `SIGNED_OUT_USER_POOLS_TOKENS_INVALID`. 

I came across this after doing a sign-out on a user in the cognito console and observing the `isSignedIn` call is still returning `true`. 

**Which AWS service(s) are affected?**
The [Amplify Flutter Cognito libs][2] delegate to the library here. Specifically, when I make a call to [fetchAuthSession][3], it eventually executes the `isSignedIn` method. That implementation uses method channels to run this as platform-specifc code so it is not trivial (at least for me) to point to something like `currentUserState` instead.

While this might be an intentional design decision, and I considered filing the issue downstream, I do not think any consumer of the library should reasonably expect this behavior.

**Expected behavior**
My expectation is that when the user state is `SIGNED_OUT*` the call to `isSignedIn` will return `false`. 

**Screenshots**
N/A

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 31
 - Device: Emulator
 - Android Version: 12
 - Specific to simulators: No

**Additional context**
N/A

[1]: https://github.com/aws-amplify/aws-sdk-android/blob/main/aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/AWSMobileClient.java#L950-L963
[2]: https://github.com/aws-amplify/amplify-flutter/blob/main/packages/auth/amplify_auth_cognito/lib/method_channel_auth_cognito.dart
[3]: https://github.com/aws-amplify/amplify-flutter/blob/main/packages/auth/amplify_auth_cognito/lib/method_channel_auth_cognito.dart#L244

**Comment by gpanshu** [comment] 2022-07-26 14:21
Can you paste what you get from fetchAuthSession when the user is signedout from the console rather than signing out from the device explicitly ? 
You can also listen to the HUB event that is sent when the session is expired and then logout your user.

**Comment by nicholasphair** [comment] 2022-07-26 23:05
Hi @gpanshu - thanks for your response.

The case where I sign out from the device explicitly seems to work as expected. 

It is actually the case where the user was signed-out from the console that I am talking about. Ultimately, It just doesn't quite understand why when a user is in a signed out state (for w/e reason) that the `isSignedIn` method would return `True`.

To be honest, my particular problems might be elsewhere. Same behavior, just not caused by this method. Nonetheless, I think this issue remains.

**Comment by gpanshu** [comment] 2022-08-02 13:54
Hi @nicholasphair the isSignedIn remains true as this is how it's designed if the user has been signed out without calling the explicit signout as the signout reason could be token expiration. If you check the full response you get from a fetchAuthSession it will tell you that the token has been expired but the user has not been explicitely signed out. The reasoning for that is that you may want to perform a signin silently under the hood through biometric or some other mechanism instead of hard logging the user out. I am closing this issue as working as designed. If you feel otherwise feel free to open it up and provide more information why you would think it is an issue.

**Closed by gpanshu** 2022-08-02 13:54 UTC
Labels: bug, cognito
