### ISSUE TITLE
Error in uploading files to S3 with name containing special characters

### ISSUE THREAD

**Issue by depak330** [aws-amplify/aws-sdk-android#545] opened 2018-10-16 06:37 UTC
**Describe the bug**
i am using latest sdk for download image from s3 server. file name with space download perfectly .if file name with ä it through error.

file is already available on bucket .iOS library download file perfectly. problem in only in android sdk .show error The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: AAAAAAA).

**Comment by kvasukib** [comment] 2018-10-16 15:48
@depak330 Thank you for reporting to us. In this case, the client is expected to do the handling for special characters before passing it to the SDK.

**Comment by kvasukib** [comment] 2018-10-23 19:00
@depak330 This was a regression introduced in 2.7.4 and we reverted the changes introduced in 2.7.4. Can you upgrade to 2.7.6 and check if it fixes the issue?

**Comment by depak330** [comment] 2018-10-27 16:58
@kvasukib thank you for reply i will check tomorrow.

**Comment by muellerfr** [comment] 2018-11-20 20:40
This issue has been closed because of inactivity. Please open a new issue if are still encountering problems.

**Comment by depak330** [comment] 2018-11-22 04:20
@muellerfr  thanks for reply... actually this scenario i already handle from server side with rename file.

**Comment by depak330** [comment] 2019-01-01 06:46
@muellerfr bug not solved in v2.9.1 show error The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: ) but my file is exist on amazon bucket.

**Comment by muellerfr** [comment] 2019-01-02 19:53
Ok, I'll reopen the issue.

**Comment by kvasukib** [comment] 2019-01-02 19:55
@depak330 Sorry for the inconvenience caused. We are in the process of implementing a fix. I will let you know when the fix is released. Thank you!

**Comment by kvasukib** [comment] 2019-01-02 20:21
This is a duplicate of issue #526. We are tracking this issue in #526. We will capture all the details there.

**Closed by kvasukib** 2019-01-02 20:21 UTC
Labels: S3, question, requesting feedback
