### ISSUE TITLE
Not able to call AWSMobileClient.getInstance().getUserAttributes() after SignInState value DONE

### ISSUE THREAD

**Issue by imhashir** [aws-amplify/aws-sdk-android#1014] opened 2019-06-10 21:08 UTC
This issue started happening when I updated my AWS dependencies. On the previous version, it logs in perfectly. Following are my current dependencies:

```
implementation 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.13.4'
implementation 'com.amazonaws:aws-android-sdk-pinpoint:2.13.4'
implementation ('com.amazonaws:aws-android-sdk-mobile-client:2.13.4@aar') { transitive = true }
```

Here's my code:

```
AWSMobileClient.getInstance().initialize(mContext, new Callback<UserStateDetails>() {
            @Override
            public void onResult(UserStateDetails result) {
                AWSMobileClient.getInstance().signIn(username, password, null, new Callback<SignInResult>() {
                    @Override
                    public void onResult(SignInResult result) {
                        switch (result.getSignInState()) {
                            case DONE:
                                try {
                                    Map<String, String> userAttributes = AWSMobileClient.getInstance().getUserAttributes();
                                } catch (Exception e) {
                                    e.printStackTrace();
                                }
                                break;
                            case NEW_PASSWORD_REQUIRED:
                                break;
                        }
                    }

                    @Override
                    public void onError(Exception e) {
                        try {
                            throw e;
                        } catch (UserNotConfirmedException ex) {
                            AWSMobileClient.getInstance().signOut();
                        } catch (Exception ex) {
                            mOnSignInCompleteListener.onFailed(e);
                        }
                    }
                });
            }

            @Override
            public void onError(Exception e) {
                mOnSignInCompleteListener.onFailed(e);
            }
        });
```

It crashes when I call **AWSMobileClient.getInstance().getUserAttributes()**

Here's the log:
```
2019-06-11 01:35:23.749 5243-6084/com.test.app.aws D/AWSMobileClient: Inspecting user state details
2019-06-11 01:35:23.906 5243-6085/com.test.app.aws D/AWSMobileClient: _federatedSignIn: Putting provider and token in store
2019-06-11 01:35:24.069 5243-6085/com.test.app.aws D/CognitoCachingCredentialsProvider: Clearing credentials from SharedPreferences
2019-06-11 01:35:24.073 5243-6085/com.test.app.aws D/CognitoCachingCredentialsProvider: Identity id is changed
2019-06-11 01:35:24.073 5243-6085/com.test.app.aws D/CognitoCachingCredentialsProvider: Saving identity id to SharedPreferences
2019-06-11 01:35:24.076 5243-6085/com.test.app.aws D/CognitoCachingCredentialsProvider: Clearing credentials from SharedPreferences
2019-06-11 01:35:24.079 5243-6085/com.test.app.aws I/chatty: uid=10231(com.test.app.aws) Thread-16 identical 1 line
2019-06-11 01:35:24.080 5243-6085/com.test.app.aws D/CognitoCachingCredentialsProvider: Clearing credentials from SharedPreferences
2019-06-11 01:35:24.284 5243-6085/com.test.app.aws D/AWSMobileClient: Inspecting user state details
2019-06-11 01:35:24.285 5243-6085/com.test.app.aws D/AWSMobileClient: hasFederatedToken: false provider: cognito-idp.us-east-2.amazonaws.com/us-east-2_mes3WUdX7
2019-06-11 01:35:24.286 5243-6085/com.test.app.aws D/CognitoCachingCredentialsProvider: Clearing credentials from SharedPreferences
2019-06-11 01:35:24.288 5243-6085/com.test.app.aws D/CognitoCachingCredentialsProvider: Clearing credentials from SharedPreferences
2019-06-11 01:35:24.711 5243-6085/com.test.app.aws D/CognitoCachingCredentialsProvider: Identity id is changed
2019-06-11 01:35:24.711 5243-6085/com.test.app.aws D/CognitoCachingCredentialsProvider: Saving identity id to SharedPreferences
2019-06-11 01:35:24.761 5243-6085/com.test.app.aws D/CognitoCachingCredentialsProvider: Clearing credentials from SharedPreferences
2019-06-11 01:35:25.118 5243-6085/com.test.app.aws W/AWSMobileClient: Failed to federate tokens during sign-in
    java.lang.RuntimeException: Error in federating the token.
        at com.amazonaws.mobile.client.AWSMobileClient$8.run(AWSMobileClient.java:1484)
        at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
        at com.amazonaws.mobile.client.AWSMobileClient.federatedSignInWithoutAssigningState(AWSMobileClient.java:1414)
        at com.amazonaws.mobile.client.AWSMobileClient$6$1.onSuccess(AWSMobileClient.java:1156)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:745)
        at com.amazonaws.mobile.client.AWSMobileClient$6.run(AWSMobileClient.java:1142)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.amazonaws.services.cognitoidentity.model.InvalidIdentityPoolConfigurationException: Invalid identity pool configuration. Check assigned IAM roles for this pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: InvalidIdentityPoolConfigurationException; Request ID: 46811690-8bbf-11e9-975e-0b743f75f624)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:1658)
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getCredentialsForIdentity(AmazonCognitoIdentityClient.java:680)
        at com.amazonaws.auth.CognitoCredentialsProvider.populateCredentialsWithCognito(CognitoCredentialsProvider.java:782)
        at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:694)
        at com.amazonaws.auth.CognitoCredentialsProvider.refresh(CognitoCredentialsProvider.java:631)
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.refresh(CognitoCachingCredentialsProvider.java:510)
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.getIdentityId(CognitoCachingCredentialsProvider.java:452)
        at com.amazonaws.auth.CognitoCredentialsProvider.populateCredentialsWithCognito(CognitoCredentialsProvider.java:776)
        at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:694)
        at com.amazonaws.auth.CognitoCredentialsProvider.refresh(CognitoCredentialsProvider.java:631)
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.refresh(CognitoCachingCredentialsProvider.java:510)
        at com.amazonaws.mobile.client.AWSMobileClient.federateWithCognitoIdentity(AWSMobileClient.java:1515)
        at com.amazonaws.mobile.client.AWSMobileClient$8.run(AWSMobileClient.java:1471)
        at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115) 
        at com.amazonaws.mobile.client.AWSMobileClient.federatedSignInWithoutAssigningState(AWSMobileClient.java:1414) 
        at com.amazonaws.mobile.client.AWSMobileClient$6$1.onSuccess(AWSMobileClient.java:1156) 
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:745) 
        at com.amazonaws.mobile.client.AWSMobileClient$6.run(AWSMobileClient.java:1142) 
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101) 
        at java.lang.Thread.run(Thread.java:764) 
2019-06-11 01:35:25.119 5243-6085/com.test.app.aws D/AWSMobileClient: Inspecting user state details
2019-06-11 01:35:25.122 5243-6085/com.test.app.aws D/AWSMobileClient: waitForSignIn: userState:SIGNED_OUT
2019-06-11 01:35:25.122 5243-6085/com.test.app.aws W/System.err: java.lang.Exception: Operation requires a signed-in state
2019-06-11 01:35:25.124 5243-6085/com.test.app.aws W/System.err:     at com.amazonaws.mobile.client.AWSMobileClient$19.run(AWSMobileClient.java:2155)
2019-06-11 01:35:25.124 5243-6085/com.test.app.aws W/System.err:     at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
2019-06-11 01:35:25.124 5243-6085/com.test.app.aws W/System.err:     at com.amazonaws.mobile.client.AWSMobileClient.getUserAttributes(AWSMobileClient.java:2147)
2019-06-11 01:35:25.124 5243-6085/com.test.app.aws W/System.err:     at com.test.app.aws.controller.AuthController$4$1.onResult(AuthController.java:326)
2019-06-11 01:35:25.124 5243-6085/com.test.app.aws W/System.err:     at com.test.app.aws.controller.AuthController$4$1.onResult(AuthController.java:320)
2019-06-11 01:35:25.124 5243-6085/com.test.app.aws W/System.err:     at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:75)
2019-06-11 01:35:25.124 5243-6085/com.test.app.aws W/System.err:     at com.amazonaws.mobile.client.internal.InternalCallback.onResult(InternalCallback.java:62)
2019-06-11 01:35:25.124 5243-6085/com.test.app.aws W/System.err:     at com.amazonaws.mobile.client.AWSMobileClient$6$1.onSuccess(AWSMobileClient.java:1166)
2019-06-11 01:35:25.125 5243-6085/com.test.app.aws W/System.err:     at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:745)
2019-06-11 01:35:25.125 5243-6085/com.test.app.aws W/System.err:     at com.amazonaws.mobile.client.AWSMobileClient$6.run(AWSMobileClient.java:1142)
2019-06-11 01:35:25.125 5243-6085/com.test.app.aws W/System.err:     at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
2019-06-11 01:35:25.125 5243-6085/com.test.app.aws W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-06-11 01:35:25.126 5243-6085/com.test.app.aws W/System.err: java.lang.Exception: Operation requires a signed-in state
2019-06-11 01:35:25.126 5243-6085/com.test.app.aws W/System.err:     at com.amazonaws.mobile.client.AWSMobileClient$19.run(AWSMobileClient.java:2155)
2019-06-11 01:35:25.126 5243-6085/com.test.app.aws W/System.err:     at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
2019-06-11 01:35:25.126 5243-6085/com.test.app.aws W/System.err:     at com.amazonaws.mobile.client.AWSMobileClient.getUserAttributes(AWSMobileClient.java:2147)
2019-06-11 01:35:25.126 5243-6085/com.test.app.aws W/System.err:     at com.test.app.aws.controller.AuthController$4$1.onResult(AuthController.java:326)
2019-06-11 01:35:25.126 5243-6085/com.test.app.aws W/System.err:     at com.test.app.aws.controller.AuthController$4$1.onResult(AuthController.java:320)
2019-06-11 01:35:25.126 5243-6085/com.test.app.aws W/System.err:     at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:75)
2019-06-11 01:35:25.127 5243-6085/com.test.app.aws W/System.err:     at com.amazonaws.mobile.client.internal.InternalCallback.onResult(InternalCallback.java:62)
2019-06-11 01:35:25.127 5243-6085/com.test.app.aws W/System.err:     at com.amazonaws.mobile.client.AWSMobileClient$6$1.onSuccess(AWSMobileClient.java:1166)
2019-06-11 01:35:25.127 5243-6085/com.test.app.aws W/System.err:     at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:745)
2019-06-11 01:35:25.127 5243-6085/com.test.app.aws W/System.err:     at com.amazonaws.mobile.client.AWSMobileClient$6.run(AWSMobileClient.java:1142)
2019-06-11 01:35:25.127 5243-6085/com.test.app.aws W/System.err:     at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
2019-06-11 01:35:25.127 5243-6085/com.test.app.aws W/System.err:     at java.lang.Thread.run(Thread.java:764)
```

**Comment by kvasukib** [comment] 2019-06-12 19:44
@imhashir Thank you for reporting to us. I tried the following and I was able to retrieve the user attributes of the signed-in user when the `SignInState` is `DONE`.

```java
final CountDownLatch countDownLatch = new CountDownLatch(1);
        AWSMobileClient.getInstance().initialize(this, new Callback<UserStateDetails>() {
                    @Override
                    public void onResult(UserStateDetails userStateDetails) {
                        Log.i(TAG, "onResult: " + userStateDetails.getUserState());

                        try {
                            SignInResult signInResult = AWSMobileClient.getInstance().signIn(userName, password, null);
                            Log.d(TAG, "SignInState: " + signInResult.getSignInState()); // DONE

                            Map<String, String> userAttributes = AWSMobileClient.getInstance().getUserAttributes();
                            Log.d(TAG, "userAttributes: " + Arrays.toString(userAttributes.entrySet().toArray()));
                        } catch (Exception e) {
                            e.printStackTrace();
                        }

                        countDownLatch.countDown();
                    }

                    @Override
                    public void onError(Exception e) {
                        Log.e(TAG, "Initialization error: ", e);
                        countDownLatch.countDown();
                    }
                }
        );

        try {
            countDownLatch.await();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
```

```
2019-06-12 13:55:03.240 25988-26042/com.amazonaws.mobileconnectors.demo.awssdkforandroid D/LoginActivity: userAttributes: [sub=redacted, email_verified=true, phone_number_verified=false, phone_number=redacted, given_name=redacted, email=redacted@redacted.com]
```

From the logs you posted here, I can see that the signIn operation has not succeeded because it failed while federating the token.

Caused by: com.amazonaws.services.cognitoidentity.model.InvalidIdentityPoolConfigurationException: Invalid identity pool configuration. Check assigned IAM roles for this pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: InvalidIdentityPoolConfigurationException; Request ID: 46811690-8bbf-11e9-975e-0b743f75f624)

If a token needs to be federated with Cognito Identity pool, you need to have a Authenticated IAM role created and added to your Cognito Identity pool. Can you check this in your identity pool?

**Comment by imhashir** [comment] 2019-06-13 20:33
Thanks for your response. Everything is working on the current version of my application that uses the same identity pools/user pools but uses a previous API version. This issue seems to be happening after updating API version.
After a bit more search, I found that others are having similar issues on this API version.

One of them is this #942 and the other one is [this SO question](https://stackoverflow.com/questions/56133194/sign-out-status-user-awscognito-in-clean-installation-of-android-application).

**Comment by imhashir** [comment] 2019-06-14 09:55
I used the method mentioned at the end of [this reply](https://github.com/aws-amplify/aws-sdk-android/issues/942#issuecomment-491978498) and it worked. Don't know if it's going to have any bad impact or any other issue later on, but for now, it's working.

**Comment by kvasukib** [comment] 2019-07-03 21:27
Closing this issue. Please feel free to re-open if the issue still persists.

**Closed by kvasukib** 2019-07-03 21:27 UTC
Labels: AWSMobileClient, Question, Requesting Feedback
