### ISSUE TITLE
AWS IOT Reconnecting Issue 

### ISSUE THREAD

**Issue by yusufonderd** [aws-amplify/aws-sdk-android#394] opened 2018-01-09 07:10 UTC
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
   AWS IOT
* In what version of SDK are you facing the problem?
   2.6.12
* Is the issue limited to Simulators / Actual Devices?
   Actual Device
* Can your problem be resolved if you bump to a higher version of SDK?
 No
* Is this problem related to specific Android/OS version?
  Now 5.0.2 and 4.4.4
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

I'm following AndroidPubSubWebSocket sample code. Status is constantly reconnecting.

```
mqttManager.connect(credentialsProvider, AWSIotMqttClientStatusCallback { status, throwable ->
                runOnUiThread {
                    if (status == AWSIotMqttClientStatus.Connecting) {
                        log("Connecting...")
                    } else if (status == AWSIotMqttClientStatus.Connected) {
                        log("Connected")
                    } else if (status == AWSIotMqttClientStatus.Reconnecting) {
                        if (throwable != null) {
                            log("Connection error.")
                        }
                        log("Reconnecting")
                    } else if (status == AWSIotMqttClientStatus.ConnectionLost) {
                        if (throwable != null) {
                            log("Connection error.")
                            throwable.printStackTrace()
                        }
                        log("Disconnected")
                    } else {
                        log("Disconnected")
                    }
                }
            })

```

* Please include a stacktrace if applicable.

MainActivity : Connecting...
AWSIotMqttManager: onFailure: connection failed.
AWSIotMqttManager: schedule Reconnect attempt 0 of 10 in 4 seconds.
MainActivity : Reconnecting
AWSIotMqttManager: attempting to reconnect to mqtt broker
AWSIotMqttManager: Reconnect failed
AWSIotMqttManager: schedule Reconnect attempt 1 of 10 in 8 seconds.
MainActivity : Reconnecting
AWSIotMqttManager: attempting to reconnect to mqtt broker
AWSIotMqttManager: Reconnect failed
AWSIotMqttManager: schedule Reconnect attempt 2 of 10 in 16 seconds.
MainActivity : Reconnecting...

**Comment by bxpan** [comment] 2018-01-09 18:33
Does this issue also happen on newer version of Android OS ? Or is it just happening on 5.0.2 and 4.4.4?

**Comment by yusufonderd** [comment] 2018-01-11 14:18
It's happen different android versions. 4.4.4, 5.0.2, 7.0 . 
**Detailed logs:** 

01-11 16:56:07.180 15972-16010/com.trio_mobil.triotys I/AWSIotMqttManager: metrics collection is enabled, username: ?SDK=Android&Version=2.6.13
01-11 16:56:07.180 15972-16010/com.trio_mobil.triotys I/AWSIotMqttManager: resetting reconnect attempt and retry time
01-11 16:56:27.389 15972-16332/com.trio_mobil.triotys W/AWSIotMqttManager: onFailure: connection failed.
01-11 16:56:27.399 15972-16332/com.trio_mobil.triotys I/AWSIotMqttManager: schedule Reconnect attempt 0 of 10 in 4 seconds.
01-11 16:56:31.413 15972-16466/com.trio_mobil.triotys I/AWSIotMqttManager: attempting to reconnect to mqtt broker
01-11 16:56:46.248 15972-16685/com.trio_mobil.triotys W/AWSIotMqttManager: Reconnect failed 
01-11 16:56:46.258 15972-16685/com.trio_mobil.triotys I/AWSIotMqttManager: schedule Reconnect attempt 1 of 10 in 8 seconds.
01-11 16:56:54.266 15972-16744/com.trio_mobil.triotys I/AWSIotMqttManager: attempting to reconnect to mqtt broker
01-11 16:57:41.722 15972-17459/com.trio_mobil.triotys W/AWSIotMqttManager: Reconnect failed 
01-11 16:57:41.722 15972-17459/com.trio_mobil.triotys I/AWSIotMqttManager: schedule Reconnect attempt 2 of 10 in 16 seconds.
01-11 16:57:57.738 15972-17542/com.trio_mobil.triotys I/AWSIotMqttManager: attempting to reconnect to mqtt broker
01-11 16:58:27.537 15972-18106/com.trio_mobil.triotys W/AWSIotMqttManager: Reconnect failed 
01-11 16:58:27.537 15972-18106/com.trio_mobil.triotys I/AWSIotMqttManager: schedule Reconnect attempt 3 of 10 in 32 seconds.
01-11 16:58:59.578 15972-18201/com.trio_mobil.triotys I/AWSIotMqttManager: attempting to reconnect to mqtt broker
01-11 16:59:34.952 15972-19023/com.trio_mobil.triotys W/AWSIotMqttManager: Reconnect failed 
01-11 16:59:34.952 15972-19023/com.trio_mobil.triotys I/AWSIotMqttManager: schedule Reconnect attempt 4 of 10 in 64 seconds.
01-11 17:00:39.025 15972-19249/com.trio_mobil.triotys I/AWSIotMqttManager: attempting to reconnect to mqtt broker
01-11 17:01:03.369 15972-19249/com.trio_mobil.triotys E/AWSIotMqttManager: Failed to get credentials. AmazonClientException: 
                                                                           com.amazonaws.AmazonClientException: Unable to execute HTTP request: Read timed out
                                                                               at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
                                                                               at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
                                                                               ...
01-11 17:01:03.379 15972-19249/com.trio_mobil.triotys I/AWSIotMqttManager: schedule Reconnect attempt 4 of 10 in 64 seconds.
01-11 17:01:17.583 15972-20632/com.trio_mobil.triotys W/AWSIotMqttManager: Reconnect failed 
01-11 17:01:17.583 15972-20632/com.trio_mobil.triotys I/AWSIotMqttManager: schedule Reconnect attempt 5 of 10 in 64 seconds.
01-11 17:02:07.471 15972-20511/com.trio_mobil.triotys I/AWSIotMqttManager: attempting to reconnect to mqtt broker
01-11 17:02:21.645 15972-20721/com.trio_mobil.triotys I/AWSIotMqttManager: attempting to reconnect to mqtt broker
01-11 17:02:35.629 15972-20721/com.trio_mobil.triotys E/AWSIotMqttManager: Exception during reconnect, exception: 
                                                                           Connect already in progress (32110)
                                                                               at org.eclipse.paho.client.mqttv3.MqttAsyncClient.connect(MqttAsyncClient.java:533)
                                                                               at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.reconnectToSession(AWSIotMqttManager.java:903)
                                                                               ...
01-11 17:02:35.629 15972-20721/com.trio_mobil.triotys I/AWSIotMqttManager: schedule Reconnect attempt 7 of 10 in 64 seconds.
01-11 17:02:53.917 15972-21916/com.trio_mobil.triotys W/AWSIotMqttManager: Reconnect failed 
01-11 17:02:53.927 15972-21916/com.trio_mobil.triotys I/AWSIotMqttManager: schedule Reconnect attempt 7 of 10 in 64 seconds.
01-11 17:03:39.701 15972-21841/com.trio_mobil.triotys I/AWSIotMqttManager: attempting to reconnect to mqtt broker
01-11 17:03:57.999 15972-22114/com.trio_mobil.triotys I/AWSIotMqttManager: attempting to reconnect to mqtt broker
01-11 17:04:44.725 15972-22114/com.trio_mobil.triotys E/AWSIotMqttManager: Exception during reconnect, exception: 
                                                                           Connect already in progress (32110)
                                                                               at org.eclipse.paho.client.mqttv3.MqttAsyncClient.connect(MqttAsyncClient.java:533)
                                                                               at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.reconnectToSession(AWSIotMqttManager.java:903)
                                                                              ....
01-11 17:04:44.725 15972-22114/com.trio_mobil.triotys I/AWSIotMqttManager: schedule Reconnect attempt 9 of 10 in 64 seconds.
01-11 17:05:48.787 15972-23695/com.trio_mobil.triotys I/AWSIotMqttManager: attempting to reconnect to mqtt broker
01-11 17:06:55.873 15972-24660/com.trio_mobil.triotys W/AWSIotMqttManager: Reconnect failed 
01-11 17:06:55.903 15972-24660/com.trio_mobil.triotys I/AWSIotMqttManager: schedule Reconnect attempt 9 of 10 in 64 seconds.
01-11 17:07:59.955 15972-25563/com.trio_mobil.triotys I/AWSIotMqttManager: attempting to reconnect to mqtt broker
01-11 17:08:45.560 15972-26577/com.trio_mobil.triotys W/AWSIotMqttManager: Reconnect failed 
01-11 17:08:45.570 15972-26577/com.trio_mobil.triotys I/AWSIotMqttManager: schedule Reconnect attempt 10 of 10 in 64 seconds.
01-11 17:08:45.570 15972-26577/com.trio_mobil.triotys W/AWSIotMqttManager: schedule reconnect returns false
01-11 17:09:08.472 15972-25563/com.trio_mobil.triotys E/AWSIotMqttManager: Failed to get credentials. AmazonClientException: 
                                                                           com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "cognito-identity.us-east-1.amazonaws.com": No address associated with hostname
                                                                               at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
                                                                               at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
                                                                               ...
                                                                            Caused by: java.net.UnknownHostException: Unable to resolve host "cognito-identity.us-east-1.amazonaws.com": No address associated with hostname
                                                                               at java.net.InetAddress.lookupHostByName(InetAddress.java:394)
                                                                               at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
                                                                               at java.net.InetAddress.getAllByName(InetAddress.java:214)
                                                                               at com.android.okhttp.internal.Dns$1.getAllByName(Dns.java:28)
                                                                            ...
01-11 17:09:08.472 15972-25563/com.trio_mobil.triotys I/AWSIotMqttManager: schedule Reconnect attempt 10 of 10 in 64 seconds.
01-11 17:09:08.472 15972-25563/com.trio_mobil.triotys W/AWSIotMqttManager: schedule reconnect returns false
01-11 17:09:08.502 15972-27663/com.trio_mobil.triotys W/AWSIotMqttManager: Reconnect failed 
01-11 17:09:08.502 15972-27663/com.trio_mobil.triotys I/AWSIotMqttManager: schedule Reconnect attempt 11 of 10 in 64 seconds.
01-11 17:09:08.502 15972-27663/com.trio_mobil.triotys W/AWSIotMqttManager: schedule reconnect returns false

**Comment by bxpan** [comment] 2018-01-11 18:36
You are getting exception in getting credentials:
E/AWSIotMqttManager: Failed to get credentials. AmazonClientException:
com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "cognito-identity.us-east-1.amazonaws.com": No address associated with hostname
Could you check that your device have actual internet connection and that your cognito pool ID as well as IoT endpoint is correct? 

Thanks.

**Comment by yusufonderd** [comment] 2018-01-12 06:27
Internet connection exists. No problem in there.

**Comment by bxpan** [comment] 2018-01-12 17:40
Do you mean that the problem only occurs on some specific android version but not others? The SDK is not dependent on specific android OS version and should work across different android versions newer than 4.4. 

I also tested on Android 7.1.1, and it was able to connect successfully.

**Comment by yusufonderd** [comment] 2018-01-13 10:56
Yes problem occcurs some spesific versions. I also connect Android 7.1.1. My problem exists 4.4.4, 5.0.2 etc.

**Comment by bxpan** [comment] 2018-01-15 18:27
There is no dependency on specific Android OS version for the SDK. It should work on os version newer than 4.4. Please check your settings on your 5.0.2 and perhaps try out other 5.x versions of Android OS.

**Comment by erdog** [comment] 2018-01-16 19:09
We're seeing a similar problem on Android 6.0.1. However, it's intermittent. We've only seen this reconnecting problem once a month for the past 6 months.

Is the problem occurring intermittently for you?

**Comment by yusufonderd** [comment] 2018-01-16 21:47
Yes problem still exists.

**Comment by Hospes** [comment] 2018-02-12 10:10
The same problem for me even on Android 7.1.1, I'm trying to use AWSCredentialsProvider for IoTMqttManager and it can't connect to endpoint.
Credentials are good cause I'm using it for s3 and everything is fine. But mqtt manager doesn't provide any error messages and it only tries to reconnect all the time.

**Comment by NTCoding** [comment] 2018-02-12 14:45
I am having a similar problem - I can register a thing, create a certificate, and attach a policy as per the sample code. But when I try to connect, it just fails and works upto 10 attempts and crashes. No diagnostics or clues available.

**Comment by tonyteate** [comment] 2018-02-18 20:03
We're also seeing the exact same issue on Android 7.1.2, SDK version 2.6.15.

The client fails to connect initially, and remains stuck attempting to reconnect (stack trace is the same as op's). We've attempted providing credentials using both Cognito, as well as just a BasicAWSCredentials object.

**Comment by isha31** [comment] 2018-03-23 10:12
Hi. Is any solution available. I am facing the same issue. Please help me! This is my log output : 

`03-23 15:37:19.589 I/AWSIotMqttManager(12825): attempting to reconnect to mqtt broker
03-23 15:37:22.582 W/AWSIotMqttManager(12825): Reconnect failed 
03-23 15:37:22.582 I/AWSIotMqttManager(12825): schedule Reconnect attempt 1 of 10 in 8 seconds.Thread started:  #4

Thread finished:  #4
The thread 0x4 has exited with code 0 (0x0).
03-23 15:37:30.589 I/AWSIotMqttManager(12825): attempting to reconnect to mqtt broker
03-23 15:37:33.686 W/AWSIotMqttManager(12825): Reconnect failed 
Thread started:  #5
03-23 15:37:33.686 I/AWSIotMqttManager(12825): schedule Reconnect attempt 2 of 10 in 16 seconds.
Thread finished:  #5
The thread 0x5 has exited with code 0 (0x0).
03-23 15:37:49.702 I/AWSIotMqttManager(12825): attempting to reconnect to mqtt broker
03-23 15:37:52.746 W/AWSIotMqttManager(12825): Reconnect failed 
03-23 15:37:52.746 I/AWSIotMqttManager(12825): schedule Reconnect attempt 3 of 10 in 32 seconds.
Thread started:  #6
Thread finished:  #6
The thread 0x6 has exited with code 0 (0x0).
03-23 15:38:24.776 I/AWSIotMqttManager(12825): attempting to reconnect to mqtt broker
03-23 15:38:28.006 W/AWSIotMqttManager(12825): Reconnect failed 
Thread started:  #7
03-23 15:38:28.006 I/AWSIotMqttManager(12825): schedule Reconnect attempt 4 of 10 in 64 seconds.
03-23 15:39:32.069 I/AWSIotMqttManager(12825): attempting to reconnect to mqtt broker
03-23 15:39:35.186 W/AWSIotMqttManager(12825): Reconnect failed 
Thread started:  #8
03-23 15:39:35.186 I/AWSIotMqttManager(12825): schedule Reconnect attempt 5 of 10 in 64 seconds.
Thread finished:  #7
The thread 0x7 has exited with code 0 (0x0).
03-23 15:40:39.249 I/AWSIotMqttManager(12825): attempting to reconnect to mqtt broker
03-23 15:40:42.362 W/AWSIotMqttManager(12825): Reconnect failed 
03-23 15:40:42.362 I/AWSIotMqttManager(12825): schedule Reconnect attempt 6 of 10 in 64 seconds.Thread started:  #9
`

**Comment by icochico** [comment] 2018-06-16 02:11
Hi,

I am experiencing the same issue. Android 7.0 and `com.amazonaws:aws-android-sdk-iot:2.6.22`. mqttManager tries to connect but loses the connection and then tries to reconnect in a loop. Does anybody have a solution for this?

```
6-15 18:59:33.953 16252-16554/? I/AWSIotMqttManager: Reconnect successful
    Auto-resubscribe is enabled. Resubscribing to previous topics.
06-15 18:59:33.958 16252-16554/? W/AWSIotMqttManager: connection is Lost
06-15 18:59:33.958 16252-16554/? I/AWSIotMqttManager: schedule Reconnect attempt 5 of 10 in 64 seconds.
06-15 19:00:37.972 16252-16556/? I/AWSIotMqttManager: attempting to reconnect to mqtt broker
06-15 19:00:38.304 16252-16679/? I/AWSIotMqttManager: Reconnect successful
```

**Comment by icochico** [comment] 2018-06-16 22:54
Hello everyone,

Just want to give you an update, I found a solution and I want to share it for anybody that will experience this problem in the future. The problem lies with the fact that the `AWSIotMqttManager` is automatically autoreconnecting and does not allow Exceptions to be thrown and visualized on the logcat. All it takes is to do this: 

`mqttManager.setAutoReconnect(false);`

To be able to display Exceptions and debug the problem. 

Best,
Enrico

**Comment by aroravinay4** [comment] 2018-07-04 04:53
Hello folks,

The client fails to connect initially, and remains stuck attempting to reconnect.we have attempted providing credentials using both Cognito and basic AWS.

We are using  "UUID.randomUUID().toString() + System.currentTimeMillis();" for generating client id.

  07-03 19:45:59.840 12813-12813/com.net.pubsubandroidfinal D/com.net.pubsubandroidfinal.MainActivity: topic = hi 07-03 19:46:03.301 12813-12813/com.net.pubsubandroidfinal D/com.net.pubsubandroidfinal.MainActivity: clientId = e9a03b89-2b39-4b31-a854-6013300f810a1530627337890 07-03 19:46:03.443 12813-12813/com.net.pubsubandroidfinal I/AWSIotMqttManager: metrics collection is enabled, username: ?SDK=Android&Version=2.6.23 07-03 19:46:03.444 12813-12813/com.net.pubsubandroidfinal I/AWSIotMqttManager: resetting reconnect attempt and retry time 07-03 19:46:03.444 12813-12813/com.net.pubsubandroidfinal D/com.net.pubsubandroidfinal.MainActivity: Status = Connecting 07-03 19:46:05.673 12813-13522/com.net.pubsubandroidfinal W/AWSIotMqttManager: onFailure: connection failed. 07-03 19:46:05.673 12813-13522/com.net.pubsubandroidfinal D/com.net.pubsubandroidfinal.MainActivity: Status = Reconnecting 07-03 19:46:05.673 12813-13522/com.net.pubsubandroidfinal I/AWSIotMqttManager: schedule Reconnect attempt 0 of 10 in 4 seconds. 07-03 19:46:09.680 12813-13526/com.net.pubsubandroidfinal I/AWSIotMqttManager: attempting to reconnect to mqtt broker 07-03 19:46:11.970 12813-13561/com.net.pubsubandroidfinal W/AWSIotMqttManager: Reconnect failed 07-03 19:46:11.971 12813-13561/com.net.pubsubandroidfinal I/AWSIotMqttManager: schedule Reconnect attempt 1 of 10 in 8 seconds. 07-03 19:46:11.973 12813-13561/com.net.pubsubandroidfinal D/com.net.pubsubandroidfinal.MainActivity: Status = Reconnecting 07-03 19:46:19.982 12813-13565/com.net.pubsubandroidfinal I/AWSIotMqttManager: attempting to reconnect to mqtt broker 07-03 19:46:23.487 12813-13647/com.net.pubsubandroidfinal W/AWSIotMqttManager: Reconnect failed 07-03 19:46:23.488 12813-13647/com.net.pubsubandroidfinal I/AWSIotMqttManager: schedule Reconnect attempt 2 of 10 in 16 seconds. 07-03 19:46:23.489 12813-13647/com.net.pubsubandroidfinal D/com.net.pubsubandroidfinal.MainActivity: Status = Reconnecting 07-03 19:46:39.506 12813-13665/com.net.pubsubandroidfinal I/AWSIotMqttManager: attempting to reconnect to mqtt broker 07-03 19:46:41.914 12813-13782/com.net.pubsubandroidfinal W/AWSIotMqttManager: Reconnect failed.

Please help Us.
Thanks in advance.

**Comment by something15525** [comment] 2018-10-18 22:29
Any update on this? I'm having the same issue.

**Comment by something15525** [comment] 2018-10-19 21:12
Turns out this was just bad error messaging on Paho's/the SDKs part. I was parsing the private key into a `PKCS8EncodedKeySpec`, instead of a `RSAPrivateCrtKeySpec`. This is without using Cognito, using a private key and cert.

**Comment by jeremiasdsa** [comment] 2018-11-27 18:02
Same Problem

`I/AWSIotMqttManager: metrics collection is enabled, username: ?SDK=Android&Version=2.8.4
I/AWSIotMqttManager: resetting reconnect attempt and retry time
D/com.amazonaws.demo.androidpubsub.PubSubActivity: Status = Connecting
W/AWSIotMqttManager: onFailure: connection failed.
D/com.amazonaws.demo.androidpubsub.PubSubActivity: Status = ConnectionLost
E/com.amazonaws.demo.androidpubsub.PubSubActivity: Connection error.
                                                   MqttException (0) - java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
                                                       at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
                                                       at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:664)
                                                       at java.lang.Thread.run(Thread.java:764)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
                                                       at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.receiveHandshakeResponse(WebSocketHandshake.java:133)
                                                       at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.execute(WebSocketHandshake.java:74)
                                                       at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:77)
                                                       at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:650)
                                                       at java.lang.Thread.run(Thread.java:764) `

**Comment by JoniDS** [comment] 2018-12-14 09:41
To add to this:
I compiled the lib from source and printed the Throwable and reconnect never connects even if there is a network with connectivity:

`2018-12-14 10:38:18.919 6622-7062/com.mqtt.test I/AWSIotMqttManager: attempting to reconnect to mqtt broker
2018-12-14 10:38:22.868 6622-7073/com.mqtt.test E/AWSIotMqttManager: Reconnect failed 
    Connection lost (32109) - java.io.EOFException
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.io.EOFException
        at java.io.DataInputStream.readByte(DataInputStream.java:270)
        at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
        at java.lang.Thread.run(Thread.java:761) 
`

**Comment by desokroshan** [comment] 2018-12-18 18:40
@JoniDS `Connection lost (32109) - java.io.EOFException` is caused when the connection to the client is shut down by the broker. This can happen due to a variety of reasons unrelated to the sdk such as multiple clients connecting with same clientId, unsupported QoS value for the message or if client attempts to publish/subscribe to a topic for which they don't have permission. I would recommend looking at the broker logs to see why the connection was closed by the broker.

**Comment by desokroshan** [comment] 2018-12-24 18:35
@yusufonderd I was not able to reproduce the issue on Android version 5.0.2 with the latest version of the SDK. From your stack-trace, there are two different issues both of which are related to no/bad network connection on your android device/emulator :  
 
Firstly, i.e. `E/AWSIotMqttManager: Failed to get credentials. AmazonClientException:
com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host ` means that the application failed to get/refresh AWS Credentials as it was not able to connect to Cognito. You can add a check for reachability in your app before making call to getCredentials to ensure that you have network connectivity and avoid this error. 

The second Exception from the stacktrace i.e. `com.amazonaws.AmazonClientException: Unable to execute HTTP request: Read timed out` means that the service took longer to respond than your configured client-side timeout. Are you setting a custom [socket timeout](https://aws-amplify.github.io/aws-sdk-android/docs/reference/com/amazonaws/ClientConfiguration.html#setSocketTimeout-int-). This can again happen due to general network issues such as stale/slow network connections. 

I would recommend updating to the latest version of SDK and add a check for network connectivity before calling connect. Please let us know if the issue persists. 

@Hospes @icochico We will update the sdk to log reconnection errors and pass the exception in the user callback. 

@aroravinay4 @jeremiasdsa @isha31 The issue you raised is different from the op's issue. Would you mind opening a different issues for easier tracking and keeping this thread relevant to the original issue.

Thanks.

**Comment by desokroshan** [comment] 2019-01-04 18:59
@Hospes @icochico 
We have made some changes to the SDK recently.
With respect to logging and propagation of connection errors, the SDK now propagate and log connection/reconnection errors to the developer even if SDK attempts an automatic reconnect. This would help pinpoint the specific exception which caused the connection failure. Currently, even though the stacktrace may look similar but the underlying issue might be different. So its difficult to root cause the connection issue from the stack trace available.
Can you please try with the latest version of the SDK(2.10.0) and let me know if the issue persists.

**Comment by asweeney99** [comment] 2019-01-17 16:20
I was seeing this problem too trying to authenticate with Cognito. MQTT connection failed due to Authentication Handshake Exception. Android Version 8.0 and SDK 2.6.X Was working fine until last weekend. Couldn't understand it. I tried compiling with SDK 2.10.0 and 2.11. No luck. Then I noticed that my Android device was 5 minutes ahead of time. Changed the time back by 5 min. No connection problems. MQTT connected first time. Users should use network provided time on their local devices to stop token expiry I'm guessing. See this issue raised today #658

**Comment by desokroshan** [comment] 2019-01-17 17:19
@asweeney99 Thanks for pointing that out. I understand that you were running into reconnection loop but it would be helpful if you could share the specific underlying exception. Latest version of SDK(2.10.+) should produce detailed logs with specific connection errors. 
Also since we are tracking this in https://github.com/aws-amplify/aws-sdk-android/issues/658 and to avoid mixing of all the different connection issues on this thread, I will add the closing-soon label back.

**Comment by asweeney99** [comment] 2019-01-17 20:50
@desokroshan Same exception as @jeremiasdsa above. Thanks for the more verbose logging but I didn't need to follow them this time.

**Comment by jeremiasdsa** [comment] 2019-01-18 00:53
Hi guys, I did forget to post how I got my problem solved.
So, I just needed to set the device time to automatic mode.

**Comment by muellerfr** [comment] 2019-01-18 04:14
@asweeney99, can you try @jeremiasdsa suggestion and report back your findings please?

**Comment by asweeney99** [comment] 2019-01-18 08:00
@muellerfr that's what worked for me.

**Comment by muellerfr** [comment] 2019-01-18 15:54
Looks like the issue is resolved then, and I will go ahead and close the issue.  Please open a new issue if you are still encountering problems.

**Closed by muellerfr** 2019-01-18 15:54 UTC
Labels: IoT, bug, requesting feedback

**Comment by pradeep-techens** [comment] 2019-05-12 19:29
> Hi guys, I did forget to post how I got my problem solved.
> So, I just needed to set the device time to automatic mode.

@jeremiasdsa can you please me know the more details. I am facing the same issue but what you mean" I just needed to set the device time to automatic mode.".
Thanks in advance.

**Comment by asweeney99** [comment] 2019-05-13 09:33
@pradeep-techens He means go to your time and date settings on the phone or tablet that you are using to log in to your service. In those settings there is an option to enable automatic mode. You need to enable this setting. This will give your phone or tablet the correct time without having to update it manually.

**Comment by Aqsathemes** [comment] 2019-05-26 15:04
I have also seen the same problem on Android 7.0, API 24, SDK version 2.13.4.
Set the device time to automatic mode doesn't resolve the issue.
Help, please!

**Comment by rahulkapoor1** [comment] 2019-06-02 08:01
There can be multiple reasons for this issues including -
1. Cert mismatch in passed Keystore
2. Unexpected or non unique client Id, depending on cloud side implementation
3. Wrong pub, sub topics

**Comment by Aqsathemes** [comment] 2019-06-02 14:00
@rahulkapoor1 
I resolved this issue, thank you very much.
The problem is in the policy, I changed it from:
`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:*",
      "Resource": "arn:aws:iot:us-east-2:928634954636:topic/*"
    }
  ]
}`
To this:
`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iot:Publish",
        "iot:Connect",
        "iot:Receive",
        "iot:Subscribe",
        "iot:GetThingShadow",
        "iot:DeleteThingShadow",
        "iot:UpdateThingShadow"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}
`

**Comment by santaclawn** [comment] 2019-07-02 16:35
> 
> 
> I was seeing this problem too trying to authenticate with Cognito. MQTT connection failed due to Authentication Handshake Exception. Android Version 8.0 and SDK 2.6.X Was working fine until last weekend. Couldn't understand it. I tried compiling with SDK 2.10.0 and 2.11. No luck. Then I noticed that my Android device was 5 minutes ahead of time. Changed the time back by 5 min. No connection problems. MQTT connected first time. Users should use network provided time on their local devices to stop token expiry I'm guessing. See this issue raised today #658

My device was ahead of actual time. Then I set it to get the time automatic from net, it actually solved the problem! Thx.

**Comment by vdharmani** [comment] 2019-11-21 08:02
Getting Same issue when i re-connect the device and hit login then getting same issue in some android devices.


Unable to execute HTTP request: Hostname cognito-idp.eu-central-1.amazonaws.com not verified:
    certificate: sha1/zD3oLGOCYOtZiu3qfI7z4JGdlRM=
    DN: CN=cognito-idp.eu-central-1.amazonaws.com
    subjectAltNames: [cognito-idp.eu-central-1.amazonaws.com]

Thanks.

**Comment by yakubpashask** [comment] 2022-07-08 07:48
> 

You saved my day buddy thanks a ton!!!

**Comment by yakubpashask** [comment] 2022-07-08 07:53
> @rahulkapoor1
> I resolved this issue, thank you very much.
> The problem is in the policy, I changed it from:
> `{ "Version": "2012-10-17", "Statement": [ { "Effect": "Allow", "Action": "iot:*", "Resource": "arn:aws:iot:us-east-2:845234952158:topic/*" } ] }`
> To this:
> `{ "Version": "2012-10-17", "Statement": [ { "Effect": "Allow", "Action": [ "iot:Publish", "iot:Connect", "iot:Receive", "iot:Subscribe", "iot:GetThingShadow", "iot:DeleteThingShadow", "iot:UpdateThingShadow" ], "Resource": [ "*" ] } ] }`

You saved my day @Aqsathemes thanks a ton!!!
