### ISSUE TITLE
AWS IoT not connecting over Wifi for some Android devices

### ISSUE THREAD

**Issue by bijuC1983** [aws-amplify/aws-sdk-android#2185] opened 2020-10-17 03:05 UTC
**Describe the bug**

Our app sends some commands like pan, tilt etc., as JSON messages to AWS IoT
Core. The "thing" is a camera.

When the device is connected through WiFi, the AWS IoT connection is not
established and it keeps trying to reconnect.

The WiFi connection is strong and consistent, because I am able to see the live
feed from the camera using a WebRTC channel without any frame loss at the same
time.

The IoT connection does establish when the Wifi is switched off, and the
connection falls back to using data on my 4G network.

**Which AWS service(s) are affected?**

AWS IoT Core

**Expected behavior**

The AWS IoT connection should be established seamlessly, be it on Wifi or a mobile data network.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.19.0
 - Device: Redmi Note 5 Pro
 - Android Version: Android 9
 - Specific to simulators: NO

**Comment by shawzyen** [comment] 2020-10-19 17:02
I have the same issue. The app under wifi environment throws the error: isConnected failed: ENETUNREACH (Network is unreachable). The alternative under cellular data environment or simulator, it works fine. 

This issue bothered me for several days.

**Comment by bijuC1983** [comment] 2020-10-19 19:16
Hello @shawzyen, were you able to find a solution for the issue?

**Comment by jamesonwilliams** [comment] 2020-10-20 05:50
@bijuC1983 @shawzyen curious is this may be related to https://github.com/aws-amplify/aws-sdk-android/issues/2105.

Try visiting http://test-ipv6.com/ while on your WiFi network(s), to see if you have IPv6 support.

**Comment by shawzyen** [comment] 2020-10-20 15:49
@jamesonwilliams Thanks for your reply. I think the issue is caused by the router that does not support IPv6. So is there any way to let the Android device connect to the AWS IoT in IPv4?

**Comment by jamesonwilliams** [comment] 2020-10-20 17:16
Closing in favor of #2105. Let's track a discussion, there, @shawzyen.

**Closed by jamesonwilliams** 2020-10-20 17:16 UTC
Labels: Duplicate, IoT, Needs Info from Requester
