### ISSUE TITLE
Token didn't get refresh after expiry when Amplify.FetchAuthSession is called

### ISSUE THREAD

**Issue by vishalmishra** [aws-amplify/aws-sdk-android#2552] opened 2021-07-26 15:10 UTC
**Describe the bug**
Hi Team
We need to send Bearer Token to our rest API so that we can authenticate the requests in backend. So we wrote an interceptor which we attach to all retrofit calls of the API. Once this went live for most of the users it's working fine but for few users we are receiving expired token at the backend even if they have just signed in on the app.
Here is the intercept logic to get token

**Code**

@kotlin.jvm.Throws(IOException::class)
    override fun intercept(chain: Interceptor.Chain): Response {
        val request: Request = chain.request()
        return try {
            Amplify.Auth.fetchAuthSession(
                { Log.i("AmplifyQuickstart", "Auth session = $it") },
                { Log.e("AmplifyQuickstart", "Failed to fetch auth session") }
            )
            val user = Amplify.Auth.currentUser
            if (user == null) {
                throw Exception("User is not logged in.")
            } else {
                val cognitoAuthPlugin = Amplify.Auth.getPlugin("awsCognitoAuthPlugin")
                val mobileClient = cognitoAuthPlugin.escapeHatch as AWSMobileClient
                var idToken = mobileClient.tokens.idToken.tokenString
                if (idToken.isNullOrEmpty()) {
                    throw Exception("idToken is null")
                } else {
                    val modifiedRequest = request.newBuilder()
                        .addHeader(X_AWS_ID_TOKEN, "Bearer $idToken")
                        .build()
                    chain.proceed(modifiedRequest)
                }
            }
        } catch (e: Exception) {
            throw IOException(e.message)
        }
    }
    
Can you please help us identify what could be the possible course of this?

**Environment Information (please complete the following information):**
 - com.amplifyframework:aws-auth-cognito:1.18.0

**Comment by rjuliano** [comment] 2021-07-29 17:38
Duplicate of https://github.com/aws-amplify/amplify-android/issues/1431. Will track progress on that issue

**Closed by rjuliano** 2021-07-29 17:38 UTC
