### ISSUE TITLE
KeyProvider23 keyStore.containsAlias(keyAlias)

### ISSUE THREAD

**Issue by BoykoDmytro** [aws-amplify/aws-sdk-android#1460] opened 2020-01-30 14:52 UTC
**Describe the bug**
Login via cognito is stucked on meizu M5s on keyStore.containsAlias(keyAlias) in KeyProvider23 class. There is no callback or failure. 

**To Reproduce**
Login via with cognito certain user which has been already registered in conginto pool.
```
        val cognitoUser = cognitoUserPool.getUser(email)
        cognitoUser.getSessionInBackground(AuthenticationHandlerImpl(it, pass))

class AuthenticationHandlerImpl(
    private val continuation: CancellableContinuation<PendingResult>,
    private val password: String
) : AuthenticationHandler {

    override fun onSuccess(session: CognitoUserSession?, newDevice: CognitoDevice?) {
        val accessToken = session?.idToken?.jwtToken
        val refreshToken = session?.refreshToken?.token
        if (accessToken.isNullOrBlank()) {
            continuation.resume(ErrorResult(AwsCognitoSessionManager.NO_ACCESS_TOKEN_ERROR, null))
            return
        }
        if (refreshToken.isNullOrBlank()) {
            continuation.resume(ErrorResult(AwsCognitoSessionManager.NO_REFRESH_TOKEN_ERROR, null))
            return
        }
        continuation.resume(Success(AuthCredentials(accessToken, refreshToken)))
    }

    override fun onFailure(exception: Exception?) {
        continuation.resume(ErrorResult(1, exception?.message))
    }

    override fun getAuthenticationDetails(
        continuation: AuthenticationContinuation,
        userId: String?
    ) {
        val authenticationDetails = AuthenticationDetails(userId, password, null)
        continuation.setAuthenticationDetails(authenticationDetails)
        continuation.continueTask()
    }

    override fun authenticationChallenge(continuation: ChallengeContinuation) {
        continuation.continueTask()
    }

    override fun getMFACode(continuation: MultiFactorAuthenticationContinuation) {
        continuation.continueTask()
    }

}
```

**Cognito, aws core sdk**

**Expected behavior**
User should successfully logged in.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.6.17
 - Device: Meizu, M5s
 - Android Version: Android 9
 - Specific to simulators: No

**Comment by raphkim** [comment] 2020-01-31 19:05
Hi @BoykoDmytro ,

Thank you for reaching out to us. In order to assist you better we are going to need more information. Would you be able to provide us with the device log so that we can identify the root cause? Thank you.

**Comment by BoykoDmytro** [comment] 2020-02-03 16:50
Please, write what kind of information do you need. Should I enable the logs in AWS SDK?

**Comment by raphkim** [comment] 2020-02-03 19:25
Hi @BoykoDmytro ,

The logcat should suffice for this at the moment. Please refer to [this](https://android.stackexchange.com/questions/14430/how-can-i-view-and-examine-the-android-log)

**Comment by BoykoDmytro** [comment] 2020-02-06 15:30
`E/LoginPresenter$login: Logggggggggg
W/CognitoUserSession: CognitoUserSession is not valid because idToken is null.
D/NativeCrypto: ssl=0x7f74946080 sslRead buf=0x7f74973000 len=2048,timeo=15000
I/AWSKeyValueStore: Detected Android API Level = 23
I/AWSKeyValueStore: Creating the AWSKeyValueStore with key for sharedPreferencesForData = CognitoIdentityProviderDeviceCache
D/NativeCrypto: ssl=0x7f74946080 sslRead buf=0x7f7593d000 len=2048,timeo=10
D/NativeCrypto: ssl=0x7f74946080 sslWrite buf=0x7f7593d000 len=392 write_timeout_millis=0
D/NativeCrypto: ssl=0x7f74946080 sslWrite buf=0x7f7593d000 len=2048 write_timeout_millis=0
D/NativeCrypto: ssl=0x7f74946080 sslWrite buf=0x7f7593d000 len=406 write_timeout_millis=0
D/NativeCrypto: ssl=0x7f74946080 sslRead buf=0x7f7593d000 len=2048,timeo=15000
D/libc-netbsd: [getaddrinfo]: hostname=****; servname=(null); netid=0; mark=0
D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
I/System.out: [CDS]connect[****/****] tm:15
I/System.out: [socket][/****] connected
D/libc-netbsd: [getaddrinfo]: hostname=****; servname=(null); netid=0; mark=0
D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
D/NativeCrypto: ssl=0x7f74946d00 NativeCrypto_SSL_do_handshake fd=0x7f770f96a8 shc=0x7f770f96ac timeout_millis=15000 client_mode=1 npn=0x0
D/NativeCrypto: doing handshake ++
D/NativeCrypto: ssl=0x7f74946d00 info_callback where=0x10 ret=1
D/NativeCrypto: ssl=0x7f74946d00 handshake start in CINIT  before connect initialization
D/NativeCrypto: ssl=0x7f74946d00 info_callback calling handshakeCompleted
D/NativeCrypto: ssl=0x7f74946d00 info_callback completed
D/NativeCrypto: ssl=0x7f74946d00 info_callback where=0x1001 ret=1
D/NativeCrypto: ssl=0x7f74946d00 SSL_connect:CINIT  before connect initialization
D/NativeCrypto: ssl=0x7f74946d00 info_callback ignored
D/NativeCrypto: ssl=0x7f74946d00 info_callback where=0x1001 ret=1
D/NativeCrypto: ssl=0x7f74946d00 SSL_connect:3WCH_A SSLv3 write client hello A
D/NativeCrypto: ssl=0x7f74946d00 info_callback ignored
D/NativeCrypto: ssl=0x7f74946d00 info_callback where=0x1002 ret=-1
D/NativeCrypto: ssl=0x7f74946d00 SSL_connect:error exit in 3RSH_A SSLv3 read server hello A
D/NativeCrypto: ssl=0x7f74946d00 info_callback ignored
D/NativeCrypto: doing handshake -- ret=-1
D/NativeCrypto: ssl=0x7f74946d00 NativeCrypto_SSL_do_handshake ret=-1 errno=11 sslError=2 timeout_millis=15000
D/NativeCrypto: ssl=0x7f74946080 sslRead buf=0x7f7593d000 len=2048,timeo=15000
D/NativeCrypto: doing handshake ++
D/NativeCrypto: ssl=0x7f74946d00 info_callback where=0x1001 ret=1
D/NativeCrypto: ssl=0x7f74946d00 SSL_connect:3RSH_A SSLv3 read server hello A
D/NativeCrypto: ssl=0x7f74946d00 info_callback ignored
D/NativeCrypto: ssl=0x7f74946d00 info_callback where=0x1001 ret=1
D/NativeCrypto: ssl=0x7f74946d00 SSL_connect:3RCCS_ SSLv3 read change cipher spec
D/NativeCrypto: ssl=0x7f74946d00 info_callback ignored
D/NativeCrypto: ssl=0x7f74946d00 info_callback where=0x1001 ret=1
D/NativeCrypto: ssl=0x7f74946d00 SSL_connect:3RFINA SSLv3 read finished A
D/NativeCrypto: ssl=0x7f74946d00 info_callback ignored
D/NativeCrypto: ssl=0x7f74946d00 info_callback where=0x1001 ret=1
D/NativeCrypto: ssl=0x7f74946d00 SSL_connect:3WCCSA SSLv3 write change cipher spec A
D/NativeCrypto: ssl=0x7f74946d00 info_callback ignored
D/NativeCrypto: ssl=0x7f74946d00 info_callback where=0x1001 ret=1
D/NativeCrypto: ssl=0x7f74946d00 SSL_connect:3WFINA SSLv3 write finished A
D/NativeCrypto: ssl=0x7f74946d00 info_callback ignored
D/NativeCrypto: ssl=0x7f74946d00 info_callback where=0x1001 ret=1
D/NativeCrypto: ssl=0x7f74946d00 SSL_connect:3FLUSH SSLv3 flush data
D/NativeCrypto: ssl=0x7f74946d00 info_callback ignored
D/NativeCrypto: ssl=0x7f74946d00 info_callback where=0x20 ret=1
D/NativeCrypto: ssl=0x7f74946d00 handshake done in SSLOK  SSL negotiation finished successfully
D/NativeCrypto: ssl=0x7f74946d00 info_callback calling handshakeCompleted
D/NativeCrypto: ssl=0x7f74946d00 info_callback completed
D/NativeCrypto: ssl=0x7f74946d00 info_callback where=0x1002 ret=1
D/NativeCrypto: ssl=0x7f74946d00 SSL_connect:ok exit in SSLOK  SSL negotiation finished successfully
D/NativeCrypto: ssl=0x7f74946d00 info_callback ignored
D/NativeCrypto: doing handshake -- ret=1
I/System.out: gba_cipher_suite:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
D/NativeCrypto: ssl=0x7f74946d00 sslWrite buf=0x7f76fa5800 len=402 write_timeout_millis=0
D/NativeCrypto: ssl=0x7f74946d00 sslWrite buf=0x7f76fa5800 len=2048 write_timeout_millis=0
D/NativeCrypto: ssl=0x7f74946d00 sslWrite buf=0x7f76fa5800 len=1504 write_timeout_millis=0
D/NativeCrypto: ssl=0x7f74946d00 sslRead buf=0x7f76fa5800 len=2048,timeo=15000
D/NativeCrypto: ssl=0x7f74946080 sslRead buf=0x7f7595b800 len=2048,timeo=10
D/NativeCrypto: ssl=0x7f74946080 sslWrite buf=0x7f7595b800 len=402 write_timeout_millis=0
D/NativeCrypto: ssl=0x7f74946080 sslWrite buf=0x7f7595b800 len=2048 write_timeout_millis=0
D/NativeCrypto: ssl=0x7f74946080 sslWrite buf=0x7f7595b800 len=1504 write_timeout_millis=0
D/NativeCrypto: ssl=0x7f74946080 sslRead buf=0x7f7595b800 len=2048,timeo=15000
D/NativeCrypto: ssl=0x7f74946d00 sslRead buf=0x7f76fa5800 len=2048,timeo=15000
D/NativeCrypto: ssl=0x7f74946d00 sslRead buf=0x7f76fa5800 len=2048,timeo=15000
D/NativeCrypto: ssl=0x7f74946080 sslRead buf=0x7f7595b800 len=2048,timeo=15000
D/NativeCrypto: ssl=0x7f74946080 sslRead buf=0x7f7595b800 len=2048,timeo=15000
`

**Comment by raphkim** [comment] 2020-02-07 19:33
Thank you for providing the log @BoykoDmytro 

Would you be able to verify if the bug can be reproduced in the most recent SDK release (v2.16.8)? There have been several patches regarding KeyStore in the past since the version you are using (v2.6.17) and it is possible that the issue you are experiencing has been fixed already in more recent releases.

**Comment by BoykoDmytro** [comment] 2020-03-12 12:56
`W/CognitoUserSession: CognitoUserSession is not valid because idToken is null.
I/AWSKeyValueStore: Detected Android API Level = 23
I/AWSKeyValueStore: Creating the AWSKeyValueStore with key for sharedPreferencesForData = CognitoIdentityProviderDeviceCache
D/libc-netbsd: [getaddrinfo]: hostname=cognito-idp.us-east-1.amazonaws.com; servname=(null); netid=0; mark=0
D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
D/libc-netbsd: [getaddrinfo]: hostname=cognito-idp.us-east-1.amazonaws.com; servname=(null); netid=0; mark=0
D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=0
D/libc-netbsd: getaddrinfo: cognito-idp.us-east-1.amazonaws.com get result from proxy gai_error = 0
D/FlymeTrafficTracking: tag  (68) **** Thread-441 uid 10093
I/System.out: [CDS]connect[cognito-idp.us-east-1.amazonaws.com/54.209.125.172:443] tm:15
D/Posix: [Posix_connect Debug]Process **** :443 
D/libc-netbsd: [getaddrinfo]: hostname=cognito-idp.us-east-1.amazonaws.com; servname=(null); netid=0; mark=0
D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
D/NativeCrypto: ssl=0x7f69257680 NativeCrypto_SSL_do_handshake fd=0x7f67c6c6e8 shc=0x7f67c6c6ec timeout_millis=15000 client_mode=1 npn=0x0
D/NativeCrypto: doing handshake ++
D/NativeCrypto: ssl=0x7f69257680 info_callback where=0x10 ret=1
D/NativeCrypto: ssl=0x7f69257680 handshake start in CINIT  before connect initialization
D/NativeCrypto: ssl=0x7f69257680 info_callback calling handshakeCompleted
D/NativeCrypto: ssl=0x7f69257680 info_callback completed
D/NativeCrypto: ssl=0x7f69257680 info_callback where=0x1001 ret=1
D/NativeCrypto: ssl=0x7f69257680 SSL_connect:CINIT  before connect initialization
D/NativeCrypto: ssl=0x7f69257680 info_callback ignored
D/NativeCrypto: ssl=0x7f69257680 info_callback where=0x1001 ret=1
D/NativeCrypto: ssl=0x7f69257680 SSL_connect:3WCH_A SSLv3 write client hello A
D/NativeCrypto: ssl=0x7f69257680 info_callback ignored
D/NativeCrypto: ssl=0x7f69257680 info_callback where=0x1002 ret=-1
D/NativeCrypto: ssl=0x7f69257680 SSL_connect:error exit in 3RSH_A SSLv3 read server hello A
D/NativeCrypto: ssl=0x7f69257680 info_callback ignored
D/NativeCrypto: doing handshake -- ret=-1
D/NativeCrypto: ssl=0x7f69257680 NativeCrypto_SSL_do_handshake ret=-1 errno=11 sslError=2 timeout_millis=15000
D/NativeCrypto: doing handshake ++
D/NativeCrypto: ssl=0x7f69257680 info_callback where=0x1001 ret=1
D/NativeCrypto: ssl=0x7f69257680 SSL_connect:3RSH_A SSLv3 read server hello A
D/NativeCrypto: ssl=0x7f69257680 info_callback ignored
D/NativeCrypto: ssl=0x7f69257680 info_callback where=0x1002 ret=-1
D/NativeCrypto: ssl=0x7f69257680 SSL_connect:error exit in 3RSC_A SSLv3 read server certificate A
D/NativeCrypto: ssl=0x7f69257680 info_callback ignored
D/NativeCrypto: doing handshake -- ret=-1
D/NativeCrypto: ssl=0x7f69257680 NativeCrypto_SSL_do_handshake ret=-1 errno=11 sslError=2 timeout_millis=15000
D/NativeCrypto: doing handshake ++
D/NativeCrypto: ssl=0x7f69257680 info_callback where=0x1002 ret=-1
D/NativeCrypto: ssl=0x7f69257680 SSL_connect:error exit in 3RSC_A SSLv3 read server certificate A
D/NativeCrypto: ssl=0x7f69257680 info_callback ignored
D/NativeCrypto: doing handshake -- ret=-1
D/NativeCrypto: ssl=0x7f69257680 NativeCrypto_SSL_do_handshake ret=-1 errno=11 sslError=2 timeout_millis=15000
D/NativeCrypto: doing handshake ++
D/NativeCrypto: ssl=0x7f69257680 info_callback where=0x1002 ret=-1
D/NativeCrypto: ssl=0x7f69257680 SSL_connect:error exit in 3RSC_A SSLv3 read server certificate A
D/NativeCrypto: ssl=0x7f69257680 info_callback ignored
D/NativeCrypto: doing handshake -- ret=-1
D/NativeCrypto: ssl=0x7f69257680 NativeCrypto_SSL_do_handshake ret=-1 errno=11 sslError=2 timeout_millis=15000
D/NativeCrypto: doing handshake ++
E/NativeCrypto: ssl=0x7f69257680 cert_verify_callback x509_store_ctx=0x7f67c6c3b0 arg=0x0
E/NativeCrypto: ssl=0x7f69257680 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
D/NativeCrypto: ssl=0x7f69257680 cert_verify_callback => 1
D/NativeCrypto: ssl=0x7f69257680 info_callback where=0x1001 ret=1
D/NativeCrypto: ssl=0x7f69257680 SSL_connect:3RSC_A SSLv3 read server certificate A
D/NativeCrypto: ssl=0x7f69257680 info_callback ignored
D/NativeCrypto: ssl=0x7f69257680 info_callback where=0x1001 ret=1
D/NativeCrypto: ssl=0x7f69257680 SSL_connect:3RSKEA SSLv3 read server key exchange A
D/NativeCrypto: ssl=0x7f69257680 info_callback ignored
D/NativeCrypto: ssl=0x7f69257680 info_callback where=0x1001 ret=1
D/NativeCrypto: ssl=0x7f69257680 SSL_connect:3RSD_A SSLv3 read server done A
D/NativeCrypto: ssl=0x7f69257680 info_callback ignored
D/NativeCrypto: ssl=0x7f69257680 info_callback where=0x1001 ret=1
D/NativeCrypto: ssl=0x7f69257680 SSL_connect:3WCKEA SSLv3 write client key exchange A
D/NativeCrypto: ssl=0x7f69257680 info_callback ignored
D/NativeCrypto: ssl=0x7f69257680 info_callback where=0x1001 ret=1
D/NativeCrypto: ssl=0x7f69257680 SSL_connect:3WCCSA SSLv3 write change cipher spec A
D/NativeCrypto: ssl=0x7f69257680 info_callback ignored
D/NativeCrypto: ssl=0x7f69257680 info_callback where=0x1001 ret=1
D/NativeCrypto: ssl=0x7f69257680 SSL_connect:3WFINA SSLv3 write finished A
D/NativeCrypto: ssl=0x7f69257680 info_callback ignored
D/NativeCrypto: ssl=0x7f69257680 info_callback where=0x1001 ret=1
D/NativeCrypto: ssl=0x7f69257680 SSL_connect:3FLUSH SSLv3 flush data
D/NativeCrypto: ssl=0x7f69257680 info_callback ignored
D/NativeCrypto: ssl=0x7f69257680 info_callback where=0x1002 ret=-1
D/NativeCrypto: ssl=0x7f69257680 SSL_connect:error exit in UNKWN  SSLv3 read server session ticket A
D/NativeCrypto: ssl=0x7f69257680 info_callback ignored
D/NativeCrypto: doing handshake -- ret=-1
D/NativeCrypto: ssl=0x7f69257680 NativeCrypto_SSL_do_handshake ret=-1 errno=11 sslError=2 timeout_millis=15000
D/NativeCrypto: doing handshake ++
D/NativeCrypto: ssl=0x7f69257680 info_callback where=0x1001 ret=1
D/NativeCrypto: ssl=0x7f69257680 SSL_connect:UNKWN  SSLv3 read server session ticket A
D/NativeCrypto: ssl=0x7f69257680 info_callback ignored
D/NativeCrypto: ssl=0x7f69257680 info_callback where=0x1001 ret=1
D/NativeCrypto: ssl=0x7f69257680 SSL_connect:3RCCS_ SSLv3 read change cipher spec
D/NativeCrypto: ssl=0x7f69257680 info_callback ignored
D/NativeCrypto: ssl=0x7f69257680 info_callback where=0x1001 ret=1
D/NativeCrypto: ssl=0x7f69257680 SSL_connect:3RFINA SSLv3 read finished A
D/NativeCrypto: ssl=0x7f69257680 info_callback ignored
D/NativeCrypto: ssl=0x7f69257680 info_callback where=0x20 ret=1
D/NativeCrypto: ssl=0x7f69257680 handshake done in SSLOK  SSL negotiation finished successfully
D/NativeCrypto: ssl=0x7f69257680 info_callback calling handshakeCompleted
D/NativeCrypto: ssl=0x7f69257680 info_callback completed
D/NativeCrypto: ssl=0x7f69257680 info_callback where=0x1002 ret=1
D/NativeCrypto: ssl=0x7f69257680 SSL_connect:ok exit in SSLOK  SSL negotiation finished successfully
D/NativeCrypto: ssl=0x7f69257680 info_callback ignored
D/NativeCrypto: doing handshake -- ret=1
D/NativeCrypto: ssl=0x7f69257680 NativeCrypto_SSL_get_certificate => NULL
I/System.out: gba_cipher_suite:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
D/FlymeTrafficTracking: tag  (71) **** Thread-441 uid 10093
D/NativeCrypto: ssl=0x7f69257680 sslWrite buf=0x7f6902a000 len=406 write_timeout_millis=0
D/NativeCrypto: ssl=0x7f69257680 sslWrite buf=0x7f6902a000 len=2048 write_timeout_millis=0
D/NativeCrypto: ssl=0x7f69257680 sslWrite buf=0x7f6902a000 len=337 write_timeout_millis=0
D/NativeCrypto: ssl=0x7f69257680 sslRead buf=0x7f6902a000 len=2048,timeo=15000
D/NativeCrypto: ssl=0x7f69257680 sslRead buf=0x7f6902a000 len=2048,timeo=15000
D/FlymeTrafficTracking: untag(68) **** Thread-441 uid 10093 761ms
I/AWSKeyValueStore: Detected Android API Level = 23
I/AWSKeyValueStore: Creating the AWSKeyValueStore with key for sharedPreferencesForData = CognitoIdentityProviderDeviceCache
D/FlymeTrafficTracking: tag  (68) **** Thread-441 uid 10093
D/NativeCrypto: ssl=0x7f69257680 sslRead buf=0x7f6808d800 len=2048,timeo=10
D/NativeCrypto: ssl=0x7f69257680 sslWrite buf=0x7f6808d800 len=416 write_timeout_millis=0
D/NativeCrypto: ssl=0x7f69257680 sslWrite buf=0x7f6808d800 len=2048 write_timeout_millis=0
D/NativeCrypto: ssl=0x7f69257680 sslWrite buf=0x7f6808d800 len=1445 write_timeout_millis=0
D/NativeCrypto: ssl=0x7f69257680 sslRead buf=0x7f6808d800 len=2048,timeo=15000
D/NativeCrypto: ssl=0x7f69257680 sslRead buf=0x7f6808d800 len=2048,timeo=15000
D/FlymeTrafficTracking: untag(68) **** Thread-441 uid 10093 415ms
I/System: FinalizerDaemon: finalize objects = 553
`

I have checked the latest sdk **version 2.16.8**.

**Comment by BoykoDmytro** [comment] 2020-04-02 13:45
any updates?

**Comment by jpignata** [comment] 2020-04-02 14:14
It appears that the device itself cannot establish an HTTPS connection with Cognito. In my read of the logs, it seems like it's trying to use SSLv3, which isn't supported by Cognito:

```console
$ curl -3 https://cognito-idp.us-east-1.amazonaws.com     

curl: (35) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
```

I also notice there seem to be myriad SSL issues reported in other popular projects around SSL and Meizu M5 devices such as in OkHttp (see https://github.com/square/okhttp/issues/3301).

Are you seeing issues connecting via raw HTTPS in other parts of the SDK or in other places in your application?

**Comment by BoykoDmytro** [comment] 2020-04-04 06:57
Have some issues with ssl in other projects. Again the problem in Keystore on deep debugging, but maybe deeper inside the phone.

**Comment by jpignata** [comment] 2020-04-04 12:16
Got it. I see, it does make an SSL connection eventually, despite the noisy log. It does appear there's some manufacturer specific encryption wonkiness with this particular model as it seems the manufacturer has a track record of compatibility issues from my light reading.

You said there's no error or failure - how does this error manifest itself?

**Comment by BoykoDmytro** [comment] 2020-04-06 09:59
There is an infinity loading cause there is no callback at all.

**Comment by jpignata** [comment] 2020-04-06 11:57
Not sure what the right next step is since I don't have access to a device to take a look. If this is truly an issue with the OS on the device as shipped, it seems reasonable that we'd try to detect this issue when it happens and throw an exception.

**Comment by jpignata** [comment] 2020-04-11 02:06
Thanks so much for your report. I'm not sure how we can help here :( I don't have access to this device, and it seems to have compatibility issues around encryption which correlates with your bug report. Unless you have reports of this happening on other devices, or a suggestion for a fix, I'm going to close this for now.

**Closed by jpignata** 2020-04-11 02:06 UTC
Labels: Bug, Core
