### ISSUE TITLE
Cognito Sync - OutOfMemoryError 

### ISSUE THREAD

**Issue by EnterPrayz** [aws-amplify/aws-sdk-android#675] opened 2019-01-25 11:12 UTC
**Describe the bug**
Hi!. Every time in my crashlytics appear OutOfMemoryError  in com.amazonaws.mobileconnectors.cognito.internal.storage.SQLiteLocalStorage.cursorToDatasetMetadata (SQLiteLocalStorage.java:350) method. What could cause a bug?

![image](https://user-images.githubusercontent.com/7173595/51741641-2dfe2f80-20a0-11e9-9aac-854905504cbf.png)
I'm using
```
"com.amazonaws:aws-android-sdk-core:2.6.14"
"com.amazonaws:aws-android-sdk-cognito:2.6.14"
"com.amazonaws:aws-android-sdk-ddb:2.6.14"
"com.amazonaws:aws-android-sdk-ddb-mapper:2.6.14"
```

**Which AWS service(s) are affected?**
com.amazonaws.mobileconnectors.cognito.internal.storage.SQLiteLocalStorage

**Device Information (please complete the following information):**
 - Device: Redmi Note 4,Redmi Note 5,Redmi Note 4 Pro,MI 5s Plus,Galaxy S5,LG G4,
Galaxy J5(2016), Galaxy S8, Galaxy A3(2016),Ulefone S8 Pro,Blackview BV6000,Galaxy S8  Y5 2017
 - Android Version: 6-8

**Comment by cbommas** [comment] 2019-01-25 20:07
@EnterPrayz 

Couple of questions
1) Can you try to reproduce this issue using the latest version of the SDK v2.11.0
2) Also, can you provide any details of how you are using Cognito in your app to help debug this further?

**Comment by EnterPrayz** [comment] 2019-01-30 20:18
>Can you try to reproduce this issue using the latest version of the SDK v2.11.0

Ok i will change version to  v2.11.0, but i need some time to collect information from user devices

>Also, can you provide any details of how you are using Cognito in your app to help debug this further?

First off all i'm using `CognitoCachingCredentialsProvider` with my custom `CognitoDeveloperIdentityProvider` whos extend `AWSAbstractCognitoDeveloperIdentityProvider` it was configured with `sessionDuration` = 7 days (`setSessionDuration()`). `IdentityProvider` is using by AmazonS3Client too - for generating public urls on my cloud files.

It seem like that

```
private CognitoSyncManager syncClient;
private CognitoCachingCredentialsProvider credentialsProvider;
private MyCognitoDevelopProvider developerIdentityProvider;
...
private void ini(String identifyPoolID, String identifyToken){
        if (syncClient == null) {
            developerIdentityProvider = new NimbusCognitoDevelopProvider(BuildConfig.COGNITO_USER_POOL_ID, identifyPoolID, identifyToken, Regions.US_EAST_1);
            credentialsProvider = new CognitoCachingCredentialsProvider(context, developerIdentityProvider, region);

            syncClient = new CognitoSyncManager(context, region, credentialsProvider);
        } else {
            developerIdentityProvider.updateTokens(identifyToken, identifyPoolID);
        }

        Map<String, String> logins = credentialsProvider.getLogins();
        if (logins == null) {
            logins = new HashMap<String, String>();
        }
        logins.put(developerIdentityProvider.getProviderName(), identifyToken);
        credentialsProvider.setLogins(logins);

        credentialsProvider.setSessionDuration(60 * 60 * 24 * 7);//7 days
        credentialsProvider.getSessionCredentitalsExpiration();// my hack ))) - if passed time> 7 days will be throw `NotAuthorizedException`, after that i'm refresh `identifyToken`
}
```
```
public class MyCognitoDevelopProvider extends AWSAbstractCognitoDeveloperIdentityProvider {
    private String identityToken;
    private String identityId;

    public MyCognitoDevelopProvider(String poolId, String identityPoolId, String token, Regions region) {
        super(null, poolId, region);
        this.identityId = identityPoolId;
        this.identityToken = token;
    }

    public void updateTokens(String identityToken, String identityId) {
        this.identityToken = identityToken;
        this.identityId = identityId;
        refresh();
    }

    @Override
    public String getIdentityId() {
        return identityId;
    }

    @Override
    public String refresh() {
        setToken(null);
        update(identityId, identityToken);
        return token;
    }

    @Override
    public String getProviderName() {
        return "my_some_proveder_name";
    }
}
```
When i have valid session, i begin the initialization of `DynamoDBMapper` 
        `new DynamoDBMapper(new AmazonDynamoDBClient(getCredentialsProvider()), new DynamoDBMapperConfig(new MyPrettyTableNameResolver()));`


By the way i was a little modified AmazonS3Client ))) More accurately -  [this](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/S3HttpUtils.java)
![image](https://user-images.githubusercontent.com/7173595/52008068-86866000-24d8-11e9-9319-76a55aa8402c.png) (left path - my code/right - from github)
And my GeneratePresignedUrlRequest seems like `new GeneratePresignedUrlRequest(bucketName, objectKey.replaceAll(" ", "+"))`, android 5  doesn't replace whitespace automatically.
I hope you understand why I did it

**Comment by minbi** [comment] 2019-02-08 16:46
Hi @EnterPrayz ,

Are you using `CognitoSyncManager` anywhere in your code? The exception is coming from the Cognito Sync library aka `aws-android-sdk-cognito`

**Comment by EnterPrayz** [comment] 2019-02-11 12:30
> Are you using `CognitoSyncManager` anywhere in your code?

Yes, it using for getting `DataSet` 
```
 favoritesDataSet = syncClient.openOrCreateDataset("Favorites");
 favoritesDataSet.synchronizeOnConnectivity(new DefaultSyncCallback());
```

> The exception is coming from the Cognito Sync library aka `aws-android-sdk-cognito`

http://crashes.to/s/9fd13740f3d . 
If you look at the stacktrace, you can see that the initial process somewhere began from the depths of your library. At least the method call did not occur from the `app` module of the program.

**Comment by muellerfr** [comment] 2019-03-07 21:12
Hi @EnterPrayz, CognitoSync has been [deprecated](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-sync.html). We will take a look at the issue and attempt to fix it, but in the meantime we would encourage you to take a look at AWS AppSync.

**Comment by minbi** [comment] 2019-04-04 19:42
Hi,

We are closing this issue because a recommendation has been made about the deprecated library. Please feel free to open a new issue for other problems. We ask this because closed issues are not actively monitored.

Thanks

**Closed by minbi** 2019-04-04 19:42 UTC
Labels: Bug, Cognito
