### ISSUE TITLE
AuthClient throws error when missing Chrome CustomTabs

### ISSUE THREAD

**Issue by jia-tse-zocdoc** [aws-amplify/aws-sdk-android#539] opened 2018-10-05 14:15 UTC
On a device that has chrome browser uninstalled or disabled, I get this error from the `AuthClient`

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { 
act=android.intent.action.VIEW dat=... flg=0x50000000 pkg=com.android.chrome 
launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } (has extras) }
```

Any suggested work around for this?

**Comment by kvasukib** [comment] 2018-10-08 18:32
@jia-tse-zocdoc Sorry for the inconvenience caused. AWS SDK for Android - CognitoAuth relies on Chrome Custom Tabs for the Hosted UI.  We have a strong dependency on the Chrome Custom Tabs library.

**Comment by jia-tse-zocdoc** [comment] 2018-10-08 20:15
@kvasukib -- what is the suggested workflow for those users who don't have chrome tabs enabled?

**Comment by CameliaTripon** [comment] 2020-05-05 09:53
Any news on this topic?
We really need it to work with any browser because the company which wants to use this has its own secure browser and also because it will also be used in China, where Google Chrome is not that used.

**Comment by ekmwilson** [comment] 2020-06-08 22:54
I'm also curious on a resolution of this topic. My team also needs it to work on devices that may have disabled Chrome.

**Comment by pantareh** [comment] 2020-06-09 14:13
Also curious..

**Comment by CameliaTripon** [comment] 2020-06-25 09:26
Guys, please let us know what we can do about this issue. For our customers is really important to be able to use it without Google Chrome because it will be highly used in China and also the new Huawei devices don't support Google Chrome anymore

**Comment by jereld** [comment] 2020-09-24 18:13
I'm seeing many users running in to this problem too.

It can be easily reproduced by disabling Chrome through Chrome's app info screen.

According to the documentation custom tabs supports most browsers
https://developers.google.com/web/android/custom-tabs/implementation-guide

I don't have any experience with the custom tabs library but it looks like this line is specifying that the intent should only be handled by the Chrome browser
https://github.com/aws-amplify/aws-sdk-android/blob/6c63c5a194d8be06d9a82c65d2d56166bac3e008/aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/AuthClient.java#L601

Would it be possible to allow other browsers to handle this intent? Or catch the ActivityNotFoundException and use a webview?

**Comment by TrekSoft** [comment] 2020-09-29 14:51
Given the interest on this I'll add the feature request to our backlog to consider and as we get more +1s on this can investigate the level of effort to add support for other browsers.

**Comment by TrekSoft** [comment] 2020-10-15 14:38
Just merged the implementation for this - it will go out in the next release. 

I'll post some instructions for using it here when that's deployed.

**Comment by jamesonwilliams** [comment] 2020-10-21 16:26
@TrekSoft Is this fix in https://github.com/aws-amplify/aws-sdk-android/releases/tag/release_v2.19.1?

**Comment by TrekSoft** [comment] 2020-10-22 14:14
Yes it is! To use this feature, you can set the new option inside either SignInUIOptions or SignOutOptions to the browser package you want to use instead of Chrome. 

```java
SignInUIOptions signInUIOptions = SignInUIOptions.builder()
                .hostedUIOptions(<your hosted UI options object here>)
                .browserPackage("org.mozilla.firefox")
                .build();

SignOutOptions.builder().browserPackage("org.mozilla.firefox").invalidateTokens(true).build()
```

Note that the browser you choose must support custom tabs. Here is a code snippet that can identify which browsers are present on the device (if any) which support custom tabs.

```java
public static ArrayList<ResolveInfo> getCustomTabsPackages(Context context) {
        PackageManager pm = context.getPackageManager();
        // Get default VIEW intent handler.
        Intent activityIntent = new Intent()
                .setAction(Intent.ACTION_VIEW)
                .addCategory(Intent.CATEGORY_BROWSABLE)
                .setData(Uri.fromParts("http", "", null));

        // Get all apps that can handle VIEW intents.
        List<ResolveInfo> resolvedActivityList = pm.queryIntentActivities(activityIntent, 0);
        ArrayList<ResolveInfo> packagesSupportingCustomTabs = new ArrayList<>();
        for (ResolveInfo info : resolvedActivityList) {
            Intent serviceIntent = new Intent();
            serviceIntent.setAction(ACTION_CUSTOM_TABS_CONNECTION);
            serviceIntent.setPackage(info.activityInfo.packageName);
            // Check if this package also resolves the Custom Tabs service.
            if (pm.resolveService(serviceIntent, 0) != null) {
                packagesSupportingCustomTabs.add(info);
            }
        }
        return packagesSupportingCustomTabs;
    }
```

**Closed by TrekSoft** 2020-10-22 14:14 UTC
Labels: Cognito, Feature Request

**Comment by camhart** [comment] 2020-11-25 18:06
@TrekSoft `signInWithWebUI` is still affected by this, and appears to not accept `SignOutOptions`.  Am I missing something?

**Comment by TrekSoft** [comment] 2020-11-25 21:14
Yeah that's Amplify Auth - different from AWSMobileClient. So your comment on this issue is the correct issue to be discussing that on: https://github.com/aws-amplify/amplify-android/issues/678

**Comment by phanisaripalli** [comment] 2021-06-20 14:59
Suggestiong by @TrekSoft works nicely. For e.g. one approach is query the supported browsers and use an available browser. But the problem is going forward with using for Android TV where Webview is available but Custom Tabs is not guaranteed.  Giving an option to use Webview or alternative way will be nice.
