### ISSUE TITLE
S3 TransferUtility: Lower the minimum notification threshold of 128KB

### ISSUE THREAD

**Issue by hipwelljo** [aws-amplify/aws-sdk-android#611] opened 2018-12-12 21:50 UTC
**Describe the bug**
I am utilizing the TransferUtility to upload a file and using TransferObserver to set a TransferListener to be informed of state changes, progress changes, and any errors should one occur. The file is uploading successfully, however I am not being informed of any upload progress aside from 0% and 100%. (The callback is often triggered multiple times for the same percentage which is already being tracked in issue #406.) As you can see here, I am getting no progress aside from started/finished.
```
12-12 14:04:21.080 10585-10585/com.x.x D/RestHelper: Upload state changed to IN_PROGRESS
12-12 14:04:21.080 10585-10585/com.x.x D/RestHelper: ID:9 bytesCurrent: 0 bytesTotal: 35980 0%
12-12 14:04:30.507 10585-10585/com.x.x D/RestHelper: ID:9 bytesCurrent: 35980 bytesTotal: 35980 100%
12-12 14:04:30.523 10585-10585/com.x.x D/RestHelper: ID:9 bytesCurrent: 35980 bytesTotal: 35980 100%
12-12 14:04:30.523 10585-10585/com.x.x D/RestHelper: ID:9 bytesCurrent: 35980 bytesTotal: 35980 100%
12-12 14:04:30.523 10585-10585/com.x.x D/RestHelper: Upload state changed to COMPLETED
```

**To Reproduce**
1. Attempt to upload a file and log the upload progress (while on a slow connection so it takes some time)

**Which AWS service(s) are affected?**
AWS S3 TransferUtility

**Expected behavior**
Progress should be reported as bytes are uploaded

**Screenshots**
None

**Environment(please complete the following information):**
 - SDK Version: 2.9.0

**Device Information (please complete the following information):**
 - Device: Emulator - Pixel API 22
 - Android Version: 5.1.1
 - Specific to simulators: Have not tried physical device yet

**Code**
```
        TransferUtility transferUtility =
                TransferUtility.builder()
                        .context(context.getApplicationContext())
                        .awsConfiguration(AWSMobileClient.getInstance().getConfiguration())
                        .s3Client(new AmazonS3Client(AWSMobileClient.getInstance()))
                        .build();

        final String filename = "image_" + randomAlphaNumeric(10) + ".jpg";

        File file = scaleImage(uri, context.getCacheDir().getPath() + File.separator + filename);

        TransferObserver transferObserver = transferUtility.upload("bucketname", filename, file);
        transferObserver.setTransferListener(new TransferListener() {
            @Override
            public void onStateChanged(int id, TransferState state) {
                Log.d(TAG, "Upload state changed to " + state);
            }

            @Override
            public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
                float percentDonef = ((float) bytesCurrent / (float) bytesTotal) * 100;
                int percentDone = (int)percentDonef;

                Log.d(TAG, "ID:" + id + " bytesCurrent: " + bytesCurrent
                        + " bytesTotal: " + bytesTotal + " " + percentDone + "%");
            }

            @Override
            public void onError(int id, Exception ex) {
                Log.e(TAG, ex);
            }
        });
```

If helpful, this is how I initialize it in my startup activity:
```
AWSMobileClient.getInstance().initialize(getApplicationContext(), new Callback<UserStateDetails>() {
            @Override
            public void onResult(UserStateDetails result) {
                Log.d(TAG, "AWSMobileClient initialized. User State is " + result.getUserState());

                TransferUtility transferUtility =
                        TransferUtility.builder()
                                .context(getApplicationContext())
                                .awsConfiguration(AWSMobileClient.getInstance().getConfiguration())
                                .s3Client(new AmazonS3Client(AWSMobileClient.getInstance()))
                                .build();
                transferUtility.resumeAllWithType(UPLOAD); //resume any uploads that were paused on app termination
            }

            @Override
            public void onError(Exception e) {
                Log.e(TAG, "Initialization error.", e);
            }
        });

        getApplicationContext().startService(new Intent(getApplicationContext(), TransferService.class));
```

(As an aside, is there a way to get the already initialized transfer utility later when I go to upload? Is it creating two different transferUtilitys as it is now?)

**Other Info**
I have also tried configuring the client to change the notification threshold to see if that would cause more progress to be reported but I still only see 0% and 100%.
```
AmazonS3Client client = new AmazonS3Client(AWSMobileClient.getInstance());
client.setNotificationThreshold(10);
```

To simulate slow network conditions, I enabled the network link conditioner on macOS to simulate an edge data connection, so the file doesn't upload quickly.

**Comment by sunchunqiang** [comment] 2018-12-12 23:39
Hi @hipwelljo 

Thanks your reporting. I have a question for the issue.
How large are the files you uploaded?

**Comment by hipwelljo** [comment] 2018-12-13 22:23
I am now trying this on a physical device (Google pixel android 7.1.2) and I see the same behavior with about a 0.15 MB photo. However, I tried a 1.6 MB photo and it did report progress in-between 0 and 100. Is there a way to reliably get progress updates if the file is small yet the internet connection isn't great?

**Comment by sunchunqiang** [comment] 2018-12-14 19:52
This appears to be a limitation in our code that doesn't allow setting the granularity very well. We will investigate enabling finer granularity progress reporting and update this thread.

**Comment by kvasukib** [comment] 2019-01-18 00:36
@hipwelljo Just wanted to know if this issue is still persistent after customizing the notification threshold?

**Comment by hipwelljo** [comment] 2019-01-18 00:51
Yes, I’ve set it to 10 currently.

**Comment by kvasukib** [comment] 2019-02-04 19:34
@hipwelljo The minimum notification threshold that `AmazonS3Client` supports in 128KB. This is because in our HTTP Client in Core Runtime of the SDK, the buffer size is set to 128KB. That's the reason why you did not get an update for files of size 100KB.

**Comment by kvasukib** [comment] 2019-02-04 19:35
Besides that, `2.11.1` version of the SDK contains improved exception handling and pause/resume handling and fixes the progress reporting issue when a transfer is paused and resumed.

Root cause analysis: 

1) When a transfer is paused by the user or due to network drop, the thread that is managing the multipart transfer is interrupted. When the thread is interrupted and encounters an exception, there is a case where we skip setting the transfer to `PAUSED` or `WAITING_FOR_NETWORK`, and instead moves to `FAILED`. 

2) When a transfer is paused by the user or due to network drop, the thread that is managing the multipart transfer is interrupted. When a multi-part transfer (N parts) is interrupted, there are X number of parts that may have been completed, Y number of parts that may been in progress and Z number of parts that are yet to be started (X + Y + Z = N). When a part that is in progress is interrupted, and then resumed at a later point, the part is retried from the beginning, however the progress made in the previous attempt that is interrupted is not reset from the total progress. This caused the progress reported to go over 100%.

Description of the fix:

The fix involves 

1) improving the exception handling of transfers: 
Improved the state, progress and error reporting when the transfers are interrupted.
* When the transfer is paused or cancelled by the user, the state is reported correctly.
* When the transfer is interrupted because of a network drop, the state is set to `WAITING_FOR_NETWORK` when the `TransferNetworkLossHandler` is used.
* When the transfer is interrupted otherwise, the transfer is set to `FAILED` and the exception is reported via `TransferListener.onError` callback.

2) Fix the progress reporting to not go beyond 100% and reset when a part failed. 

See [2.11.1](https://github.com/aws-amplify/aws-sdk-android/releases/tag/release_v2.11.1) for more information.

**Comment by hipwelljo** [comment] 2019-02-12 17:51
Gotcha. Is there a way to reduce that buffer size? It seems our photos are generally within the range of 50-100 KB.

**Comment by kvasukib** [comment] 2019-02-12 18:03
@hipwelljo Unfortunately, the current minimum that the SDK supports in 128KB.

**Comment by hipwelljo** [comment] 2019-02-12 18:04
Ok! Then this can be marked enhancement request instead of bug ;)

**Comment by kvasukib** [comment] 2019-02-12 18:08
@hipwelljo I have made the necessary modifications to the title and the state of the issue. Thank you!

**Comment by gpanshu** [comment] 2022-05-06 19:22
Checking in here as this issue is now more than 2 years old and Android devices do not take pictures anymore that are lower than 128KB. I am going to go ahead and close this issue as a "Wont do" based on what Kvasukib mentioned and the limitations. Feel free to reopen if this still persists.

**Closed by gpanshu** 2022-05-06 19:22 UTC
Labels: feature-request, s3
