### ISSUE TITLE
AndroidPubSub Sample does not work!!!

### ISSUE THREAD

**Issue by muellerfr** [aws-amplify/aws-sdk-android#719] opened 2019-02-22 23:47 UTC
This issue was originally opened by @iwwork as a PR in the sample app repo:
https://github.com/awslabs/aws-sdk-android-samples/pull/308

**Which AWS Services are you utilizing?**
AWS IoT

**Provide code snippets (if applicable)**
Followed the instruction https://github.com/awslabs/aws-sdk-android-samples/tree/master/AndroidPubSub to set the parameter on the AWS cloud

Downloaded the whole code from https://github.com/awslabs/aws-sdk-android-samples

Used Android Studio 3.3.1 to open the folder AndroidPubSub

Changed the following part
PubSubActivity.java
// IoT endpoint
// AWS Iot CLI describe-endpoint call returns: XXXXXXXXXX.iot..amazonaws.com
private static final String CUSTOMER_SPECIFIC_ENDPOINT = "REPLACE_ME";
// Name of the AWS IoT policy to attach to a newly created certificate
private static final String AWS_IOT_POLICY_NAME = "REPLACE_ME";

awsconfiguration.json
"PoolId": "REPLACE_ME",
"Region": "Regions.US_EAST_1"

Sync, Build and Run App on emulator9.0 or Mobile Phone8.0, the result in Logcat is

```
com.amazonaws.demo.androidpubsub W/o.androidpubsu: Verification of com.amazonaws.logging.Log com.amazonaws.logging.LogFactory.getLog(java.lang.String) took 100.996ms
com.amazonaws.demo.androidpubsub E/com.amazonaws.demo.androidpubsub.PubSubActivity: onError:
java.lang.RuntimeException: Failed to initialize Cognito Identity; please check your awsconfiguration.json
at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:402)
at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalArgumentException: Failed to read CognitoIdentity please check your setup or awsconfiguration.json file
at com.amazonaws.auth.CognitoCredentialsProvider.getRegions(CognitoCredentialsProvider.java:195)
at com.amazonaws.auth.CognitoCredentialsProvider.(CognitoCredentialsProvider.java:174)
at com.amazonaws.auth.CognitoCachingCredentialsProvider.(CognitoCachingCredentialsProvider.java:228)
at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:400)
at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101) 
at java.lang.Thread.run(Thread.java:764) 
Caused by: java.lang.IllegalArgumentException: Cannot create enum from Regions.US_EAST_1 value!
at com.amazonaws.regions.Regions.fromName(Regions.java:114)
at com.amazonaws.auth.CognitoCredentialsProvider.getRegions(CognitoCredentialsProvider.java:193)
at com.amazonaws.auth.CognitoCredentialsProvider.(CognitoCredentialsProvider.java:174) 
at com.amazonaws.auth.CognitoCachingCredentialsProvider.(CognitoCachingCredentialsProvider.java:228) 
at com.amazonaws.mobile.client.AWSMobileClient$2.run(AWSMobileClient.java:400) 
at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101) 
at java.lang.Thread.run(Thread.java:764) 
```

Seems that the AWS modules do not work in the App.

How to deal with this problem?
Should there some other code be added?

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.25]

**Device Information (please complete the following information):**
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by iwwork** [comment] 2019-02-25 01:10
@muellerfr Hi Muelle, thanks for your kind help. Could you give some constructive suggestion?

**Comment by desokroshan** [comment] 2019-02-25 01:19
@iwwork Thanks for submitting the issue. Apologies for the inconvenience. I will try to reproduce the issue and get back to you soon.

**Comment by minbi** [comment] 2019-02-25 19:52
Hi @iwwork ,

> awsconfiguration.json
"PoolId": "REPLACE_ME",
"Region": "Regions.US_EAST_1"

If you have `Regions.US_EAST_1` as the region value, please replace it with `us-east-1` instead.

**Comment by iwwork** [comment] 2019-02-26 06:58
@minbi this does not work.

**Comment by minbi** [comment] 2019-02-26 16:34
Can you elaborate or potentially provide a stacktrace?

**Comment by desokroshan** [comment] 2019-02-28 18:07
Sounds like this issue has been resolved as mentioned in https://github.com/aws-amplify/aws-sdk-android/issues/750. Closing this issue.

**Closed by desokroshan** 2019-02-28 18:07 UTC
Labels: IoT, Question, Requesting Feedback

**Comment by XCarbone** [comment] 2020-04-02 14:46
> Hi @iwwork ,
> 
> > awsconfiguration.json
> > "PoolId": "REPLACE_ME",
> > "Region": "Regions.US_EAST_1"
> 
> If you have `Regions.US_EAST_1` as the region value, please replace it with `us-east-1` instead.

this work just write the region in lowercase with - instade of _ and Caused by: java.lang.IllegalArgumentException: Failed to read CognitoIdentity please check your setup or awsconfiguration.json file will be initialise
