### ISSUE TITLE
AWS Cognito Android SDK MFA Authentication Issue

### ISSUE THREAD

**Issue by Goutham-Byteridge** [aws-amplify/aws-sdk-android#764] opened 2019-03-04 07:18 UTC
We are using cognito android sdk to authenticate against the Microsoft IDP via SAML 2.0 protocol. IDP has a call based MFA enabled. When the user receives a phone call in his device and user answers it, phone activity opens and app goes to background and webview also got closed as cognito is calling the OnFailure() method. When the user opens the application again, signin page is shown and when user clicks on signin button, webview opens and phone call gets triggered again. The same process happens in an endless loop. Cognito is never returning a success response even after attending the phone call. Whereas the same scenario works perfectly for iOS app.

**Comment by minbi** [comment] 2019-03-05 22:44
Hi @Goutham-Byteridge ,

I think I understand what is happening. The SDK is treating the hiding of the tab as a user cancelled event. We will need to change this behavior to support this use-case.

**Comment by Goutham-Byteridge** [comment] 2019-03-06 05:48
Hi minbi,

We are working on very stringent timelines for one of our projects and this issue is a serious blocker for us to go live. We had already spent 2 weeks on this looking for a resolution. If you could please assist me on fixing this issue on the SDK itself, i will be grateful to you. Or if its a quick fix that you can do immediately, that would be even better. Please let me know whatever is feasible for you.

**Comment by minbi** [comment] 2019-03-06 16:17
Hi @Goutham-Byteridge ,

We do not currently have a solution to resume this using the CustomTab implementation since like you said the tab is dismissed. Programmatically I am not aware of a way to prevent the dismissal. There may be a way to use WebView since that *might* have a tighter "bind" to the activity and not be dismissed, but we do not have an implementation. We are open to pull requests, so if you find a solution we would review it. I will escalate this, but we may not be able to resolve this issue.

**Comment by ekmwilson** [comment] 2020-06-08 22:55
Any update on this feature request in terms of whether it is on the roadmap? This limitation makes it almost impossible to implement MFA using Hosted UI.

**Comment by TrekSoft** [comment] 2020-06-09 18:23
For those reading this issue, reposting my reply on the Amplify ticket:

"for HostedUI, Chrome Tabs are a necessity because they have a lot of functionality which isn't feasible for us to rewrite if we were using a webview. The issue of it closing when there's an incoming phone call is definitely a problem and we actually just had a user [report a potential fix](https://github.com/aws-amplify/aws-sdk-android/issues/871#issuecomment-641351186) we could implement which I plan to look into."

**Comment by TrekSoft** [comment] 2020-07-06 19:50
Heads up @ekmwilson and others that I'm starting work on this issue now so hope to have a resolution soon.

**Comment by TrekSoft** [comment] 2020-07-08 20:16
Found a solution which we plan to prioritize getting implemented soon here. We'll keep this issue updated on the progress.

**Comment by TrekSoft** [comment] 2020-07-21 14:17
Yup, it should address that as well. The work has been scheduled for this sprint so we'll give an update when it's completed.

**Comment by nicholas-cook** [comment] 2020-08-13 14:14
@TrekSoft Thanks for your PR! In preparation for the next release of this SDK, we went ahead and pulled down the `develop` branch with the changes from your PR to see if they would solve our issue.

We’re actually still seeing issues with logging in via 2FA. There seems to be a timing issue where if the user doesn’t move back to our app from their 2FA app quickly enough, they end up stuck on an empty custom tab.

We believe this is happening because after the user confirms their 2FA, the custom tab continues its auth flow in the background while the 2FA app is in the foreground. Because the tab is in the background, the implicit intent with the scheme `authRedirectScheme` never gets fired, meaning that `CustomTabsRedirectActivity` is never started. This doesn’t happen if the user moves immediately back to our app after confirming 2FA instead of waiting for the 2FA app to finish itself.

This appears similar to [this issue](https://github.com/openid/AppAuth-Android/issues/135).

Do you know of any workarounds or solutions for this?

**Comment by TrekSoft** [comment] 2020-08-13 14:55
Hmm, yeah so looking at that issue and based on what you're describing, this sounds like a bug outside our control. How the Cognito HostedUI website works is separate code owned by the Cognito team and based on that ticket, this would be an issue that would need to be handled either by their code or by the Chrome Custom Tabs team. 

Have you considered a different method of 2FA where the user inputs a code given to them so as to avoid this issue?

**Comment by nicholas-cook** [comment] 2020-08-13 16:04
We're locked into the 2FA app that our client uses. It does have a code option, but most people use a push notification to confirm login. If they confirm straight from the push, it works fine. The issue is with users opening the 2FA app from the push and confirming in app.

**Comment by TrekSoft** [comment] 2020-08-14 14:21
Gotcha - yeah this would be something you'd need to take up with Cognito to see if there's something inside the HostedUI code that could be done to support this use case since Chrome tabs apparently don't support calling a deep link while backgrounded.

**Comment by michaelmwhite** [comment] 2020-08-14 19:28
@nicholas-cook and I are on the same team - we were able to create a work around for this issue by modifying our redirect uri to point to a page in our web app. This page has a button which will link the user to the authentication uri that cognito provides. Clicking this button will trigger an intent that's handled by our app, and the user can successfully log in and out. Thanks for being responsive on this issue.

**Comment by TrekSoft** [comment] 2020-08-17 14:20
That's awesome - thanks for sharing that workaround so we can provide that info to others as well.

**Comment by TrekSoft** [comment] 2020-08-19 14:06
For everyone's information, this has now been resolved in the latest release - 2.18.0. You'll need to follow the updated documentation here to use the fixed implementation of HostedUI: https://docs.amplify.aws/sdk/auth/hosted-ui/q/platform/android#setup-amazon-cognito-hosted-ui-in-android-app

**Closed by TrekSoft** 2020-08-19 14:06 UTC
Labels: Cognito, Feature Request
