### ISSUE TITLE
NoClassDefFoundError: org/apache/commons/logging/LogFactory

### ISSUE THREAD

**Issue by emumair** [aws-amplify/aws-sdk-android#476] opened 2018-06-08 05:38 UTC
* What service are you using?
**Mobile Analytics**

* In what version of SDK are you facing the problem?
`implementation 'com.amazonaws:aws-android-sdk-core:2.4.2'`
`implementation 'com.amazonaws:aws-android-sdk-mobileanalytics:2.4.2'`

* Is the issue limited to Simulators / Actual Devices?
**No**

* Can your problem be resolved if you bump to a higher version of SDK?
**No**

* Is this problem related to specific Android/OS version?
**Yes, API level 28**

Runs well on version <= 27 but throws exception when app is run on version 28.

Crash occurs at:

`CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(context, BuildConfig.AMAZON_IDENTITY_POOL_ID, region);`

* **Stacktrace**

```
06-07 15:58:10.189 5075-5075 E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/commons/logging/LogFactory;
        at com.amazonaws.util.VersionInfoUtils.<clinit>(VersionInfoUtils.java:41)
        at com.amazonaws.util.VersionInfoUtils.getVersion(VersionInfoUtils.java:54)
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.<clinit>(CognitoCachingCredentialsProvider.java:81)
        at com.umair.myapp.analytics.AmazonMobileAnalytics.initialize(AmazonMobileAnalytics.java:41)
        at com.umair.myapp.MyApplication.onCreate(MyApplication.java:48)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5858)
        at android.app.ActivityThread.access$1000(ActivityThread.java:197)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1634)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6642)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.logging.LogFactory" on path: DexPathList[[zip file "/data/app/com.umair.myapp-n6G1DHuwf6SphItF6XvOPw==/base.apk"],nativeLibraryDirectories=[/data/app/com.umair.myapp-n6G1DHuwf6SphItF6XvOPw==/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:126)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.amazonaws.util.VersionInfoUtils.<clinit>(VersionInfoUtils.java:41) 
        at com.amazonaws.util.VersionInfoUtils.getVersion(VersionInfoUtils.java:54) 
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.<clinit>(CognitoCachingCredentialsProvider.java:81) 
        at com.umair.myapp.analytics.AmazonMobileAnalytics.initialize(AmazonMobileAnalytics.java:41) 
        at com.umair.myapp.MyApplication.onCreate(MyApplication.java:48) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5858) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:197) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1634) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6642) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.umair.myapp-n6G1DHuwf6SphItF6XvOPw==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:377)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:340)
        at dalvik.system.DexPathList.<init>(DexPathList.java:160)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:66)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
06-07 15:58:10.191 5075-5075 E/AndroidRuntime:     at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:727)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:772)
        at android.app.LoadedApk.getResources(LoadedApk.java:994)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2345)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5736)
        		... 8 more
```

Saw a similar issue [here](https://github.com/aws/aws-sdk-android/issues/265) but the given solution is not working for me.

`testCompile 'commons-logging:commons-logging:1.1.1'`
and
`testImplementation 'commons-logging:commons-logging:1.1.1'`
both are not working.

**Comment by minbi** [comment] 2018-06-08 22:59
Hi @emumair ,

Thanks for reporting this issue. Currently, it looks like we may be able to remove this dependency.
We will investigate and reply here when we have more information.

**Comment by minbi** [comment] 2018-06-08 23:00
Also, Mobile Analytics is no longer recommended, please use AWS Pinpoint instead.

**Comment by mseleng** [comment] 2018-06-26 11:19
👍 Same issue here, now with 
`implementation 'com.amazonaws:aws-android-sdk-sns:2.6.23'`

**Comment by elliott-accolade** [comment] 2018-06-28 18:29
Having this issue with both
` api 'com.amazonaws:aws-android-sdk-kinesis:2.2.+'
    api 'com.amazonaws:aws-android-sdk-core:2.2.+'`

and 
`    api 'com.amazonaws:aws-android-sdk-kinesis:2.6.+'
    api 'com.amazonaws:aws-android-sdk-core:2.6.+'

**Comment by karannaik** [comment] 2018-07-07 01:28
Has anyone solved this problem yet?

**Comment by C0lumbo** [comment] 2018-07-26 14:38
I'm also affected by this issue. The crash occurs downstream from the call to `new AWSKinesisFirehose`. I'm using:

`aws-android-sdk-core:2.6.+`
`aws-android-sdk-auth-core:2.6.+`
`aws-android-sdk-kinesis:2.6.+`

Release date for Android P is likely to be 3rd week of August if it follows the pattern of Oreo and Nougat. It would be frustrating if this issue prevented us from using Android P at launch. Thanks.

**Comment by minbi** [comment] 2018-07-30 18:43
Please add dependency for now:

```
implementation 'commons-logging:commons-logging:1.1.1'
```

**Comment by C0lumbo** [comment] 2018-07-31 14:51
`implementation 'commons-logging:commons-logging:1.1.1'`

is working for me, thanks. Initially I had problems in my submission build, I had to add this lot into my proguard rules to get that working.

```
-keep class org.apache.log.** { *; }
-dontwarn org.apache.log.**
-keep class org.apache.log4j.** { *; }
-dontwarn org.apache.log4j.**
-keep class org.apache.avalon.** { *; }
-dontwarn org.apache.avalon.**
-keep class javax.servlet.** { *; }
-dontwarn javax.servlet.**
```

**Comment by charbgr** [comment] 2018-08-07 10:56
We also have this issue. 

Including `implementation 'commons-logging:commons-logging:1.1.1'` will causes other bugs though to other libraries.

**Comment by charbgr** [comment] 2018-08-07 10:57
We also have this issue.

Including implementation 'commons-logging:commons-logging:1.1.1' will causes other bugs to other libraries.

**Comment by elliottj-accolade** [comment] 2018-08-07 16:44
We are having this issue now when attempting to release a signed build:
`Error: commons-logging defines classes that conflict with classes now provided by Android. Solutions include finding newer versions or alternative libraries that don't have the same problem (for example, for httpclient use HttpUrlConnection or okhttp instead), or repackaging the library using something like jarjar. [DuplicatePlatformClasses]
    implementation 'commons-logging:commons-logging:1.1.1'
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   Explanation for issues of type "DuplicatePlatformClasses":
   There are a number of libraries that duplicate not just functionality of
   the Android platform but using the exact same class names as the ones
   provided in Android -- for example the apache http classes. This can lead
   to unexpected crashes.

   To solve this, you need to either find a newer version of the library which
   no longer has this problem, or to repackage the library (and all of its
   dependencies) using something like the jarjar tool, or finally, rewriting
   the code to use different APIs (for example, for http code, consider using
   HttpUrlConnection or a library like okhttp).

1 errors, 0 warnings
:app:lintVitalProdRelease FAILED`

This is including the proguard stuff that C0lumbo recommended.

So we're still stuck releasing for Android Pie and targeting API level 28. Any ETA on getting this fixed, considering that Google just started rolling out Android Pie to Pixel devices, etc?

**Comment by elliottj-accolade** [comment] 2018-08-07 20:12
Also there's this: https://developer.android.com/about/versions/pie/android-9.0-changes-all#apache-nonp

```An app can be affected if it uses a non-standard ClassLoader that explicitly delegates to the system ClassLoader. These apps need to delegate to the app ClassLoader instead when looking for classes in org.apache.http.*. If they delegate to the system ClassLoader, the apps will fail on Android 9 or higher with a NoClassDefFoundError, because those classes are no longer known to the system ClassLoader. To prevent similar problems in the future, apps should in general load classes through the app ClassLoader rather than accessing the system ClassLoader directly.```

**Comment by lucasmpaim** [comment] 2018-08-08 15:14
+1

**Comment by emezias** [comment] 2018-08-10 20:09
I'm using:
api 'commons-logging:commons-logging:1.1.2'
in my dependencies so that the S3 APIs do not fail with the same NoClassDefFound. This is not the right answer.

What about this closed issue?
https://github.com/aws/aws-sdk-android/issues/265

**Comment by emezias** [comment] 2018-08-10 20:26
Android Pie runtime has a crash that's not on earlier Androids. Is anybody at Amazon on a fix for it?

**Comment by roshanrajaratnam** [comment] 2018-08-14 05:31
+1

**Comment by emezias** [comment] 2018-08-14 14:18
almost forgot about this issue - these lines in build.gradle seem to work with the S3 SDK so that the Android P runtime does not crash

 api 'com.amazonaws:aws-android-sdk-core:$version'
    api ('com.amazonaws:aws-android-sdk-s3:$version'){
        exclude module: 'commons-logging:commons-logging:+'
    }

**Comment by dlazaro66** [comment] 2018-08-17 10:35
@minbi I'm having the same issue here; Is there any release coming soon that solves this problem?

**Comment by charbgr** [comment] 2018-08-17 10:48
This is quite blocking!

**Comment by dwaynehoy** [comment] 2018-08-18 03:47
Adding 'commons-logging:commons-logging:1.1.1' as a dependency causes crashes in other libraries like the Google Maps SDK. This is blocking a scheduled release.

**Comment by mauricegavin** [comment] 2018-08-20 14:26
It's blocking us from uploading and downloading files to S3 in production on Android P devices.

**Comment by emezias** [comment] 2018-08-20 21:02
@minbi The problem with locking #265 is that this issue refers to MobileAnalyticsManager while the earlier, closed issue refers to a problem with client initialization. The problem I am experiencing is with the S3 client fetching keys. Developers using the S3 APIs might be led to believe that the NoClassDefFoundError on the S3 client is solved when it is not.

**Comment by minbi** [comment] 2018-08-20 23:11
@emezias , correct me if I am wrong, but aren't these both related to the usage of commons logging in the SDK?

**Comment by minbi** [comment] 2018-08-21 00:35
@emezias , we are treating this as the issue for tracking the commons logging issue for all SDKs under AWS Android SDK.

**Comment by emezias** [comment] 2018-08-21 01:16
Thanks @minbi. If that is the case the issue title referring to the
MobileAnalyticsManager is specific and confusing. Can you correct it?
Developers that do not use Amazon for analytics are affected. Issue 265 on
the S3 Amazon client was filed before this one and is still a problem.

**Comment by DrewCarlson** [comment] 2018-08-21 01:16
@minbi It would be valuable in the future to include the reason and more explicit direction when stopping an active conversation.

Additionally if this is to be the primary issue for the bug: updating the title, providing details (in summary) of the root cause, and adding any insight into the status of your investigation would be appreciated.

**Comment by pavlospt** [comment] 2018-08-21 05:26
@minbi any reason why this is taking so long? Is there anything blocking you?

**Comment by dlazaro66** [comment] 2018-08-21 09:44
Also about this: 

> Also, Mobile Analytics is no longer recommended, please use AWS Pinpoint instead.

We tried to migrate to Pinpoint but the same issue seems to be there using the version:
`com.amazonaws:aws-android-sdk-pinpoint:2.6.28`

@minbi As other people said, this issue is blocking everyone to have Android Pie support. If there's anything we can do to help you out, just ping us 👍

**Comment by jiuzhou9** [comment] 2018-08-22 07:17
https://github.com/freedom-java/freedom-java/issues/1
缺少资源包：
<dependency>
  <groupId>commons-logging</groupId>
  <artifactId>commons-logging</artifactId>
  <version>1.2</version>
</dependency>

**Comment by pavlospt** [comment] 2018-08-24 08:54
Any news on the progress of the resolution of this issue?

**Comment by dwaynehoy** [comment] 2018-08-29 02:39
@minbi Can we get some form of update on this issue?

**Comment by nbtk123** [comment] 2018-08-29 18:08
Adding

`implementation group: 'commons-logging', name: 'commons-logging', version: '1.2'`

Solved our problem, but definitely waiting for a fix

**Comment by ygnessin** [comment] 2018-08-31 01:03
@minbi this is blocking us and many other developers from adding support for Android P. Is a fix in the works?

This is not just Mobile Analytics related. In the app I'm working on, we are using Kinesis and Cognito only, and it is still occurring.

Thanks for investigating!

**Comment by laramartin** [comment] 2018-08-31 08:47
This issue is blocking us as well from supporting Android P. Any news on the status of the fix would be greatly appreciated!

**Comment by pavlospt** [comment] 2018-08-31 12:40
Am I the only one that I don't find anything related to apache logging in that release tag?

**Comment by laramartin** [comment] 2018-08-31 12:45
@pavlospt you're not alone, it wasn't fixed in the release v2.6.29, it still uses it :(

**Comment by minbi** [comment] 2018-08-31 17:45
Hi everyone,

We are working on a fix for this issue. Please see #521 for a preview of the change and to post any comments or bug reports about the fix.

**Comment by pavlospt** [comment] 2018-08-31 18:02
@minbi Great! Is there any ETA on releasing this?

**Comment by m00head** [comment] 2018-08-31 21:27
I was using https://github.com/aws/aws-sdk-android/issues/265#issuecomment-411978696 as a workaround for an Android app with a Cognito dependencyuntil release v2.6.29, after which the workaround is no longer required.

**Comment by ericpearson** [comment] 2018-09-04 14:56
this is pathetic support amazon, what gives, there are a ton of angry devs here and you won't even accept a patch

**Comment by kvasukib** [comment] 2018-09-07 18:18
Description of the fix: We introduced a LogFactory and Log interface in the SDK (aws-android-sdk-core) and made Apache Commons Logging and android.util.Log as implementations of the Log interface. By default, the LogFactory checks if Apache Commons Logging is present, if so, it will use the Commons Logging as the logger, else it will use android.util.Log.

Customers who want to use Apache Commons Logging can import it as an explicit dependency and LogFactory will use it. Please feel free to provide feedback on this fix. We will be happy to take in the recommendations. Closing the issue.

**Comment by minbi** [comment] 2018-11-08 20:49
@AnthonyUccello Do you need commons logging for your project? If not, then you can let it default to Android logging instead.

**Comment by AnthonyUccello** [comment] 2018-11-08 21:01
I spoke too soon, my build server threw this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lint'.
> Lint found errors in the project; aborting build.

 Fix the issues identified by lint, or add the following to your build script to proceed with errors:
 ...
 android {
     lintOptions {
         abortOnError false
     }
 }
 ...

 Errors found:

 /godata/pipelines/android-pr/app/build.gradle:263: Error: commons-logging defines classes that conflict with classes now provided by Android. Solutions include finding newer versions or alternative libraries that don't have the same problem (for example, for httpclient use HttpUrlConnection or okhttp instead), or repackaging the library using something like jarjar. [DuplicatePlatformClasses]
     implementation 'commons-logging:commons-logging:1.1.1'
```

@minbi Can you clarify how I let it default to Android logging instead? This is failing when I try to mock an object

**Comment by AnthonyUccello** [comment] 2018-11-08 21:10
The issue is, in the VersionInfoUtils there are missing libraries:

<img width="589" alt="screen shot 2018-11-08 at 4 09 41 pm" src="https://user-images.githubusercontent.com/3809669/48227610-c5d96080-e370-11e8-83d3-cfa9d8061302.png">

**Comment by kvasukib** [comment] 2018-11-08 22:29
@AnthonyUccello Can you upgrade to the latest 2.7.+ and see if it fixes the issue? We fixed this issue in `2.6.30`.

**Comment by minbi** [comment] 2018-11-08 22:31
@emumair This is how the code branches the logic [if else](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-core/src/main/java/com/amazonaws/logging/LogFactory.java#L39). Remove that dependency. We only included the option to go to commons logging for those that *need or depend* on functionality provided by commons logging.

**Comment by danielesegato** [comment] 2018-12-18 08:38
Guys the proper workaround is the same you need for using Google Maps:

Add this inside your Application in the App manifest

```
        <uses-library
            android:name="org.apache.http.legacy"
            android:required="false"/>
```

still has to be fixed in the library.

**Comment by sauravpradhan** [comment] 2020-09-21 05:12
I am using : implementation 'com.amazonaws:aws-android-sdk-s3:2.19.0' and can still see the issue. Can anyone here let me know if this was fixed and released ?

**Comment by raphkim** [comment] 2020-09-21 17:04
Hi @sauravpradhan ,
Thank you for letting us know regarding this issue. Looks like the bug got resurfaced after our recent dependency cleanup. We will investigate a fix for the next release.

**Comment by jamesonwilliams** [comment] 2020-09-21 17:43
@sauravpradhan @raphkim Ah yes. In #2014, I set out to remove our dependency on the Apache HTTP client. As part of that, I've removed this line from the `aws-android-sdk-core`:
```gradle
useLibrary 'org.apache.http.legacy'
```

I suspect that this has removed the _logging_ dependency from the runtime classpath, as well.

Some workarounds for the consumer are suggested in [this StackOverflow thread](useLibrary 'org.apache.http.legacy').

I believe our next step here will be to remove the Apache Logging dependency entirely.

**Comment by sauravpradhan** [comment] 2020-09-21 17:53
I cannot move to a SDK < 28, more over the problem is when we progaurd the app. Debug apk and non progaurded relase apk's are fine . Adding the implementation of commons or even including jar did not work out for me. And since it was fixed long back , I was really looking for my project configs as all comments suggested it's fixed. @raphkim Thanks for reopening this.

**Comment by jamesonwilliams** [comment] 2021-02-18 22:03
All references to Apache Logging have been removed from the SDK as of https://github.com/aws-amplify/aws-sdk-android/releases/tag/release_v2.19.4. If you are encountering issue #476, the current recommendation is to update to the latest version of the SDK.

**Closed by jamesonwilliams** 2021-02-18 22:03 UTC

**Comment by jarve** [comment] 2021-08-23 14:10
No android. Latest version of your SDK today: 2.17.24.  Just plain java and very easy code  S3Client s3 = S3Client.builder()
                .region(Region...)build();
 ListBucketsResponse listBucketsResponse = s3.listBuckets();
        listBucketsResponse.buckets().stream().forEach(x -> System.out.println(x.name()));
and
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
	at org.apache.http.conn.ssl.AbstractVerifier.<init>(AbstractVerifier.java:61)
	at org.apache.http.conn.ssl.AllowAllHostnameVerifier.<init>(AllowAllHostnameVerifier.java:44)
	at org.apache.http.conn.ssl.AllowAllHostnameVerifier.<clinit>(AllowAllHostnameVerifier.java:46)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:151)
	at software.amazon.awssdk.http.apache.ApacheHttpClient$ApacheConnectionManagerFactory.getPreferredSocketFactory(ApacheHttpClient.java:630)
	at software.amazon.awssdk.http.apache.ApacheHttpClient$ApacheConnectionManagerFactory.create(ApacheHttpClient.java:609)
and adding <dependency>
    <groupId>commons-logging</groupId>
    <artifactId>commons-logging</artifactId>
    <version>1.2</version>
</dependency>
to my pom didn't help. I think it's common problem of the ApacheHttpClient  but I have java 11 with better http client, why are you  still using the apache one? I also used it too in the past but today?

**Comment by jiuzhou9** [comment] 2021-08-24 04:29
You can try it, like this:


<dependency&gt;
  <groupId&gt;org.projectlombok</groupId&gt;
  <artifactId&gt;lombok</artifactId&gt;
  <scope&gt;compile</scope&gt;
</dependency&gt;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Pekka ***@***.***&gt;; 
发送时间: 2021年8月23日(星期一) 晚上10:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aws-amplify/aws-sdk-android] NoClassDefFoundError: org/apache/commons/logging/LogFactory (#476)





 
No android. Latest version of your SDK today: 2.17.24.  Just plain java and very easy code  S3Client s3 = S3Client.builder()
 .region(Region...)build();
 ListBucketsResponse listBucketsResponse = s3.listBuckets();
 listBucketsResponse.buckets().stream().forEach(x -&gt; System.out.println(x.name()));
 and
 Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
 at org.apache.http.conn.ssl.AbstractVerifier.(AbstractVerifier.java:61)
 at org.apache.http.conn.ssl.AllowAllHostnameVerifier.(AllowAllHostnameVerifier.java:44)
 at org.apache.http.conn.ssl.AllowAllHostnameVerifier.(AllowAllHostnameVerifier.java:46)
 at org.apache.http.conn.ssl.SSLConnectionSocketFactory.(SSLConnectionSocketFactory.java:151)
 at software.amazon.awssdk.http.apache.ApacheHttpClient$ApacheConnectionManagerFactory.getPreferredSocketFactory(ApacheHttpClient.java:630)
 at software.amazon.awssdk.http.apache.ApacheHttpClient$ApacheConnectionManagerFactory.create(ApacheHttpClient.java:609)
 and adding 
 commons-logging
 commons-logging
 1.2
 
 to my pom didn't help. I think it's common problem of the ApacheHttpClient  but I have java 11 with better http client, why are you  still using the apache one? I also used it too in the past but today?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LouieMiddleHawkeye** [comment] 2022-05-13 15:56
> No android. Latest version of your SDK today: 2.17.24. Just plain java and very easy code S3Client s3 = S3Client.builder() .region(Region...)build(); ListBucketsResponse listBucketsResponse = s3.listBuckets(); listBucketsResponse.buckets().stream().forEach(x -> System.out.println(x.name())); and Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory at org.apache.http.conn.ssl.AbstractVerifier.(AbstractVerifier.java:61) at org.apache.http.conn.ssl.AllowAllHostnameVerifier.(AllowAllHostnameVerifier.java:44) at org.apache.http.conn.ssl.AllowAllHostnameVerifier.(AllowAllHostnameVerifier.java:46) at org.apache.http.conn.ssl.SSLConnectionSocketFactory.(SSLConnectionSocketFactory.java:151) at software.amazon.awssdk.http.apache.ApacheHttpClient$ApacheConnectionManagerFactory.getPreferredSocketFactory(ApacheHttpClient.java:630) at software.amazon.awssdk.http.apache.ApacheHttpClient$ApacheConnectionManagerFactory.create(ApacheHttpClient.java:609) and adding commons-logging commons-logging 1.2 to my pom didn't help. I think it's common problem of the ApacheHttpClient but I have java 11 with better http client, why are you still using the apache one? I also used it too in the past but today?

@jarve Did you manage to fix this? I keep getting this trying to start a DynamoDBClient and I'm really stumped as to why.

**Comment by jarve** [comment] 2022-05-16 11:27
No, but I found go program called rclone to use.
