### ISSUE TITLE
JetPack Compose with Amplify - strange Frame Exception

### ISSUE THREAD

**Issue by vbudilov** [aws-amplify/aws-sdk-android#1464] opened 2020-02-03 15:29 UTC
I've been playing around with JetPack Compose and Amplify and for the most part it works seamlessly. The only change I had to make when using the Authentication component is to run all of the code in the UI Thread. So the example below is from the Amplify Docs. The content of the onResult is wrapped in runOnUiThread(), while the onError isn't. Whenever I use the exact same code and pass in a Kotlin lambda to modify the JetPack Compose @Model object I get a Frame exception. If I wrap the contents of the onError in a  runOnUiThread() then everything works. 

I'm not sure if this is an error or bug, nor am I sure that this is an Amplify vs JetPack issue, but wanted to create this issue for visibility. 

https://aws-amplify.github.io/docs/android/authentication#signin

```
AWSMobileClient.getInstance().signIn(username, password, null, new Callback<SignInResult>() {
    @Override
    public void onResult(final SignInResult signInResult) {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                Log.d(TAG, "Sign-in callback state: " + signInResult.getSignInState());
                switch (signInResult.getSignInState()) {
                    case DONE:
                        makeToast("Sign-in done.");
                        break;
                    case SMS_MFA:
                        makeToast("Please confirm sign-in with SMS.");
                        break;
                    case NEW_PASSWORD_REQUIRED:
                        makeToast("Please confirm sign-in with new password.");
                        break;
                    default:
                        makeToast("Unsupported sign-in confirmation: " + signInResult.getSignInState());
                        break;
                }
            }
        });
    }

    @Override
    public void onError(Exception e) {
        Log.e(TAG, "Sign-in error", e);
    }
});
```

Here's the code that works: 

```
data class LoginState(var state: LoginStateEnum? = null, var message: String? = null)


    fun signIn(
        username: String,
        password: String,
        onStateChange: (loginState: LoginState) -> Unit
    ) {
        AWSMobileClient.getInstance().signIn(
            username,
            password,
            null,
            object : Callback<SignInResult> {
                override fun onResult(signInResult: SignInResult) {
                    ThreadUtils.runOnUiThread(Runnable {
                        Log.d(
                            null,
                            "Sign-in callback state: " + signInResult.signInState
                        )
                        when (signInResult.signInState) {
                            SignInState.DONE -> {
                                println("Sign-in done.")
                                onStateChange(LoginState(LoginStateEnum.LOGGED_IN, "Success"))
                            }
                            SignInState.SMS_MFA -> {
                                println("Please confirm sign-in with SMS.")
                                onStateChange(LoginState(LoginStateEnum.SMS_MFA, "Please confirm sign-in with SMS"))
                            }
                            SignInState.NEW_PASSWORD_REQUIRED -> {
                                println("Please confirm sign-in with new password.")
                                onStateChange(LoginState(LoginStateEnum.NEW_PASSWORD_REQUIRED, "Please confirm sign-in with new password"))
                            }
                            else -> println("Unsupported sign-in confirmation: " + signInResult.signInState)
                        }
                    })
                }

                override fun onError(e: java.lang.Exception) {
                    ThreadUtils.runOnUiThread(Runnable {
                        Log.e(TAG, "Couldn't sign in ${e}")
                        onStateChange(LoginState(LoginStateEnum.LOGIN_ERROR, e.message))
                    })
                }
            })
    }
```

**Comment by jamesonwilliams** [comment] 2020-02-07 18:26
Hi @vbudilov, thanks for the report. Can you share the full exception trace?

**Comment by vbudilov** [comment] 2020-02-09 05:31
You'll find it below. Also, [here's the project](https://github.com/vbudilov/jetpack-compose-starter) if you'd like to replicate the exception. You'd want to comment out [this line](https://github.com/vbudilov/jetpack-compose-starter/blob/master/app/src/main/java/com/budilov/starter/service/auth/CognitoAuthService.kt#L194) and try to login with incorrect credentials. 



```
E/AndroidRuntime: FATAL EXCEPTION: Thread-3
    Process: com.budilov.starter, PID: 15663
    java.lang.IllegalStateException: Not in a frame
        at androidx.compose.frames.FramesKt.currentFrame(Frames.kt:180)
        at androidx.compose.ModelMutableState.setValue(MutableState.kt:266)
        at com.budilov.starter.ui.auth.LoginScreenKt$LoginScreen$1$1$invoke$1$1$invoke$1$19$invoke$1$1$1.invoke(LoginScreen.kt:84)
        at com.budilov.starter.ui.auth.LoginScreenKt$LoginScreen$1$1$invoke$1$1$invoke$1$19$invoke$1$1$1.invoke(Unknown Source:3)
        at com.budilov.starter.service.auth.CognitoAuthService$signIn$1.onError(CognitoAuthService.kt:199)
        at com.amazonaws.mobile.client.internal.InternalCallback.call(InternalCallback.java:77)
        at com.amazonaws.mobile.client.internal.InternalCallback.access$000(InternalCallback.java:34)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:103)
        at java.lang.Thread.run(Thread.java:919)
I/chatty: uid=10139(com.budilov.starter) Thread-3 identical 1 line
E/CognitoAuthService: Couldn't sign in java.lang.IllegalStateException: Not in a frame
I/Process: Sending signal. PID: 15663 SIG: 9
```

**Comment by raphkim** [comment] 2020-02-17 19:44
Hi @vbudilov 

Thank you for reaching out to us! It seems that this is less of JetPack issue, as suggested by the similar usage pattern in our [sample app code](https://github.com/awslabs/aws-sdk-android-samples/blob/4aff058a6a5e83b6737bb02f101bf2b1069d2386/AmazonKinesisVideoDemoApp/src/main/java/com/amazonaws/kinesisvideo/demoapp/activity/StartUpActivity.java). 

I will provide an update after discussing with the team whether this is an intended behavior.

**Comment by brady-aiello** [comment] 2020-04-26 23:44
I'd try printing ```Thread.currentThread()``` in both the ```onResult()``` and ```onError()``` callbacks. Composable functions must be called from the UI thread, so that's my first guess. (I'm assuming ```onStateUpdate()``` was a composable function). What you're doing now, by just modifying state directly, is fine, because updating annotated ```@model```'s is thread-safe.

**Comment by richardmcclellan** [comment] 2021-06-16 20:19
Closing, as this is intended behavior, as illustrated by the sample app.

**Closed by richardmcclellan** 2021-06-16 20:19 UTC
Labels: AWSMobileClient
